<%
  import math
  p_name = config.project.name
  
  # 1. Ricava le dimensioni massime della griglia
  comps = [config.host] + config.components
  max_x, max_y = 0, 0
  
  for c in comps:
      p = getattr(c, 'placement', None)
      if not p or 'logical' not in p: continue
      log = p['logical']
      items = log if isinstance(log, list) else [log]
      for item in items:
          if 'box' in item:
              max_x = max(max_x, item['box']['x_end'])
              max_y = max(max_y, item['box']['y_end'])
          else:
              max_x = max(max_x, item['x'])
              max_y = max(max_y, item['y'])

  endpoints = []
  connections = []

  # 2. Processa ogni componente per generare Endpoint e Connessioni fisiche
  for c in comps:
      if not c.interfaces or 'noc_networks' not in c.interfaces:
          continue
          
      noc_nets_raw = c.interfaces.get('noc_networks', [])
      mst_nets = noc_nets_raw.get('master', []) if isinstance(noc_nets_raw, dict) else noc_nets_raw
      slv_nets = noc_nets_raw.get('slave', []) if isinstance(noc_nets_raw, dict) else noc_nets_raw
      
      protocols_mgr = []
      protocols_sbr = []
      if c.interfaces.get('axi_master'):
          if "narrow" in mst_nets: protocols_mgr.append("narrow_in")
          if "wide" in mst_nets: protocols_mgr.append("wide_in")
          
      slaves = c.interfaces.get('axi_slave', [])
      if isinstance(slaves, dict): slaves = [slaves]
      if slaves:
          if "narrow" in slv_nets: protocols_sbr.append("narrow_out")
          if "wide" in slv_nets: protocols_sbr.append("wide_out")
          
      en_collective = c.features.get('multicast_target', False) if c.features else False
          
      # Logica di posizionamento: converte le coordinate logiche in intervalli FlooGen
      p = getattr(c, 'placement', None)
      if not p or 'logical' not in p: continue
      log = p['logical']
      items = log if isinstance(log, list) else [log]

      boxes = []
      for item in items:
          if 'box' in item:
              b = item['box']
              boxes.append((b['x_start'], b['x_end'], b['y_start'], b['y_end']))
          else:
              boxes.append((item['x'], item['x'], item['y'], item['y']))

      array_str = None
      if len(boxes) == 1:
          x_len = boxes[0][1] - boxes[0][0] + 1
          y_len = boxes[0][3] - boxes[0][2] + 1
          if x_len > 1 and y_len > 1:
              array_str = f"[{x_len}, {y_len}]"
              connections.append({
                  'src': c.name,
                  'dst': "mesh_router",
                  'src_range': [[0, x_len - 1], [0, y_len - 1]],
                  'dst_range': [[boxes[0][0], boxes[0][1]], [boxes[0][2], boxes[0][3]]],
                  'dst_dir': "Eject"
              })
          elif x_len > 1 or y_len > 1:
              count = max(x_len, y_len)
              array_str = f"[{count}]"
              connections.append({
                  'src': c.name,
                  'dst': "mesh_router",
                  'src_range': [[0, count - 1]],
                  'dst_range': [[boxes[0][0], boxes[0][1]], [boxes[0][2], boxes[0][3]]],
                  'dst_dir': "Eject"
              })
          else:
              connections.append({
                  'src': c.name,
                  'dst': "mesh_router",
                  'dst_idx': [boxes[0][0], boxes[0][2]],
                  'dst_dir': "Eject"
              })
      else:
          # Mappatura 1D complessa sparsa su diverse colonne
          total = sum((b[1]-b[0]+1)*(b[3]-b[2]+1) for b in boxes)
          array_str = f"[{total}]"
          curr_idx = 0
          for b in boxes:
              count = (b[1]-b[0]+1)*(b[3]-b[2]+1)
              connections.append({
                  'src': c.name,
                  'dst': "mesh_router",
                  'src_range': [[curr_idx, curr_idx + count - 1]],
                  'dst_range': [[b[0], b[1]], [b[2], b[3]]],
                  'dst_dir': "Eject"
              })
              curr_idx += count
              
      endpoints.append({
          'name': c.name,
          'array': array_str,
          'slaves': slaves,
          'mgr': protocols_mgr,
          'sbr': protocols_sbr,
          'en_collective': en_collective
      })
%><%namespace file="/license_header.mako" import="license"/>\
${license('#')}\
# AUTOMATICALLY GENERATED BY OLLIVANDER - DO NOT EDIT DIRECTLY
#
# FlooGen NoC Configuration for ${p_name}
# Description: ${config.project.description}

name: "${p_name}"
description: "${config.project.description}"
network_type: "narrow-wide"

routing:
  route_algo: "XY"
  use_id_table: true
  collective:
    en_narrow_multicast: true
    en_wide_multicast: true
    en_barrier: true
    en_wide_reduction:
      rd_pipeline_depth: 5
      cut_offload_intf: true
  decouple_rw: Phys
  vc_impl: naive

<%
  narrow_net = config.topology.noc_settings.networks.get('narrow') if config.topology.noc_settings and config.topology.noc_settings.networks else None
  user_id_w = getattr(narrow_net, 'id_width', None) if narrow_net else None
  if user_id_w is not None:
      g_id_w = user_id_w
  else:
      # Auto-calculate required ID width based on host internal ID width + total external AXI rules
      host_params = getattr(config.host, 'parameters', {}) or {}
      host_mst_id = int(host_params.get('AxiMstIdWidth', 3))
      tot_slvs = 0
      for c in comps:
          if c.interfaces and 'axi_slave' in c.interfaces:
              slvs = c.interfaces['axi_slave']
              tot_slvs += len(slvs) if isinstance(slvs, list) else 1
      extra_bits = math.ceil(math.log2(max(tot_slvs, 1))) if tot_slvs > 1 else 0
      g_id_w = max(host_mst_id + extra_bits + 1, 6)
%>
protocols:
  - name: "narrow_in"
    type: "narrow"
    protocol: "AXI4"
    data_width: 64
    addr_width: 48
    id_width: ${g_id_w}
    user_width:
      collective_mask: 48
      collective_op: 4
      user: 5
  - name: "narrow_out"
    type: "narrow"
    protocol: "AXI4"
    data_width: 64
    addr_width: 48
    id_width: 2
    user_width:
      collective_mask: 48
      collective_op: 4
      user: 5
  - name: "wide_in"
    type: "wide"
    protocol: "AXI4"
    data_width: 512
    addr_width: 48
    id_width: 3
    user_width:
      collective_mask: 48
      collective_op: 4
  - name: "wide_out"
    type: "wide"
    protocol: "AXI4"
    data_width: 512
    addr_width: 48
    id_width: 1
    user_width:
      collective_mask: 48
      collective_op: 4

endpoints:
% for ep in endpoints:
  - name: "${ep['name']}"
  % if ep['array']:
    array: ${ep['array']}
  % endif
  % if ep['slaves']:
    addr_range:
   % if len(ep['slaves']) == 1:
    % if ep['array']:
      base: 0x${"%08X" % (ep['slaves'][0].get('base_addr', 0))}
    % else:
      start: 0x${"%08X" % (ep['slaves'][0].get('base_addr', 0))}
    % endif
      size: 0x${"%08X" % (ep['slaves'][0].get('size', ep['slaves'][0].get('size_per_instance', 0)))}
    % if ep['slaves'][0].get('name'):
      desc: "${ep['slaves'][0].get('name')}"
    % endif
    % if ep['en_collective']:
      en_collective: true
    % endif
   % else:
    % for slv in ep['slaves']:
     % if ep['array']:
      - base: 0x${"%08X" % slv.get('base_addr', 0)}
     % else:
      - start: 0x${"%08X" % slv.get('base_addr', 0)}
     % endif
       % if slv.get('size') or slv.get('size_per_instance'):
        size:  0x${"%08X" % slv.get('size', slv.get('size_per_instance', 0))}
       % endif
        desc: "${slv.get('name', 'region')}"
      % if ep['en_collective']:
        en_collective: true
      % endif
    % endfor
   % endif
  % endif
  % if ep['mgr']:
    mgr_port_protocol:
   % for p in ep['mgr']:
      - "${p}"
   % endfor
  % endif
  % if ep['sbr']:
    sbr_port_protocol:
   % for p in ep['sbr']:
      - "${p}"
   % endfor
  % endif
% endfor

routers:
  - name: "mesh_router"
    array: [${max_x + 1}, ${max_y + 1}]
    degree: 5

connections:
% for conn in connections:
  - src: "${conn['src']}"
    dst: "${conn['dst']}"
  % if 'src_range' in conn:
    src_range:
    % for sr in conn['src_range']:
      - [${sr[0]}, ${sr[1]}]
    % endfor
  % endif
  % if 'dst_range' in conn:
    dst_range:
    % for dr in conn['dst_range']:
      - [${dr[0]}, ${dr[1]}]
    % endfor
  % endif
  % if 'dst_idx' in conn:
    dst_idx: [${conn['dst_idx'][0]}, ${conn['dst_idx'][1]}]
  % endif
    dst_dir: "${conn['dst_dir']}"
% endfor