<%
  # ============================================================================
  # MAKO TEMPLATE FOR THE APB SUBSYSTEM ISLE
  # ============================================================================
  # This template generates a complete SystemVerilog Isle containing a fully
  # featured APB Subsystem. It dynamically auto-generates the entire protocol 
  # conversion pipeline (AXI4 -> AXI4-Lite -> APB) and instantiates all the 
  # low-speed peripherals defined in the YAML configuration (Timers, Watchdogs, 
  # CAN, etc.), seamlessly bridging them to the high-performance system interconnect.
  
  # If the generator context does not provide the list of APB peripherals,
  # we use a fallback based on a default configuration.
  _apb_periphs = context.get('apb_peripherals')
  if _apb_periphs is None:
      _apb_periphs = [
          {'name': 'system_timer',   'type': 'apb_timer_unit', 'idx': 0, 'base_addr': "32'h20004000", 'size': "32'h1000"},
          {'name': 'advanced_timer', 'type': 'apb_adv_timer',  'idx': 1, 'base_addr': "32'h20005000", 'size': "32'h1000"},
          {'name': 'watchdog',       'type': 'aon_timer',      'idx': 2, 'base_addr': "32'h20007000", 'size': "32'h1000"},
          {'name': 'can_bus',        'type': 'can_top_apb',    'idx': 3, 'base_addr': "32'h20001000", 'size': "32'h1000"}
      ]
  num_apb_slaves = len(_apb_periphs)

  # Determine the synchronization domain from the component's interfaces.
  # This tells the template whether to instantiate a Clock Domain Crossing (CDC)
  # at the boundary of the Isle.
  is_sync_domain = True
  if comp.interfaces and 'axi_slave' in comp.interfaces:
      slvs = comp.interfaces['axi_slave']
      if isinstance(slvs, dict): slvs = [slvs]
      for slv in slvs:
          if not slv.get('sync_domain', True):
              is_sync_domain = False
              break
              
  comp_clk = comp.clock_domain or config.host.clock_domain or "host_clk"
  sys_clk = config.host.clock_domain or "host_clk"
  # Calculate if an internal CDC is needed when the component is marked as 
  # synchronous, but its clock domain is physically different from the host clock.
  needs_internal_cdc = is_sync_domain and (comp_clk != sys_clk)
%><%namespace file="/license_header.mako" import="license"/>\
${license()}\
//
// AUTOMATICALLY GENERATED BY OLLIVANDER - DO NOT EDIT DIRECTLY
//
// Standardized SystemVerilog shell for the APB Subsystem.
// It dynamically generates a complete and optimized protocol conversion pipeline:
// Async AXI4 (64-bit) -> Sync AXI4 -> AXI4 Atomics -> AXI4 (32-bit) ->
// AXI-Lite -> APB. This specific ordering ensures correct atomic resolution
// before data downsizing, maximizing compatibility and timing closure.
// Finally, it instantiates and memory-maps all nested peripherals.
//
// PROVENANCE
// ----------
// This subsystem is derived from the peripheral domain of the astral SoC
// (carfield.sv, "axi_cdc -> axi_amos -> axi_cut -> axi_to_axilite ->
// axilite_to_apb -> periph devices"), and supports the same four peripheral
// types: apb_timer_unit, apb_adv_timer, aon_timer and can_top_apb. Three
// classes of difference are worth knowing about.
//
// Inherited from astral, and still incomplete. These are not oversights of the
// generator: the reference ties them off in the same way, in most cases with an
// explicit TODO, because none of them is exercised by its own test suite.
//   - apb_adv_timer: the 64 external trigger inputs (ext_sig_i) are tied to '0,
//     so external event capture is unusable.
//   - aon_timer: alert_rx_i, lc_escalate_en_i and sleep_mode_i are tied to '0
//     and alert_tx_o is left open, so the OpenTitan alert and sleep interfaces
//     are inert.
//   - can_top_apb: the 64-bit timestamp input is tied to all-ones instead of a
//     running timebase, so time-triggered transmission always reads as expired
//     and every received frame carries the same stamp.
//   - The CAN and watchdog interrupts do not pass through an edge propagator,
//     unlike the two timers; astral makes the same distinction.
//
// Corrected with respect to astral:
//   - pprot and pstrb of the CAN are forwarded from the bridge instead of being
//     tied to 3'b000 and 4'b1111. axi_lite_to_apb derives pstrb from the AXI
//     W-channel strobe, so tying it off turned every sub-word write into a
//     full-word one, clobbering the neighbouring bytes of a CAN register.
//
// Added by Ollivander:
//   - The peripheral set is driven by the YAML description rather than fixed at
//     four. Index, address-map rule and Bender dependency of each peripheral are
//     generated, so a peripheral that is not declared simply does not exist. The
//     reference instead keeps all four slaves in the map and, when one is
//     disabled, answers on its behalf with a recognizable pattern to keep the
//     bus from hanging; that tie-off has no counterpart here because there is no
//     unmapped slave to answer for.
//
// RESET DOMAIN
// ------------
// The whole APB path - CDC, atomics, downsizer, AXI-Lite conversion, bridge and
// every peripheral - runs on pwr_on_rst_ni, the power-on reset of the domain,
// matching astral. It deliberately does NOT use rst_ni, which also asserts on a
// software reset: a watchdog that the system reset clears cannot protect against
// the event it exists for, and a CDC whose two sides can be reset independently
// loses FIFO pointer coherence. rst_ni is therefore left unconnected inside this
// isle; the port is kept for interface uniformity across all Ollivander isles.
//
// BENDER: name="axi"
// BENDER: name="apb"
// BENDER: name="register_interface"
// BENDER: name="common_cells"
<%
  required_benders = set()
  for p in _apb_periphs:
      if p['type'] == 'apb_timer_unit': required_benders.add("timer_unit")
      elif p['type'] == 'apb_adv_timer': required_benders.add("apb_adv_timer")
      elif p['type'] == 'aon_timer': required_benders.add("opentitan")
      elif p['type'] == 'can_top_apb': required_benders.add("can_bus")
%>\
% for b in sorted(required_benders):
${require_bender(b)}
% endfor
${require_file("olli_edge_propagator.sv")}

`include "axi/typedef.svh"
`include "axi/assign.svh"
`include "apb/typedef.svh"
`include "register_interface/typedef.svh"

module ${p_name}_${c_type}
  import ollivander_soc_pkg::*;
  import axi_pkg::*;
  import apb_pkg::*;
  import tlul_ot_pkg::*;
#(
  parameter int unsigned AxiAddrWidth    = 48,
  parameter int unsigned AxiDataWidth    = 64,
  parameter int unsigned AxiInIdWidth    = 4,
  parameter int unsigned AxiUserWidth    = 10,
  parameter int unsigned ApbAddrWidth    = 32,
  parameter int unsigned ApbDataWidth    = 32,
  parameter int unsigned AxiMaxReadTxns  = ollivander_soc_pkg::RegMaxReadTxns,
  parameter int unsigned AxiMaxWriteTxns = ollivander_soc_pkg::RegMaxWriteTxns,
  parameter int unsigned AxiUserAmoMsb   = ollivander_soc_pkg::AxiUserAmoMsb,
  parameter int unsigned AxiUserAmoLsb   = ollivander_soc_pkg::AxiUserAmoLsb,
  parameter int unsigned AxiAmoNumCuts   = ollivander_soc_pkg::RegAmoNumCuts,
  parameter bit          RegAmoPostCut   = ollivander_soc_pkg::RegAmoPostCut,
  parameter int unsigned LogDepth        = 3,
  parameter int unsigned CdcSyncStages   = 3,
  
  // AXI types
  parameter type axi_req_t      = logic,
  parameter type axi_resp_t     = logic,
  parameter type axi_aw_chan_t  = logic,
  parameter type axi_w_chan_t   = logic,
  parameter type axi_b_chan_t   = logic,
  parameter type axi_ar_chan_t  = logic,
  parameter type axi_r_chan_t   = logic
) (
  input  logic clk_i,
  // Intentionally unused: the whole APB path runs on pwr_on_rst_ni (see the
  // RESET DOMAIN note in the header). The port is kept so that every Ollivander
  // isle presents the same reset interface to the tile wrapper.
  /* verilator lint_off UNUSEDSIGNAL */
  input  logic rst_ni,
  /* verilator lint_on UNUSEDSIGNAL */
  input  logic pwr_on_rst_ni,
  input  logic sys_clk_i,
  input  logic sys_rst_ni,
  input  logic rt_clk_i,
  input  logic test_mode_i,

% if not is_sync_domain:
  // Asynchronous AXI IN (Slave)
  input  logic [(2**LogDepth)*axi_pkg::aw_width(AxiAddrWidth, AxiInIdWidth, AxiUserWidth)-1:0] async_axi_in_aw_data_i,
  input  logic [LogDepth:0] async_axi_in_aw_wptr_i,
  output logic [LogDepth:0] async_axi_in_aw_rptr_o,
  input  logic [(2**LogDepth)*axi_pkg::w_width(AxiDataWidth, AxiUserWidth)-1:0] async_axi_in_w_data_i,
  input  logic [LogDepth:0] async_axi_in_w_wptr_i,
  output logic [LogDepth:0] async_axi_in_w_rptr_o,
  output logic [(2**LogDepth)*axi_pkg::b_width(AxiInIdWidth, AxiUserWidth)-1:0] async_axi_in_b_data_o,
  output logic [LogDepth:0] async_axi_in_b_wptr_o,
  input  logic [LogDepth:0] async_axi_in_b_rptr_i,
  input  logic [(2**LogDepth)*axi_pkg::ar_width(AxiAddrWidth, AxiInIdWidth, AxiUserWidth)-1:0] async_axi_in_ar_data_i,
  input  logic [LogDepth:0] async_axi_in_ar_wptr_i,
  output logic [LogDepth:0] async_axi_in_ar_rptr_o,
  output logic [(2**LogDepth)*axi_pkg::r_width(AxiDataWidth, AxiInIdWidth, AxiUserWidth)-1:0] async_axi_in_r_data_o,
  output logic [LogDepth:0] async_axi_in_r_wptr_o,
  input  logic [LogDepth:0] async_axi_in_r_rptr_i,
% else:
  // Synchronous AXI IN (Slave)
  input  axi_req_t  axi_req_i,
  output axi_resp_t axi_resp_o,
% endif

  // External IOs (conditionally generated based on components)
% for p in _apb_periphs:
 % if p['type'] == 'can_top_apb':
  input  logic ${p['name']}_rx_i,
  output logic ${p['name']}_tx_o,
 % endif
% endfor

  // Interrupts OUT
<% 
  apb_irqs = []
  for p in _apb_periphs:
    if 'interrupts' in p:
      for irq_name, irq_cfg in p['interrupts'].items():
        apb_irqs.append((p['name'], irq_name, irq_cfg.get('width', 1)))
%>
% for i, (pname, irq_name, width) in enumerate(apb_irqs):
  output logic ${f"[{width-1}:0] " if width > 1 else ""}${pname}_${irq_name}_o${"," if i < len(apb_irqs)-1 else ""}
% endfor
);

  // =========================================================================
  // 1. BUS TYPE DEFINITIONS
  // =========================================================================
  // Generates the struct definitions for all the intermediate buses in the 
  // conversion pipeline: AXI (64-bit), AXI (32-bit), AXI-Lite, and APB.
  
  typedef logic [AxiDataWidth-1:0]   axi_data_t;
  typedef logic [AxiDataWidth/8-1:0] axi_strb_t;
  typedef logic [AxiAddrWidth-1:0]   axi_addr_t;
  typedef logic [AxiUserWidth-1:0]   axi_user_t;
  typedef logic [AxiInIdWidth-1:0]   axi_id_t;

  typedef logic [ApbDataWidth-1:0]   apb_data_t;
  typedef logic [ApbDataWidth/8-1:0] apb_strb_t;
  typedef logic [ApbAddrWidth-1:0]   apb_addr_t;

  // Downsized AXI (64-bit -> 32-bit data)
  // verilog_lint: waive-start line-length
  `AXI_TYPEDEF_ALL_CT(apb_sys_axi_dw, apb_sys_axi_dw_req_t, apb_sys_axi_dw_rsp_t, axi_addr_t, axi_id_t, apb_data_t, apb_strb_t, axi_user_t)
  // Narrow AXI (48-bit -> 32-bit addr)
  `AXI_TYPEDEF_ALL_CT(apb_sys_axi_narrow, apb_sys_axi_narrow_req_t, apb_sys_axi_narrow_rsp_t, apb_addr_t, axi_id_t, apb_data_t, apb_strb_t, axi_user_t)
  // AXI-Lite
  `AXI_LITE_TYPEDEF_ALL_CT(apb_sys_axi_lite, apb_sys_axi_lite_req_t, apb_sys_axi_lite_rsp_t, apb_addr_t, apb_data_t, apb_strb_t)
  // APB
  `APB_TYPEDEF_REQ_T(apb_sys_req_t, apb_addr_t, apb_data_t, apb_strb_t)
  `APB_TYPEDEF_RESP_T(apb_sys_rsp_t, apb_data_t)
  // verilog_lint: waive-stop line-length

  // =========================================================================
  // 2. AXI CONVERSION PIPELINE
  // =========================================================================
  // The following blocks convert the wide, asynchronous, full-featured AXI bus
  // from the central crossbar into a narrow, synchronous, simple APB bus.
  
  axi_req_t  axi_cdc_req;
  axi_resp_t axi_cdc_rsp;

% if not is_sync_domain:
  // =======================================================================
  // 2.0a ASYNCHRONOUS AXI CDC
  // =======================================================================
  // Receives split asynchronous CDC signals directly from the external 
  // Crossbar and completes the crossing into the local clock domain.
  axi_cdc_dst #(
    .LogDepth   ( LogDepth       ),
    .SyncStages ( CdcSyncStages  ),
    .aw_chan_t  ( axi_aw_chan_t  ),
    .w_chan_t   ( axi_w_chan_t   ),
    .b_chan_t   ( axi_b_chan_t   ),
    .ar_chan_t  ( axi_ar_chan_t  ),
    .r_chan_t   ( axi_r_chan_t   ),
    .axi_req_t  ( axi_req_t      ),
    .axi_resp_t ( axi_resp_t     )
  ) i_cdc_dst_peripherals (
    .async_data_slave_aw_data_i ( async_axi_in_aw_data_i ),
    .async_data_slave_aw_wptr_i ( async_axi_in_aw_wptr_i ),
    .async_data_slave_aw_rptr_o ( async_axi_in_aw_rptr_o ),
    .async_data_slave_w_data_i  ( async_axi_in_w_data_i  ),
    .async_data_slave_w_wptr_i  ( async_axi_in_w_wptr_i  ),
    .async_data_slave_w_rptr_o  ( async_axi_in_w_rptr_o  ),
    .async_data_slave_b_data_o  ( async_axi_in_b_data_o  ),
    .async_data_slave_b_wptr_o  ( async_axi_in_b_wptr_o  ),
    .async_data_slave_b_rptr_i  ( async_axi_in_b_rptr_i  ),
    .async_data_slave_ar_data_i ( async_axi_in_ar_data_i ),
    .async_data_slave_ar_wptr_i ( async_axi_in_ar_wptr_i ),
    .async_data_slave_ar_rptr_o ( async_axi_in_ar_rptr_o ),
    .async_data_slave_r_data_o  ( async_axi_in_r_data_o  ),
    .async_data_slave_r_wptr_o  ( async_axi_in_r_wptr_o  ),
    .async_data_slave_r_rptr_i  ( async_axi_in_r_rptr_i  ),
    .dst_clk_i                  ( clk_i                  ),
    .dst_rst_ni                 ( pwr_on_rst_ni          ),
    .dst_req_o                  ( axi_cdc_req            ),
    .dst_resp_i                 ( axi_cdc_rsp            )
  );
% elif needs_internal_cdc:
  // =======================================================================
  // 2.0b FULL INTERNAL AXI CDC
  // =======================================================================
  // The external interconnect provides synchronous AXI on sys_clk_i, but this 
  // Isle operates on a different local clock (clk_i). We must instantiate a 
  // full CDC here before feeding the pipeline.
  axi_cdc #(
    .AwDepth    ( 2**LogDepth    ),
    .WDepth     ( 2**LogDepth    ),
    .BDepth     ( 2**LogDepth    ),
    .ArDepth    ( 2**LogDepth    ),
    .RDepth     ( 2**LogDepth    ),
    .aw_chan_t  ( axi_aw_chan_t  ),
    .w_chan_t   ( axi_w_chan_t   ),
    .b_chan_t   ( axi_b_chan_t   ),
    .ar_chan_t  ( axi_ar_chan_t  ),
    .r_chan_t   ( axi_r_chan_t   ),
    .axi_req_t  ( axi_req_t      ),
    .axi_resp_t ( axi_resp_t     )
  ) i_cdc_full_peripherals (
    .src_clk_i  ( sys_clk_i      ),
    .src_rst_ni ( sys_rst_ni     ),
    .src_req_i  ( axi_req_i      ),
    .src_rsp_o  ( axi_resp_o     ),
    .dst_clk_i  ( clk_i          ),
    .dst_rst_ni ( pwr_on_rst_ni  ),
    .dst_req_o  ( axi_cdc_req    ),
    .dst_resp_i ( axi_cdc_rsp    )
  );
% else:
  // =======================================================================
  // 2.0c NO CDC REQUIRED
  // =======================================================================
  assign axi_cdc_req = axi_req_i;
  assign axi_resp_o  = axi_cdc_rsp;
% endif

  axi_req_t  axi_amo_req;
  axi_resp_t axi_amo_rsp;

  // =======================================================================
  // 2.1 SHIM ATOMICS (RISC-V AMOs)
  // =======================================================================
  // Handles RISC-V Atomic Memory Operations (AMOs) locally at the 64-bit level.
  // Since the downstream APB protocol does not natively support atomics, this adapter 
  // absorbs the AMO, performs the read-modify-write sequence over standard 
  // AXI/APB transactions, and returns the correct response to the Host.
  axi_riscv_atomics_structs #(
    .AxiAddrWidth     ( AxiAddrWidth    ),
    .AxiDataWidth     ( AxiDataWidth    ),
    .AxiIdWidth       ( AxiInIdWidth    ),
    .AxiUserWidth     ( AxiUserWidth    ),
    .AxiMaxReadTxns   ( AxiMaxReadTxns  ),
    .AxiMaxWriteTxns  ( AxiMaxWriteTxns ),
    .AxiUserAsId      ( 1               ),
    .AxiUserIdMsb     ( AxiUserAmoMsb   ),
    .AxiUserIdLsb     ( AxiUserAmoLsb   ),
    .RiscvWordWidth   ( 64              ),
    .NAxiCuts         ( AxiAmoNumCuts   ),
    .CutOupPopInpGnt  ( 1               ),
    .axi_req_t        ( axi_req_t       ),
    .axi_rsp_t        ( axi_resp_t      )
  ) i_atomics_peripherals (
    .clk_i         ( clk_i       ),
    .rst_ni        ( pwr_on_rst_ni ),
    .axi_slv_req_i ( axi_cdc_req ),
    .axi_slv_rsp_o ( axi_cdc_rsp ),
    .axi_mst_req_o ( axi_amo_req ),
    .axi_mst_rsp_i ( axi_amo_rsp )
  );

  axi_req_t  axi_cut_req;
  axi_resp_t axi_cut_rsp;

  // =======================================================================
  // 2.2 AXI PIPELINE CUT
  // =======================================================================
  // Inserts pipeline registers to cut long combinatorial paths and improve 
  // timing closure, especially after the complex Atomics adapter logic.
  axi_cut #(
    .Bypass     ( ~RegAmoPostCut ),
    .aw_chan_t  ( axi_aw_chan_t  ),
    .w_chan_t   ( axi_w_chan_t   ),
    .b_chan_t   ( axi_b_chan_t   ),
    .ar_chan_t  ( axi_ar_chan_t  ),
    .r_chan_t   ( axi_r_chan_t   ),
    .axi_req_t  ( axi_req_t      ),
    .axi_resp_t ( axi_resp_t     )
  ) i_atomics_cut_peripherals (
    .clk_i      ( clk_i       ),
    .rst_ni     ( pwr_on_rst_ni ),
    .slv_req_i  ( axi_amo_req ),
    .slv_resp_o ( axi_amo_rsp ),
    .mst_req_o  ( axi_cut_req ),
    .mst_resp_i ( axi_cut_rsp )
  );

  apb_sys_axi_dw_req_t axi_dw_req;
  apb_sys_axi_dw_rsp_t axi_dw_rsp;

  // =======================================================================
  // 2.3 DATA DOWNSIZE
  // =======================================================================
  // Converts the 64-bit AXI data bus from the system crossbar down to a 
  // 32-bit AXI data bus to match the APB peripheral specifications.
  axi_dw_converter #(
    .AxiSlvPortDataWidth ( AxiDataWidth ),
    .AxiMstPortDataWidth ( ApbDataWidth ),
    .AxiAddrWidth        ( AxiAddrWidth ),
    .AxiIdWidth          ( AxiInIdWidth   ),
    .aw_chan_t           ( axi_aw_chan_t             ),
    .mst_w_chan_t        ( apb_sys_axi_dw_w_chan_t   ),
    .slv_w_chan_t        ( axi_w_chan_t              ),
    .b_chan_t            ( axi_b_chan_t              ),
    .ar_chan_t           ( axi_ar_chan_t             ),
    .mst_r_chan_t        ( apb_sys_axi_dw_r_chan_t   ),
    .slv_r_chan_t        ( axi_r_chan_t              ),
    .axi_mst_req_t       ( apb_sys_axi_dw_req_t      ),
    .axi_mst_resp_t      ( apb_sys_axi_dw_rsp_t      ),
    .axi_slv_req_t       ( axi_req_t                 ),
    .axi_slv_resp_t      ( axi_resp_t                )
  ) i_axi_dw_converter_peripherals (
    .clk_i      ( clk_i       ),
    .rst_ni     ( pwr_on_rst_ni ),
    .slv_req_i  ( axi_cut_req ),
    .slv_resp_o ( axi_cut_rsp ),
    .mst_req_o  ( axi_dw_req  ),
    .mst_resp_i ( axi_dw_rsp  )
  );

  apb_sys_axi_narrow_req_t axi_narrow_req;
  apb_sys_axi_narrow_rsp_t axi_narrow_rsp;

  // =======================================================================
  // 2.4 ADDRESS DOWNSIZE
  // =======================================================================
  // Truncates the 48-bit AXI address down to a 32-bit address space, as 
  // APB peripherals do not require the full system-level addressing range.
  axi_modify_address #(
    .slv_req_t  ( apb_sys_axi_dw_req_t     ),
    .mst_addr_t ( apb_addr_t               ),
    .mst_req_t  ( apb_sys_axi_narrow_req_t ),
    .axi_resp_t ( apb_sys_axi_narrow_rsp_t )
  ) i_axi_modify_addr_peripherals (
    .slv_req_i     ( axi_dw_req                     ),
    .slv_resp_o    ( axi_dw_rsp                     ),
    .mst_req_o     ( axi_narrow_req                 ),
    .mst_resp_i    ( axi_narrow_rsp                 ),
    .mst_aw_addr_i ( axi_dw_req.aw.addr[ApbAddrWidth-1:0] ),
    .mst_ar_addr_i ( axi_dw_req.ar.addr[ApbAddrWidth-1:0] )
  );

  apb_sys_axi_lite_req_t axi_lite_req;
  apb_sys_axi_lite_rsp_t axi_lite_rsp;

  // =======================================================================
  // 2.5 AXI TO AXI-LITE CONVERTER
  // =======================================================================
  // Strips away AXI burst and ID tracking capabilities, simplifying the protocol
  // to AXI-Lite. This is a mandatory stepping stone before the final APB conversion.
  axi_to_axi_lite #(
    .AxiAddrWidth    ( ApbAddrWidth             ),
    .AxiDataWidth    ( ApbDataWidth             ),
    .AxiIdWidth      ( AxiInIdWidth             ),
    .AxiUserWidth    ( AxiUserWidth             ),
    .AxiMaxWriteTxns ( 1                        ),
    .AxiMaxReadTxns  ( 1                        ),
    .FallThrough     ( 1                        ),
    .full_req_t      ( apb_sys_axi_narrow_req_t ),
    .full_resp_t     ( apb_sys_axi_narrow_rsp_t ),
    .lite_req_t      ( apb_sys_axi_lite_req_t   ),
    .lite_resp_t     ( apb_sys_axi_lite_rsp_t   )
  ) i_axi_to_axi_lite_peripherals (
    .clk_i      ( clk_i          ),
    .rst_ni     ( pwr_on_rst_ni  ),
    .test_i     ( test_mode_i    ),
    .slv_req_i  ( axi_narrow_req ),
    .slv_resp_o ( axi_narrow_rsp ),
    .mst_req_o  ( axi_lite_req   ),
    .mst_resp_i ( axi_lite_rsp   )
  );

  // =========================================================================
  // 3. APB DEMUX & PERIPHERAL INSTANTIATIONS
  // =========================================================================
  
  // APB Address map definition dynamically built from the YAML configuration.
  typedef struct packed {
    int unsigned             idx;
    logic [ApbAddrWidth-1:0] start_addr;
    logic [ApbAddrWidth-1:0] end_addr;
  } apb_addr_map_rule_t;
  
  localparam apb_addr_map_rule_t [${num_apb_slaves}-1:0] ApbAddrMap = '{
  % for p in _apb_periphs:
    '{idx: ${p['idx']}, start_addr: ${p['base_addr']}, end_addr: ${p['base_addr']} + ${p['size']}}${"," if not loop.last else ""}
  % endfor
  };

  apb_sys_req_t [${num_apb_slaves}-1:0] apb_req;
  apb_sys_rsp_t [${num_apb_slaves}-1:0] apb_rsp;

  // =======================================================================
  // 3.1 AXI-LITE TO APB & DEMULTIPLEXER
  // =======================================================================
  // Final conversion from AXI-Lite to APB and demultiplexing of the requests 
  // to the various instantiated peripherals based on the address map.
  axi_lite_to_apb #(
    .NoApbSlaves      ( ${num_apb_slaves}        ),
    .NoRules          ( ${num_apb_slaves}        ),
    .AddrWidth        ( ApbAddrWidth             ),
    .DataWidth        ( ApbDataWidth             ),
    .PipelineRequest  ( '0                       ),
    .PipelineResponse ( '0                       ),
    .axi_lite_req_t   ( apb_sys_axi_lite_req_t   ),
    .axi_lite_resp_t  ( apb_sys_axi_lite_rsp_t   ),
    .apb_req_t        ( apb_sys_req_t            ),
    .apb_resp_t       ( apb_sys_rsp_t            ),
    .rule_t           ( apb_addr_map_rule_t      )
  ) i_axi_lite_to_apb_peripherals (
    .clk_i           ( clk_i        ),
    .rst_ni          ( pwr_on_rst_ni ),
    .axi_lite_req_i  ( axi_lite_req ),
    .axi_lite_resp_o ( axi_lite_rsp ),
    .apb_req_o       ( apb_req      ),
    .apb_resp_i      ( apb_rsp      ),
    .addr_map_i      ( ApbAddrMap   )
  );

  // =======================================================================
  // 4. GENERATED PERIPHERAL INSTANCES
  // =======================================================================
  // Instantiates the IPs defined in the YAML and maps them to the APB bus array.
% for p in _apb_periphs:
 % if p['type'] == 'apb_timer_unit':
  
  logic ${p['name']}_irq_lo_async;
  logic ${p['name']}_irq_hi_async;

  // ${p['name']}
  apb_timer_unit #(
    .APB_ADDR_WIDTH ( ApbAddrWidth )
  ) i_${p['name']} (
    .HCLK       ( clk_i                           ),
    .HRESETn    ( pwr_on_rst_ni                   ),
    .PADDR      ( apb_req[${p['idx']}].paddr      ),
    .PWDATA     ( apb_req[${p['idx']}].pwdata     ),
    .PWRITE     ( apb_req[${p['idx']}].pwrite     ),
    .PSEL       ( apb_req[${p['idx']}].psel       ),
    .PENABLE    ( apb_req[${p['idx']}].penable    ),
    .PRDATA     ( apb_rsp[${p['idx']}].prdata     ),
    .PREADY     ( apb_rsp[${p['idx']}].pready     ),
    .PSLVERR    ( apb_rsp[${p['idx']}].pslverr    ),
    .ref_clk_i  ( rt_clk_i                        ),
    .event_lo_i ( '0                              ),
    .event_hi_i ( '0                              ),
    .irq_lo_o   ( ${p['name']}_irq_lo_async       ),
    .irq_hi_o   ( ${p['name']}_irq_hi_async       ),
    .busy_o     ( /* unused */                    )
  );
  
  // Ollivander automatically generates edge-to-level propagators for IPs that
  // natively generate short pulsed/edge interrupts. This ensures compliance with 
  // the level-sensitive PLIC/CLIC interrupt controllers at the SoC level.
  olli_edge_propagator i_sync_${p['name']}_lo (
    .clk_tx_i  ( clk_i ),
    .rstn_tx_i ( pwr_on_rst_ni ),
    .edge_i    ( ${p['name']}_irq_lo_async ),
    .clk_rx_i  ( sys_clk_i ),
    .rstn_rx_i ( sys_rst_ni ),
    .edge_o    ( ${p['name']}_irq_lo_o )
  );

  olli_edge_propagator i_sync_${p['name']}_hi (
    .clk_tx_i  ( clk_i ),
    .rstn_tx_i ( pwr_on_rst_ni ),
    .edge_i    ( ${p['name']}_irq_hi_async ),
    .clk_rx_i  ( sys_clk_i ),
    .rstn_rx_i ( sys_rst_ni ),
    .edge_o    ( ${p['name']}_irq_hi_o )
  );

 % elif p['type'] == 'apb_adv_timer':
  
  logic [3:0] ${p['name']}_events_async;
  logic [3:0] ${p['name']}_channels_async;

  // ${p['name']}
  apb_adv_timer #(
    .APB_ADDR_WIDTH  ( ApbAddrWidth ),
    .EXTSIG_NUM      ( 64           )
  ) i_${p['name']} (
    .HCLK            ( clk_i                           ),
    .HRESETn         ( pwr_on_rst_ni                   ),
    .dft_cg_enable_i ( 1'b0                            ),
    .PADDR           ( apb_req[${p['idx']}].paddr      ),
    .PWDATA          ( apb_req[${p['idx']}].pwdata     ),
    .PWRITE          ( apb_req[${p['idx']}].pwrite     ),
    .PSEL            ( apb_req[${p['idx']}].psel       ),
    .PENABLE         ( apb_req[${p['idx']}].penable    ),
    .PRDATA          ( apb_rsp[${p['idx']}].prdata     ),
    .PREADY          ( apb_rsp[${p['idx']}].pready     ),
    .PSLVERR         ( apb_rsp[${p['idx']}].pslverr    ),
    .low_speed_clk_i ( rt_clk_i                        ),
    .ext_sig_i       ( '0                              ),
    .events_o        ( ${p['name']}_events_async       ),
    .ch_0_o          ( ${p['name']}_channels_async     ),
    .ch_1_o          ( /* unused */                    ),
    .ch_2_o          ( /* unused */                    ),
    .ch_3_o          ( /* unused */                    )
  );
  
  // Ollivander automatically generates edge-to-level propagators for IPs that
  // natively generate short pulsed/edge interrupts. This ensures compliance with 
  // the level-sensitive PLIC/CLIC interrupt controllers at the SoC level.
  for (genvar i = 0; i < 4; i++) begin : gen_sync_${p['name']}_events
    olli_edge_propagator i_sync_${p['name']}_events (
      .clk_tx_i  ( clk_i ),
      .rstn_tx_i ( pwr_on_rst_ni ),
      .edge_i    ( ${p['name']}_events_async[i] ),
      .clk_rx_i  ( sys_clk_i ),
      .rstn_rx_i ( sys_rst_ni ),
      .edge_o    ( ${p['name']}_events_o[i] )
    );
  end

  for (genvar i = 0; i < 4; i++) begin : gen_sync_${p['name']}_channels
    olli_edge_propagator i_sync_${p['name']}_channels (
      .clk_tx_i  ( clk_i ),
      .rstn_tx_i ( pwr_on_rst_ni ),
      .edge_i    ( ${p['name']}_channels_async[i] ),
      .clk_rx_i  ( sys_clk_i ),
      .rstn_rx_i ( sys_rst_ni ),
      .edge_o    ( ${p['name']}_channels_o[i] )
    );
  end

 % elif p['type'] == 'aon_timer':

  ${require_file("reg_to_tlul.sv")}
  // ${p['name']} 
  // This is an OpenTitan IP which natively speaks TileLink-UL (TL-UL).
  // We bridge it seamlessly into the APB subsystem using a double conversion:
  // APB -> Standard RegBus -> TL-UL.
  typedef struct packed {
    logic [ApbAddrWidth-1:0] addr;
    logic                    write;
    logic [31:0]             wdata;
    logic [3:0]              wstrb;
    logic                    valid;
  } aon_reg_req_t;

  typedef struct packed {
    logic [31:0] rdata;
    logic        error;
    logic        ready;
  } aon_reg_rsp_t;

  aon_reg_req_t reg_wdt_req;
  aon_reg_rsp_t reg_wdt_rsp;

  REG_BUS #(
    .ADDR_WIDTH ( ApbAddrWidth ),
    .DATA_WIDTH ( ApbDataWidth )
  ) reg_bus_wdt (clk_i);

  apb_to_reg i_apb_to_reg_${p['name']} (
    .clk_i     ( clk_i                        ),
    .rst_ni    ( pwr_on_rst_ni                ),
    .penable_i ( apb_req[${p['idx']}].penable ),
    .pwrite_i  ( apb_req[${p['idx']}].pwrite  ),
    .paddr_i   ( apb_req[${p['idx']}].paddr   ),
    .psel_i    ( apb_req[${p['idx']}].psel    ),
    .pwdata_i  ( apb_req[${p['idx']}].pwdata  ),
    .prdata_o  ( apb_rsp[${p['idx']}].prdata  ),
    .pready_o  ( apb_rsp[${p['idx']}].pready  ),
    .pslverr_o ( apb_rsp[${p['idx']}].pslverr ),
    .reg_o     ( reg_bus_wdt                  )
  );

  assign reg_wdt_req.addr  = reg_bus_wdt.addr;
  assign reg_wdt_req.write = reg_bus_wdt.write;
  assign reg_wdt_req.wdata = reg_bus_wdt.wdata;
  assign reg_wdt_req.wstrb = reg_bus_wdt.wstrb;
  assign reg_wdt_req.valid = reg_bus_wdt.valid;
  assign reg_bus_wdt.rdata = reg_wdt_rsp.rdata;
  assign reg_bus_wdt.error = reg_wdt_rsp.error;
  assign reg_bus_wdt.ready = reg_wdt_rsp.ready;

  tlul_ot_pkg::tl_h2d_t tl_wdt_req;
  tlul_ot_pkg::tl_d2h_t tl_wdt_rsp;

  reg_to_tlul #(
    .reg_req_t         ( aon_reg_req_t                   ),
    .reg_rsp_t         ( aon_reg_rsp_t                   ),
    .tl_h2d_t          ( tlul_ot_pkg::tl_h2d_t           ),
    .tl_d2h_t          ( tlul_ot_pkg::tl_d2h_t           )
  ) i_reg_to_tlul_${p['name']} (
    .clk_i     ( clk_i       ),
    .rst_ni    ( pwr_on_rst_ni ),
    .tl_o      ( tl_wdt_req  ),
    .tl_i      ( tl_wdt_rsp  ),
    .reg_req_i ( reg_wdt_req ),
    .reg_rsp_o ( reg_wdt_rsp )
  );

  aon_timer i_${p['name']} (
    .clk_i                     ( clk_i           ),
    .rst_ni                    ( pwr_on_rst_ni   ),
    .clk_aon_i                 ( rt_clk_i        ),
    .rst_aon_ni                ( pwr_on_rst_ni   ),
    .tl_i                      ( tl_wdt_req      ),
    .tl_o                      ( tl_wdt_rsp      ),
    .alert_rx_i                ( '0              ),
    .alert_tx_o                ( /* unused */    ),
    .lc_escalate_en_i          ( '0              ),
    .intr_wkup_timer_expired_o ( ${p['name']}_intr_wkup_timer_expired_o ),
    .intr_wdog_timer_bark_o    ( ${p['name']}_intr_wdog_timer_bark_o    ),
    .nmi_wdog_timer_bark_o     ( ${p['name']}_nmi_wdog_timer_bark_o     ),
    .wkup_req_o                ( ${p['name']}_wkup_req_o                ),
    .aon_timer_rst_req_o       ( ${p['name']}_aon_timer_rst_req_o       ),
    .sleep_mode_i              ( '0              )
  );

 % elif p['type'] == 'can_top_apb':
 
  // ${p['name']}
  can_top_apb #(
    .rx_buffer_size   ( 32 ),
    .txt_buffer_count ( 2  ),
    .target_technology( 0  ) // 0 for ASIC or 1 for FPGA
  ) i_${p['name']} (
    .aclk             ( clk_i                           ),
    .arstn            ( pwr_on_rst_ni                   ),
    .scan_enable      ( 1'b0                            ),
    .res_n_out        ( /* unused */                    ),
    .irq              ( ${p['name']}_event_o    ),
    .CAN_tx           ( ${p['name']}_tx_o               ),
    .CAN_rx           ( ${p['name']}_rx_i               ),
    .timestamp        ( 64'hFFFFFFFFFFFFFFFF            ),
    .s_apb_paddr      ( apb_req[${p['idx']}].paddr      ),
    .s_apb_penable    ( apb_req[${p['idx']}].penable    ),
    ## pprot and pstrb are forwarded from the bridge rather than tied off. axi_lite_to_apb
    ## fills pstrb from the AXI W-channel strobe, so tying it to all-ones turned every
    ## sub-word write into a full-word one, clobbering the neighbouring bytes of a CAN
    ## register. apb_strb_t is ApbDataWidth/8 bits wide, matching the peripheral port.
    .s_apb_pprot      ( apb_req[${p['idx']}].pprot      ),
    .s_apb_prdata     ( apb_rsp[${p['idx']}].prdata     ),
    .s_apb_pready     ( apb_rsp[${p['idx']}].pready     ),
    .s_apb_psel       ( apb_req[${p['idx']}].psel       ),
    .s_apb_pslverr    ( apb_rsp[${p['idx']}].pslverr    ),
    .s_apb_pstrb      ( apb_req[${p['idx']}].pstrb      ),
    .s_apb_pwdata     ( apb_req[${p['idx']}].pwdata     ),
    .s_apb_pwrite     ( apb_req[${p['idx']}].pwrite     )
  );
 % endif
% endfor

endmodule : ${p_name}_${c_type}