<%def name="license(prefix='//')">\
${prefix} Copyright 2026 Fondazione Chips-IT.
${prefix} Licensed under the Solderpad Hardware License, Version 0.51, see LICENSE for details.
${prefix} SPDX-License-Identifier: SHL-0.51
% if context.get('gen_version') and context.get('git_hash'):

${prefix} Generated by Ollivander v${context.get('gen_version')} (${context.get('git_hash')})
% endif
</%def>\