<%namespace file="/license_header.mako" import="license"/>\
${license()}\
// =========================================================================
// OLLIVANDER AUTO-GENERATED GLOBAL MEMORY MAP
// =========================================================================
// Project: ${config.project.name}
// Description: ${config.project.description}
// =========================================================================
//
// This file defines the Top-Level SystemRDL address map. 
// It aggregates the auto-generated System Controller (PCRs) and all the 
// third-party IPs that declared a `PEAKRDL` pragma in their SystemVerilog 
// wrapper. PeakRDL parses this file to generate the global C headers, 
// correctly computing the absolute memory addresses for the software stack.

// 1. Include the System Controller RDL (Auto-generated by soc_regs.rdl.mako)
`include "${top_level_module_name}_regs.rdl"

// 2. Include External Components RDLs
<%
    # Flatten the hierarchy recursively to include all nested components
    all_comps = []
    def flatten_comps(comp_list):
        for c in comp_list:
            all_comps.append(c)
            if getattr(c, 'components', None):
                flatten_comps(c.components)
    
    flatten_comps([config.host] + (config.components or []))
%>
// Discovered dynamically from all top-level and nested components.
% for c in all_comps:
    <% c_info = comp_info.get(c.name, {}) %>
    % if c_info.get('rdl_file'):
`include "${c_info['rdl_file']}"
    % endif
% endfor

// 3. Global Address Map Definition
// Instantiates the individual register maps at their physical base addresses 
// defined in the YAML configuration.
addrmap ${top_level_module_name}_soc_map {
    name = "${config.project.name} Global Address Map";

    // System Controller (Power, Clock, and Reset Registers)
    ${top_level_module_name}_sys_regs sys_ctrl @ ${hex(config.system_controller.base_addr) if isinstance(config.system_controller.base_addr, int) else config.system_controller.base_addr};

% if config.system_controller and config.system_controller.external_registers:
    // External Registers (Exported to Top-Level via RegBus)
 % for ext_reg in config.system_controller.external_registers:
    <% 
        s_size = getattr(ext_reg, 'size', None) or 0x1000
        s_size_val = int(s_size, 16) if isinstance(s_size, str) else s_size
        mem_entries = max(1, s_size_val // 4)
    %>
    external mem { name = "${ext_reg.name} Opaque Region"; mementries = ${mem_entries}; memwidth = 32; } ${ext_reg.name} @ ${hex(ext_reg.base_addr) if isinstance(ext_reg.base_addr, int) else ext_reg.base_addr};
 % endfor
% endif

    // Hardware IPs Memory Maps
<%def name="generate_map(comps, parent_base=0)">
% for c in comps:
    <% 
        c_info = comp_info.get(c.name, {}) 
        has_rdl = bool(c_info.get('rdl_map'))
        
        # Hardware instance count, from the component's NoC placement. Shared with the SoC
        # package, the address map and FlooGen through core.utils, so that a component cannot
        # be an array of four here and of eight there.
        from core.utils import resolve_instance_windows, instance_count
        num_inst = instance_count(c)
        
        slaves = []
        if c.interfaces:
            for if_type in ['regbus_slave', 'axi_slave', 'apb_slave', 'llc_port']:
                if if_type in c.interfaces and isinstance(c.interfaces[if_type], list):
                    for item in c.interfaces[if_type]:
                        s_size = item.get('size') or item.get('size_per_instance') or 4
                        s_stride = item.get('size_per_instance') or s_size
                        slaves.append((if_type, item.get('base_addr'), s_size, s_stride, item.get('name', if_type.split('_')[0]), item))
        elif getattr(c, 'base_addr', None) is not None:
            # Nested components often define base_addr directly without an interfaces block
            slaves.append(('apb_slave', c.base_addr, getattr(c, 'size', 4), getattr(c, 'size', 4), 'regs', None))
            
        rdl_mapped = False
        has_children = bool(getattr(c, 'components', None))
    %>
    % for i, (if_type, b_addr, s_size, s_stride, slv_name, raw_item) in enumerate(slaves):
        <%
            if b_addr is None: continue
            inst_name = c.name if len(slaves) == 1 else f"{c.name}_{slv_name}"

            b_addr_val = int(b_addr, 16) if isinstance(b_addr, str) else b_addr
            offset = b_addr_val - parent_base

            # Calculate memory entries for opaque blocks (assuming 32-bit/4-byte words)
            s_size_val = int(s_size, 16) if isinstance(s_size, str) else s_size
            s_stride_val = int(s_stride, 16) if isinstance(s_stride, str) else s_stride
            mem_entries = max(1, s_size_val // 4)

            array_str = f"[{num_inst}]" if num_inst > 1 else ""
            stride_str = f" += {hex(s_stride_val)}" if num_inst > 1 else ""

            # RDL EXPRESSES AN ARRAY AS A SINGLE STRIDE - 'name[N] @ offset += stride' - so it
            # can describe instances of equal depth at a constant pitch and nothing else. That
            # is the same limitation FlooGen's 'array:' has, and it takes the same remedy: when
            # a list on 'base_addr' or 'size_per_instance' breaks uniformity, the array is
            # UNROLLED into one declaration per instance, each carrying its own offset and its
            # own depth. 'emissions' is what the branches below emit; a single entry reproduces
            # today's array form byte for byte, which is what every uniform project generates.
            emissions = [(inst_name, array_str, stride_str, offset, mem_entries)]
            if num_inst > 1 and raw_item is not None:
                windows = resolve_instance_windows(raw_item, num_inst)
                sizes = {size for _, size in windows}
                strides = {windows[k + 1][0] - windows[k][0] for k in range(num_inst - 1)}
                if len(sizes) > 1 or strides != {s_stride_val}:
                    emissions = [(f"{inst_name}_{k}", "", "", base - parent_base,
                                  max(1, size // 4))
                                 for k, (base, size) in enumerate(windows)]

            use_rdl = False
            if has_rdl and not rdl_mapped:
                if if_type in ['regbus_slave', 'apb_slave'] or not any(t in ['regbus_slave', 'apb_slave'] for t, *_ in slaves):
                    use_rdl = True
                    rdl_mapped = True
        %>
      % for e_name, e_array, e_stride, e_offset, e_entries in emissions:
        % if use_rdl:
    ${c_info['rdl_map']} ${e_name}${e_array} @ ${hex(e_offset)}${e_stride};
        % elif has_children:
    addrmap {
        name = "${c.name} Subsystem";
        ${generate_map(c.components, b_addr_val)}
    } ${e_name}${e_array} @ ${hex(e_offset)}${e_stride};
        % else:
    external mem { name = "Opaque Memory Region"; mementries = ${e_entries}; memwidth = 32; } ${e_name}${e_array} @ ${hex(e_offset)}${e_stride};
        % endif
      % endfor
    % endfor
% endfor
</%def>

${generate_map([config.host] + (config.components or []))}
};
