<%namespace file="/license_header.mako" import="license"/>\
${license()}\
// =========================================================================
// OLLIVANDER AUTO-GENERATED GLOBAL MEMORY MAP
// =========================================================================
// Project: ${config.project.name}
// Description: ${config.project.description}
// =========================================================================
//
// This file defines the Top-Level SystemRDL address map. 
// It aggregates the auto-generated System Controller (PCRs) and all the 
// third-party IPs that declared a `PEAKRDL` pragma in their SystemVerilog 
// wrapper. PeakRDL parses this file to generate the global C headers, 
// correctly computing the absolute memory addresses for the software stack.

// 1. Include the System Controller RDL (Auto-generated by soc_regs.rdl.mako)
`include "${config.project.name}_regs.rdl"

// 2. Include External Components RDLs
// Discovered dynamically during the SystemVerilog parsing phase.
% for c in [config.host] + (config.components or []):
    <% c_info = comp_info.get(c.name, {}) %>
    % if c_info.get('rdl_file'):
`include "${c_info['rdl_file']}"
    % endif
% endfor

// 3. Global Address Map Definition
// Instantiates the individual register maps at their physical base addresses 
// defined in the YAML configuration.
addrmap ${config.project.name}_soc_map {
    name = "${config.project.name} Global Address Map";

    // System Controller (Power, Clock, and Reset Registers)
    ${config.project.name}_sys_regs sys_ctrl @ ${hex(config.system_controller.base_addr) if isinstance(config.system_controller.base_addr, int) else config.system_controller.base_addr};

    // Hardware IPs Memory Maps
% for c in [config.host] + (config.components or []):
    <% 
        c_info = comp_info.get(c.name, {}) 
        base_addr = 0
        if c.interfaces:
            for if_type in ['regbus_slave', 'axi_slave', 'apb_slave', 'llc_port']:
                if if_type in c.interfaces and isinstance(c.interfaces[if_type], list):
                    base_addr = c.interfaces[if_type][0].get('base_addr', 0)
                    break
    %>
    % if c_info.get('rdl_map'):
    ${c_info['rdl_map']} ${c.name} @ ${hex(base_addr) if isinstance(base_addr, int) else base_addr};
    % endif
% endfor
};