<%
  # ============================================================================
  # MAKO TEMPLATE FOR THE SYSTEM CONTROLLER REGISTERS (HJSON)
  # ============================================================================
  # This template generates the specification for the central control registers (PCRs).
  
  # Helper functions to safely format strings for HJSON and SystemVerilog
  def fmt_dom(name):
      return name.replace('_clk', '').upper()
  
  def fmt_comp(name):
      return name.upper()
      
  def fmt_hex(val):
      if isinstance(val, int): return f"0x{val:X}"
      if isinstance(val, str) and val.isdigit(): return f"0x{int(val):X}"
      return val

  # --- Component Grouping ---
  # Ollivander extracts subsets of components that require specific system-level 
  # control registers based on their `system_config` flags in the YAML.
  
  isolate_comps = [c for c in components if c.get('system_config', {}).get('isolate', False)]
  fetch_comps = [c for c in components if c.get('system_config', {}).get('fetch_enable', False)]
  # Add host explicitly for fetch (the host always needs a fetch_enable register to boot)
  fetch_comps.insert(0, {'name': 'host', 'system_config': {'boot_addr': '0x1000'}}) 
  
  boot_comps = [c for c in components if 'boot_addr' in c.get('system_config', {})]
  boot_comps.insert(0, {'name': 'host', 'system_config': {'boot_addr': '0x1000'}})

  dedicated_clk_comps = [c for c in components if 'dedicated_clock_div' in c]
%><%namespace file="/license_header.mako" import="license"/>\
${license()}\
//
// AUTOMATICALLY GENERATED BY OLLIVANDER - DO NOT EDIT DIRECTLY
//
// System Controller Register File Specification.
// This HJSON file is intended to be processed by an external tool (like OpenTitan's 
// regtool or PeakRDL) to generate the physical SystemVerilog register block 
// and the corresponding C headers for software drivers.
{
  name: "${project_name}",
  clocking: [
    { clock: "clk_i", reset: "rst_ni", primary: true }
  ],
  bus_interfaces: [
    { protocol: "tlul", direction: "device" }
  ],
  regwidth: "32",
  registers: [

    // =========================================================================
    // 1. STATIC SYSTEM CONTROLLER REGISTERS
    // =========================================================================
    // Read-only identification registers and read-write scratchpads for generic 
    // software use (e.g., inter-processor communication flags before mailboxes are up).
% for i in range(sys_ctrl.get('version_registers', 0)):
    { name: "VERSION${i}",
      desc: "Version / Commit hash register ${i}",
      swaccess: "ro",
      hwaccess: "none",
      resval: "0",
      hwqe: "0",
      fields: [ { bits: "31:0" } ],
    }
% endfor

    { name: "JEDEC_IDCODE",
      desc: "JEDEC ID CODE",
      swaccess: "rw",
      hwaccess: "none",
      resval: "${fmt_hex(sys_ctrl.get('jedec_id', 0))}",
      hwqe: "0",
      fields: [ { bits: "31:0" } ],
    }

% for i in range(sys_ctrl.get('scratch_registers', 0)):
    { name: "GENERIC_SCRATCH${i}",
      desc: "Generic Scratch register ${i}",
      swaccess: "rw",
      hwaccess: "hrw",
      resval: "0",
      hwqe: "0",
      fields: [ { bits: "31:0" } ],
    }
% endfor

    // =========================================================================
    // 2. DOMAIN RESETS
    // =========================================================================
    // Software-triggered resets for individual clock domains. 
    // These are logically OR-ed with the global Power-On Reset (POR) in the hardware.
% for domain in domains:
    { name: "${fmt_dom(domain['name'])}_RST",
      desc: "${fmt_dom(domain['name'])} Domain reset - active high, inverted in HW",
      swaccess: "${'ro' if domain['name'] == 'host_clk' else 'rw'}",
      hwaccess: "hro",
      resval: "0",
      hwqe: "0",
      fields: [ { bits: "0:0" } ],
    }
% endfor

    // =========================================================================
    // 3. AXI ISOLATION CONTROL
    // =========================================================================
    // Isolation signals are critical for heterogeneous SoCs. They safely "fence" 
    // an IP's AXI transactions before the IP is put into sleep mode or reset,
    // preventing deadlocks on the central interconnect.
% for c in isolate_comps:
    { name: "${fmt_comp(c['name'])}_ISOLATE",
      desc: "${c['name']} AXI isolate request",
      swaccess: "rw",
      hwaccess: "hro",
      resval: "${'1' if c.get('system_config', {}).get('isolate', False) else '0'}",
      hwqe: "0",
      fields: [ { bits: "0:0" } ],
    }
% endfor

% for c in isolate_comps:
    { name: "${fmt_comp(c['name'])}_ISOLATE_STATUS",
      desc: "${c['name']} AXI isolate status acknowledgment",
      swaccess: "rw",
      hwaccess: "hwo",
      resval: "0",
      hwqe: "0",
      fields: [ { bits: "0:0" } ],
    }
% endfor

    // =========================================================================
    // 4. CLOCK GATING AND MULTIPLEXING
    // =========================================================================
    // Software control for the dynamic clock generation tree. 
    // Registers drive the Glitch-Free Muxes and Integer Dividers in the top-level.
% for domain in domains:
 % if domain['name'] != 'rt_clk' and domain['name'] != 'host_clk':
    { name: "${fmt_dom(domain['name'])}_CLK_EN",
      desc: "${fmt_dom(domain['name'])} Domain clock gate enable",
      swaccess: "rw",
      hwaccess: "hro",
      resval: "${'0' if domain.get('has_mux', False) else '1'}",
      hwqe: "0",
      fields: [ { bits: "0:0" } ],
    }
 % endif
% endfor

% for domain in domains:
 % if domain.get('has_mux', False):
    { name: "${fmt_dom(domain['name'])}_CLK_SEL",
      desc: "${fmt_dom(domain['name'])} Domain FLL select multiplexer",
      swaccess: "rw",
      hwaccess: "hro",
      resval: "1",
      hwqe: "0",
      fields: [ { bits: "1:0" } ],
    }
 % endif
% endfor

% for domain in domains:
 % if domain.get('has_divider', False):
    { name: "${fmt_dom(domain['name'])}_CLK_DIV_VALUE",
      desc: "${fmt_dom(domain['name'])} Domain clock divider value",
      swaccess: "rw",
      hwaccess: "hro",
      resval: "${domain.get('default_div', 1)}",
      hwqe: "1",
      fields: [ { bits: "23:0" } ],
    }
 % endif
% endfor

    // =========================================================================
    // 5. FETCH ENABLE AND BOOT ADDRESSES
    // =========================================================================
    // Registers that control the boot sequence of programmable cores in the system.
    // The Host configures the boot address, loads the firmware into memory, 
    // and then asserts fetch_enable to wake the core up.
% for c in fetch_comps:
    { name: "${fmt_comp(c['name'])}_FETCH_ENABLE",
      desc: "${c['name']} fetch enable",
      swaccess: "${'ro' if c['name'] == 'host' else 'rw'}",
      hwaccess: "hro",
      resval: "0",
      hwqe: "0",
      fields: [ { bits: "0:0" } ],
    }
% endfor

% for c in components:
 % if c.get('system_config', {}).get('debug_req', False):
    { name: "${fmt_comp(c['name'])}_DEBUG_REQ",
      desc: "${c['name']} debug request",
      swaccess: "rw",
      hwaccess: "hro",
      resval: "0",
      hwqe: "0",
      fields: [ { bits: "1:0" } ],
    }
 % endif
% endfor

% for c in boot_comps:
    { name: "${fmt_comp(c['name'])}_BOOT_ADDR",
      desc: "${c['name']} boot address",
      swaccess: "rw",
      hwaccess: "hro",
      resval: "${fmt_hex(c['system_config']['boot_addr'])}",
      hwqe: "0",
      fields: [ { bits: "31:0" } ],
    }
% endfor

% for c in components:
 % if 'boot_enable' in c.get('system_config', {}):
    { name: "${fmt_comp(c['name'])}_BOOT_ENABLE",
      desc: "${c['name']} boot enable",
      swaccess: "rw",
      hwaccess: "hro",
      resval: "0",
      hwqe: "0",
      fields: [ { bits: "0:0" } ],
    }
 % endif
% endfor

    // =========================================================================
    // 6. COMPONENT STATUS (BUSY / EOC)
    // =========================================================================
    // Read-only status flags exported directly from the hardware IPs to monitor 
    // their execution state (e.g., End Of Computation for accelerators).
% for c in components:
 % if c.get('system_config', {}).get('has_busy_status', False):
    { name: "${fmt_comp(c['name'])}_BUSY",
      desc: "${c['name']} busy status flag",
      swaccess: "ro",
      hwaccess: "hrw",
      resval: "0",
      hwqe: "0",
      fields: [ { bits: "0:0" } ],
    }
 % endif
 % if c.get('system_config', {}).get('has_eoc_status', False):
    { name: "${fmt_comp(c['name'])}_EOC",
      desc: "${c['name']} end of computation flag",
      swaccess: "ro",
      hwaccess: "hrw",
      resval: "0",
      hwqe: "0",
      fields: [ { bits: "0:0" } ],
    }
 % endif
% endfor

    // =========================================================================
    // 7. DEDICATED CLOCK DIVIDERS
    // =========================================================================
    // Independent clock dividers dedicated to specific interfaces that require 
    // highly constrained frequencies (like RGMII for Ethernet or HyperBus PHYs).
% for c in dedicated_clk_comps:
    { name: "${fmt_dom(c['dedicated_clock_div']['name'])}_CLK_EN",
      desc: "${c['name']} dedicated clock divider enable bit",
      swaccess: "rw",
      hwaccess: "hro",
      resval: "1",
      hwqe: "0",
      fields: [ { bits: "0:0" } ],
    }

    { name: "${fmt_dom(c['dedicated_clock_div']['name'])}_CLK_DIV_VALUE",
      desc: "${c['name']} dedicated clock divider value",
      swaccess: "rw",
      hwaccess: "hro",
      resval: "${c['dedicated_clock_div'].get('default_div', 1)}",
      hwqe: "1",
      fields: [ { bits: "23:0" } ],
    }
% endfor

    // =========================================================================
    // 8. FLL AND DEBUG CLOCKS
    // =========================================================================
    // Status of the analog PLLs/FLLs and control for the parallel debug clock
    // network used by JTAG and DMI (Debug Module Interface).
% if sys_ctrl.get('fll_status_regs', False):
    { name: "FLL_LOCK",
      desc: "FLL global lock status",
      swaccess: "ro",
      hwaccess: "hrw",
      resval: "0",
      hwqe: "0",
      fields: [ { bits: "${max(0, config.clock_tree.flls - 1)}:0" } ],
    }
% endif

% for domain in domains:
 % if domain.get('has_debug_divider', False):
    { name: "${fmt_dom(domain['name'])}_DEBUG_CLK_EN",
      desc: "${fmt_dom(domain['name'])} Domain debug clock divider enable",
      swaccess: "rw",
      hwaccess: "hro",
      resval: "1",
      hwqe: "0",
      fields: [ { bits: "0:0" } ],
    }
 % endif
% endfor

% for domain in domains:
 % if domain.get('has_debug_divider', False):
    { name: "${fmt_dom(domain['name'])}_DEBUG_CLK_DIV_VALUE",
      desc: "${fmt_dom(domain['name'])} Domain debug clock divider value",
      swaccess: "rw",
      hwaccess: "hro",
      resval: "10",
      hwqe: "1",
      fields: [ { bits: "23:0" } ],
    }
 % endif
% endfor

    // =========================================================================
    // 9. AUTO CONTROL GROUPS (NoC / Array based controls)
    // =========================================================================
% if 'auto_control_groups' in sys_ctrl:
 % for group in sys_ctrl['auto_control_groups']:
  <%
    target_type = group.get('target_component_type')
    target_tile_type = target_type.replace('_subtile', '_tile').replace('_isle', '_tile') if target_type else None
    count = 0
    for c in components:
        orig_type = original_isle_types.get(c.get('name'), c.get('type'))
        if c.get('type') == target_type or c.get('type') == target_tile_type or orig_type == target_type:
            p = c.get('placement')
            if not p or 'logical' not in p:
                count += 1
            else:
                items = p['logical'] if isinstance(p['logical'], list) else [p['logical']]
                for item in items:
                    if 'box' in item:
                        count += (item['box']['x_end'] - item['box']['x_start'] + 1) * (item['box']['y_end'] - item['box']['y_start'] + 1)
                    else:
                        count += 1
  %>
  % if count > 0 and group.get('type') == 'clk_rst_control':
    { name: "${group['name'].upper()}_RST",
      desc: "Reset array for ${group['name']} (1 bit per tile)",
      swaccess: "rw",
      hwaccess: "hro",
      resval: "0",
      hwqe: "0",
      fields: [ { bits: "${count-1}:0" } ],
    }

    { name: "${group['name'].upper()}_CLK_EN",
      desc: "Clock gate array for ${group['name']} (1 bit per tile)",
      swaccess: "rw",
      hwaccess: "hro",
      resval: "0x${'%X' % ((1 << count) - 1)}",
      hwqe: "0",
      fields: [ { bits: "${count-1}:0" } ],
    }
  % endif
 % endfor
% endif
  ],
}