# Copyright Fondazione Chips-IT
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0
#

OLLIVANDER_ROOT := ../..
SOC_YAML        := $(OLLIVANDER_ROOT)/soc_cfg_examples/crossbar_mini/crux_mini.yml
ENV_YAML        := $(OLLIVANDER_ROOT)/soc_cfg_examples/crossbar_mini/crux_mini_env.yml
OUT_DIR         := generated

include $(OLLIVANDER_ROOT)/ollivander.mk
