<%
  # ============================================================================
  # MAKO TEMPLATE FOR THE SOC GLOBAL RESET TREE
  # ============================================================================
  # This template generates a project-specific wrapper that aggregates multiple 
  # reset generators. It takes a global asynchronous Power-On Reset (POR) and an 
  # array of software-controlled resets, and synchronizes them into the respective 
  # clock domains to ensure safe, glitch-free de-assertions.
  p_name = config.project.name
%><%namespace file="/license_header.mako" import="license"/>\
${license()}\
//
// AUTOMATICALLY GENERATED BY OLLIVANDER - DO NOT EDIT DIRECTLY
//
// SoC Global Reset Tree Wrapper for ${p_name.upper()}
//
// BENDER: name="common_cells"

module ${p_name}_rstgen #(
  parameter int unsigned NumRstDomains = 1
) (
  input  logic [NumRstDomains-1:0] clks_i,
  input  logic                     pwr_on_rst_ni,
  input  logic [NumRstDomains-1:0] sw_rsts_ni,
  input  logic                     test_mode_i,
  output logic [NumRstDomains-1:0] rsts_no,
  output logic [NumRstDomains-1:0] pwr_on_rsts_no,
  output logic [NumRstDomains-1:0] inits_no
);

  for (genvar i = 0; i < NumRstDomains; i++) begin : gen_rst_domains
    logic pwr_on_rst_n;

    ${require_file("olli_rstgen.sv")}
    // =======================================================================
    // 1. HARDWARE POWER-ON RESET (POR) SYNCHRONIZATION
    // =======================================================================
    // Synchronize the global asynchronous power-on reset into the local domain clock.
    // This reset bypasses the software-controlled CSRs and cannot be gated.
    olli_rstgen i_pwr_on_rstgen (
      .clk_i       ( clks_i[i] ),
      .rst_ni      ( pwr_on_rst_ni ),
      .test_mode_i ( test_mode_i ),
      .rst_no      ( pwr_on_rst_n ),
      .init_no     ( inits_no[i] )
    );

    assign pwr_on_rsts_no[i] = pwr_on_rst_n;

    // =======================================================================
    // 2. SOFTWARE-CONTROLLED RESET
    // =======================================================================
    // The software reset is the register bit ALONE - no second synchronizer, and no AND with
    // the power-on reset either. One step beyond the Carfield reference, which keeps the AND
    // and declares that path false; and the same shape gwaihir gives its tiles, where the
    // payload reset is a single flop output.
    //
    // Why no AND: the power-on reset already reaches this domain through the reset VALUE of
    // the register that drives 'sw_rsts_ni', which soc_regs.rdl.mako pins to 'held in reset'
    // under both power-on policies. Combining the two here would put combinational logic on a
    // reset net DOWNSTREAM of the synchronizer above, undoing the synchronous release it just
    // produced and able to carry a glitch to part of the domain.
    //
    // Why no second synchronizer: it would restore the synchronous release, at the price of a
    // single-cycle recovery constraint from the synchronizer to every flop of the domain, at
    // full runtime speed - the burden the reference explicitly declines. The path is a FALSE
    // PATH by design, safe because software only toggles this bit while the domain's clock is
    // gated (offload.h.mako honours that order). Flops that need a CONSTRAINED release stay on
    // 'pwr_on_rsts_no', which every isle declares as 'pwr_on_rst_ni' for exactly that purpose.
    //
    // Note: the software reset is active low, so sw_rsts_ni[i] == 0 holds the domain in reset.
    assign rsts_no[i] = sw_rsts_ni[i];
  end

endmodule : ${p_name}_rstgen
