<%
  # ============================================================================
  # MAKO TEMPLATE FOR THE SOC GLOBAL RESET TREE
  # ============================================================================
  p_name = config.project.name
%><%namespace file="/license_header.mako" import="license"/>\
${license()}\
//
// AUTOMATICALLY GENERATED BY OLLIVANDER - DO NOT EDIT DIRECTLY
//
// SoC Global Reset Tree Wrapper for ${p_name.upper()}
//
// BENDER: name="common_cells"

module ${p_name}_rstgen #(
  parameter int unsigned NumRstDomains = 1
) (
  input  logic [NumRstDomains-1:0] clks_i,
  input  logic                     pwr_on_rst_ni,
  input  logic [NumRstDomains-1:0] sw_rsts_ni,
  input  logic                     test_mode_i,
  output logic [NumRstDomains-1:0] rsts_no,
  output logic [NumRstDomains-1:0] pwr_on_rsts_no,
  output logic [NumRstDomains-1:0] inits_no
);

  for (genvar i = 0; i < NumRstDomains; i++) begin : gen_rst_domains
    logic pwr_on_rst_n;

    // 1. Synchronize the global asynchronous power-on reset to the domain clock
    rstgen i_pwr_on_rstgen (
      .clk_i       ( clks_i[i] ),
      .rst_ni      ( pwr_on_rst_ni ),
      .test_mode_i ( test_mode_i ),
      .rst_no      ( pwr_on_rst_n ),
      .init_no     ( inits_no[i] )
    );

    assign pwr_on_rsts_no[i] = pwr_on_rst_n;

    // 2. Combine the synchronized POR with the software reset and synchronize again.
    // Software reset is active low, meaning sw_rsts_ni = 0 triggers a reset.
    rstgen i_sw_rstgen (
      .clk_i       ( clks_i[i] ),
      .rst_ni      ( pwr_on_rst_n & sw_rsts_ni[i] ),
      .test_mode_i ( test_mode_i ),
      .rst_no      ( rsts_no[i] ),
      .init_no     ( /* unused */ )
    );
  end

endmodule : ${p_name}_rstgen
