<%
  # ============================================================================
  # MAKO TEMPLATE FOR THE DUMMY TILE (ROUTER ONLY)
  # ============================================================================
  # A "Dummy Tile" is instantiated in the Network-on-Chip (NoC) grid at coordinates 
  # where no functional IP (Component) is placed. It serves purely as a routing 
  # node to maintain the integrity and connectivity of the 2D mesh, allowing packets 
  # to pass through to their actual destinations.
  # Prefix of every generated module, see Project.module_prefix.
  p_name = config.project.module_prefix
  # FlooNoC package name, see Project.noc_pkg_name.
  noc_pkg = config.project.noc_pkg_name
  # Global SoC package name. Derived from the project so that a "macro" build gets
  # the same suffix as its top-level module and never collides with a "standalone"
  # build of the same project.
  soc_pkg = config.project.soc_pkg_name
%><%namespace file="/license_header.mako" import="license"/>\
${license()}\
//
// AUTOMATICALLY GENERATED BY OLLIVANDER - DO NOT EDIT DIRECTLY
//
// Dummy Tile (Router Only)
//
// BENDER: name="axi"
// BENDER: name="floo_noc"

`include "floo_noc/typedef.svh"

module ${p_name}_dummy_tile
  import floo_pkg::*;
  import ${noc_pkg}::*; // Autogenerated NoC package
  import ${soc_pkg}::*;      // Global SoC parameters and routes
(
  input  logic clk_i,
  input  logic rst_ni,
  input  logic test_mode_i,
  input wire id_t  id_i,
  output floo_req_t  [West:North] floo_req_o,
  input wire floo_rsp_t  [West:North] floo_rsp_i,
  output floo_wide_t [West:North] floo_wide_o,
  input wire floo_req_t  [West:North] floo_req_i,
  output floo_rsp_t  [West:North] floo_rsp_o,
  input wire floo_wide_t [West:North] floo_wide_i
);

  floo_req_t  [Eject:North] router_floo_req_out, router_floo_req_in;
  floo_rsp_t  [Eject:North] router_floo_rsp_out, router_floo_rsp_in;
  floo_wide_t [Eject:North] router_floo_wide_in, router_floo_wide_out;

  // =======================================================================
  // 1. FLOONOC ROUTER INSTANTIATION
  // =======================================================================
  // Instantiates a standard 5-port router (4 Cardinal directions + 1 Eject).
  // A dummy tile hosts no endpoint, so it never injects or receives a
  // collective - but it may have to CARRY one. Transit is a property of the
  // router, not of the endpoint: with the collective config left at its
  // all-zero default, floo_route_select ties the multicast route selection to
  // zero ("No MCast supported") and a replicated flit crossing an empty
  // coordinate is dropped in silence. Today's geometries route around the
  // dummies, so nothing observes it; the configuration is passed anyway,
  // because the day a placement puts one on a collective path the failure
  // would be a lost flit with no diagnostic.
  // Transit-only collective set. Multicast and the LsbAnd barrier are PARALLEL
  // operations: the router merges or replicates flits itself, with no compute.
  // Every arithmetic reduction is masked off instead, because it COMPUTES at
  // each merging router through an offload interface, and a dummy tile has no
  // unit behind it - enabling one here makes the router demand reduction types
  // this tile cannot provide, and elaboration fails on the offload port
  // (vsim-3701, measured 2026-09-01). A reduction tree must therefore never be
  // shaped so that it merges on an empty coordinate; replication across one is
  // now carried correctly.
  localparam floo_pkg::collective_cfg_t DummyCollectiveCfg = '{
      OpCfg: '{
          EnNarrowMulticast: RouteCfg.CollectiveCfg.OpCfg.EnNarrowMulticast,
          EnWideMulticast:   RouteCfg.CollectiveCfg.OpCfg.EnWideMulticast,
          EnLsbAnd:          RouteCfg.CollectiveCfg.OpCfg.EnLsbAnd,
          EnFpAdd:  1'b0, EnFpMul:  1'b0, EnFpMin:  1'b0, EnFpMax:  1'b0,
          EnIntAdd: 1'b0, EnIntMul: 1'b0, EnIntMinS: 1'b0,
          EnIntMinU: 1'b0, EnIntMaxS: 1'b0, EnIntMaxU: 1'b0
      },
      NarrRedCfg: RouteCfg.CollectiveCfg.NarrRedCfg,
      WideRedCfg: RouteCfg.CollectiveCfg.WideRedCfg
  };

  floo_nw_router #(
    .AxiCfgN       (AxiCfgN),
    .AxiCfgW       (AxiCfgW),
    .RouteAlgo     (RouteCfgNoMcast.RouteAlgo),
    .NumRoutes     (5),
    .InFifoDepth   (2),
    .OutFifoDepth  (2),
    .id_t          (id_t),
    .hdr_t         (hdr_t),
    .floo_req_t    (floo_req_t),
    .floo_rsp_t    (floo_rsp_t),
    .floo_wide_t   (floo_wide_t),
    .WideRwDecouple(WideRwDecouple),
    .VcImpl        (VcImpl),
    .CollectiveCfg (DummyCollectiveCfg),
    .NoLoopback    (!floo_pkg::en_collective(DummyCollectiveCfg.OpCfg))
  ) i_router (
    .clk_i               (clk_i),
    .rst_ni              (rst_ni),
    .id_i                (id_i),
    .test_enable_i       (test_mode_i),
    .id_route_map_i      ('0),
    .floo_req_i          (router_floo_req_in),
    .floo_rsp_o          (router_floo_rsp_out),
    .floo_req_o          (router_floo_req_out),
    .floo_rsp_i          (router_floo_rsp_in),
    .floo_wide_i         (router_floo_wide_in),
    .floo_wide_o         (router_floo_wide_out),
    .offload_wide_req_o  (),
    .offload_wide_rsp_i  ('0),
    .offload_narrow_req_o(),
    .offload_narrow_rsp_i('0)
  );

  // =======================================================================
  // 2. MESH WIRING
  // =======================================================================
  // Map the 4 cardinal directions to the external module ports.
  assign floo_req_o                      = router_floo_req_out[West:North];
  assign router_floo_req_in[West:North]  = floo_req_i;
  assign floo_rsp_o                      = router_floo_rsp_out[West:North];
  assign router_floo_rsp_in[West:North]  = floo_rsp_i;
  assign router_floo_wide_in[West:North] = floo_wide_i;
  assign floo_wide_o[West:North]         = router_floo_wide_out[West:North];

  // =======================================================================
  // 3. EJECT PORT TIE-OFF
  // =======================================================================
  // Since this is a dummy tile without any attached IP (no Chimney), the 
  // Eject port (which would normally deliver packets to the local node) 
  // must be permanently tied off to avoid floating inputs or invalid transactions.
  assign router_floo_req_in[Eject]       = '0;
  assign router_floo_rsp_in[Eject]       = '0;
  assign router_floo_wide_in[Eject]      = '0;

endmodule : ${p_name}_dummy_tile
