//
// AUTOMATICALLY GENERATED BY OLLIVANDER
//
// SystemVerilog Testbench for ${config.project.name}

`timescale 1ns/1ps

module tb_${config.project.name}();

  // ===========================================================================
  // Clock and Reset definitions
  // ===========================================================================
  logic pwr_on_rst_ni;
  logic [${config.clock_tree.flls - 1}:0] domain_clk_i;
  logic [${config.clock_tree.flls - 1}:0] fll_lock_i;
  logic test_mode_i;
  logic [1:0] boot_mode_i;

  // ===========================================================================
  // Clock Generation
  // ===========================================================================
  for (genvar i = 0; i < ${config.clock_tree.flls}; i++) begin: gen_clocks
    initial begin
      domain_clk_i[i] = 1'b0;
      forever #5 domain_clk_i[i] = ~domain_clk_i[i];
    end
  end

  // ===========================================================================
  // Reset Generation
  // ===========================================================================
  initial begin
    pwr_on_rst_ni = 1'b0;
    test_mode_i   = 1'b0;
    boot_mode_i   = 2'b0;
    fll_lock_i    = '0;
    #100;
    pwr_on_rst_ni = 1'b1;
    #1000;
    fll_lock_i = '1; // Assert FLL lock after reset is stable
  end

  // ===========================================================================
  // DUT Instantiation
  // ===========================================================================
  ${config.project.name} dut (
    .domain_clk_i  (domain_clk_i),
    .fll_lock_i    (fll_lock_i),
    .pwr_on_rst_ni (pwr_on_rst_ni),
    .test_mode_i   (test_mode_i),
    .boot_mode_i   (boot_mode_i)
  );

  // ===========================================================================
  // Memory Preload ($readmemh)
  // ===========================================================================
<%
testbench_cfg = config.testbench or {}
preload_mems = testbench_cfg.get("preload_memories", [])
%>
% if preload_mems:
  initial begin
  % for mem in preload_mems:
    $display("[TB] Preloading memory ${mem['instance']} with ${mem['file']}...");
    $readmemh("${mem['file']}", dut.${mem['instance']});
  % endfor
  end
% endif

  // ===========================================================================
  // Test Sequence
  // ===========================================================================
  initial begin
    $display("[TB] Starting Simulation for ${config.project.name}...");
    // Wait for reset deassertion
    @(posedge pwr_on_rst_ni);
    $display("[TB] Reset deasserted. Running...");
    
    // Add your custom test stimuli here...
    #5000;
    
    $display("[TB] Simulation finished.");
    $finish;
  end

endmodule
