//
// AUTOMATICALLY GENERATED BY OLLIVANDER
//
// =============================================================================
// MAKO TEMPLATE FOR THE SOC SYSTEMVERILOG TESTBENCH
// =============================================================================
// This template generates a standard, out-of-the-box SystemVerilog testbench
// to simulate the generated SoC. It automatically configures the correct clock
// sources, initializes the resets, instantiates the Top-Level DUT, and provides
// an automated memory preloading mechanism to execute compiled C firmware.

// Include auto-generated SystemVerilog register macros from PeakRDL.
// These macros provide the absolute physical addresses of the CSRs, 
// making it extremely easy to write AXI/RegBus stimulus sequences.
`include "${rel_hw_from_tb}/${top_level_module_name}_regs.svh"

`timescale 1ns/1ps

module tb_${config.project.name}();

  // ===========================================================================
  // Clock and Reset definitions
  // ===========================================================================
  logic pwr_on_rst_ni;
  logic test_mode_i;
  logic [1:0] boot_mode_i;
  logic rt_clk_i;
% if config.clock_tree.generators > 0:
  logic [${config.clock_tree.generators - 1}:0] domain_clk_i;
  logic [${config.clock_tree.generators - 1}:0] clk_gen_lock_i;
% else:
  logic clk_i;
  logic rst_ni;
% endif
% if config.topology.type == "noc":
  logic clk_rst_bypass_i;
% endif

  // ===========================================================================
  // Clock Generation
  // ===========================================================================
% if config.clock_tree.generators > 0:
  // Dynamically generates the required number of clock sources (FLLs) 
  // based on the SoC's clock tree configuration.
  for (genvar i = 0; i < ${config.clock_tree.generators}; i++) begin: gen_clocks
    initial begin
      domain_clk_i[i] = 1'b0;
      forever #5 domain_clk_i[i] = ~domain_clk_i[i];
    end
  end
% else:
  initial begin
    clk_i = 1'b0;
    forever #5 clk_i = ~clk_i;
  end
% endif
  initial begin
    rt_clk_i = 1'b0;
    forever #500 rt_clk_i = ~rt_clk_i;
  end

  // ===========================================================================
  // Reset Generation
  // ===========================================================================
  // Standard Power-On Reset (POR) sequence.
  // It holds the reset low, applies clocks, and then releases it.
  initial begin
    pwr_on_rst_ni = 1'b0;
    test_mode_i   = 1'b0;
    boot_mode_i   = 2'b0;
% if config.clock_tree.generators > 0:
    clk_gen_lock_i = '0;
% else:
    rst_ni        = 1'b0;
% endif
% if config.topology.type == "noc":
    clk_rst_bypass_i = 1'b0;
% endif
    #100;
    pwr_on_rst_ni = 1'b1;
% if config.clock_tree.generators > 0:
    #1000;
    clk_gen_lock_i = '1; // Assert FLL lock after reset is stable
% else:
    rst_ni        = 1'b1;
% endif
  end

  // ===========================================================================
  // DUT Instantiation
  // ===========================================================================
  // Instantiates the absolute Top-Level of the generated SoC.
  ${top_level_module_name} dut (
    .pwr_on_rst_ni (pwr_on_rst_ni),
    .test_mode_i   (test_mode_i),
    .boot_mode_i   (boot_mode_i),
    .rt_clk_i      (rt_clk_i)
% if config.clock_tree.generators > 0:
    ,.domain_clk_i  (domain_clk_i)
    ,.${'fll_lock_i' if config.topology.type == "noc" else 'clk_gen_lock_i'} (clk_gen_lock_i)
% else:
    ,.clk_i         (clk_i)
    ,.rst_ni        (rst_ni)
% endif
% if config.topology.type == "noc":
    ,.clk_rst_bypass_i (clk_rst_bypass_i)
% endif
  );

  // ===========================================================================
  // Memory Preload ($readmemh)
  // ===========================================================================
  // Extracts the 'preload_memories' configuration from the YAML testbench 
  // section. It uses standard $readmemh to inject compiled firmware (hex) 
  // directly into the hierarchical SRAM instances before the boot sequence.
  // This avoids the need for complex JTAG/SPI boot preloaders in simulation.
<%
testbench_cfg = config.testbench or {}
preload_mems = testbench_cfg.get("preload_memories", [])
%>
% if preload_mems:
  initial begin
  % for mem in preload_mems:
    $display("[TB] Preloading memory ${mem['instance']} with ${mem['file']}...");
    $readmemh("${mem['file']}", dut.${mem['instance']});
  % endfor
  end
% endif

  // ===========================================================================
  // Test Sequence
  // ===========================================================================
  initial begin
    $display("[TB] Starting Simulation for ${config.project.name}...");
    // Wait for reset deassertion
    @(posedge pwr_on_rst_ni);
    $display("[TB] Reset deasserted. Running...");
    
    // =========================================================================
    // CUSTOM TEST STIMULI
    // =========================================================================
    // You can write your custom SystemVerilog tests here.
    // Use the PeakRDL macros (e.g., `${config.project.name.upper()}_SYS_CTRL_BASE_ADDR`) 
    // to drive AXI VIPs or directly peek into the design.

    #5000;
    
    $display("[TB] Simulation finished.");
    $finish;
  end

endmodule
