//
<%!
  import re
%>
// AUTOMATICALLY GENERATED BY OLLIVANDER
//
// =============================================================================
// MAKO TEMPLATE FOR THE SOC SYSTEMVERILOG TESTBENCH
// =============================================================================
// This template generates a standard, out-of-the-box SystemVerilog testbench
// to simulate the generated SoC. It automatically configures the correct clock
// sources, initializes the resets, instantiates the Top-Level DUT, and provides
// an automated memory preloading mechanism to execute compiled C firmware.

// Include auto-generated SystemVerilog register macros from PeakRDL.
// These macros provide the absolute physical addresses of the CSRs, 
// making it extremely easy to write AXI/RegBus stimulus sequences.
`include "${rel_hw_from_tb}/${top_level_module_name}_regs.svh"

`timescale 1ns/1ps

module tb_${top_level_module_name}();

<%
  has_axi_ports = 'axi_req_t' in top_level_params
  has_axi_mst_ports = 'axi_master_req_t' in top_level_params
  is_cheshire = "cheshire" in original_isle_types.get(config.host.name, getattr(config.host, "type", "")).lower()
%>\
% if has_axi_ports:
  // AXI type overrides for top-level port declarations
  typedef ${config.project.name}_soc_pkg::soc_axi_req_t axi_req_t;
  typedef ${config.project.name}_soc_pkg::soc_axi_resp_t axi_resp_t;
% endif
% if has_axi_mst_ports:
  typedef ${config.project.name}_soc_pkg::soc_axi_slv_req_t axi_master_req_t;
  typedef ${config.project.name}_soc_pkg::soc_axi_slv_resp_t axi_master_resp_t;
% endif
  // ===========================================================================
  // Clock and Reset definitions
  // ===========================================================================
<%
  has_rt_clk = any(dom.is_real_time and (dom.source_gen is None or config.clock_tree.generators == 0) for dom in config.clock_tree.domains)

  def find_component(comp_name, config):
      if config.topology.type == "noc" and "i_tile_" in comp_name:
          parts = comp_name.split('.')
          tile_part = [p for p in parts if p.startswith("i_tile_")]
          if tile_part:
              tile_sub = tile_part[0].replace("i_tile_", "")
              coords = tile_sub.split('_')
              if len(coords) >= 2:
                  try:
                      tx, ty = int(coords[0]), int(coords[1])
                      comps = [config.host] + (config.components if config.components else [])
                      for c in comps:
                          p = getattr(c, 'placement', None)
                          if not p or 'logical' not in p: continue
                          log = p['logical']
                          items = log if isinstance(log, list) else [log]
                          for item in items:
                              if 'box' in item:
                                  b = item['box']
                                  if b['x_start'] <= tx <= b['x_end'] and b['y_start'] <= ty <= b['y_end']:
                                      return c
                              else:
                                  if (item or {}).get('x') == tx and (item or {}).get('y') == ty:
                                      return c
                  except ValueError:
                      pass
      clean_name = comp_name
      if '.' in clean_name:
          clean_name = clean_name.split('.')[0]
      if clean_name.startswith("i_"):
          clean_name = clean_name[2:]
      for comp in config.components:
          if comp.name == clean_name:
              return comp
      return None
%>\
  logic pwr_on_rst_ni;
  logic test_mode_i;
  logic [1:0] boot_mode_i;
% if has_rt_clk:
  logic rt_clk_i;
% endif
% if config.clock_tree.generators > 0:
  logic [${config.clock_tree.generators - 1}:0] domain_clk_i;
  logic [${config.clock_tree.generators - 1}:0] clk_gen_lock_i;
% else:
  logic clk_i;
  logic rst_ni;
% endif
% if config.topology.type == "noc":
  logic clk_rst_bypass_i;
% endif

  // ===========================================================================
  // Top-Level Stub Declarations (TFMPC Missing Connection Fix)
  // ===========================================================================
<%
  stubs = []
  for p_name, p_info in top_level_ports.items():
      if p_name in ['clk_i', 'rst_ni', 'pwr_on_rst_ni', 'test_mode_i', 'boot_mode_i', 'domain_clk_i', 'clk_gen_lock_i', 'fll_lock_i', 'clk_rst_bypass_i', 'rt_clk_i']:
          continue
      stubs.append(f"  {p_info['decl']};")
  stubs_str = "\n".join(stubs)
%>\
${stubs_str}

  // ===========================================================================
  // Clock Generation
  // ===========================================================================
% if config.clock_tree.generators > 0:
  // Dynamically generates the required number of clock sources (FLLs) 
  // based on the SoC's clock tree configuration.
  <%
    periods = config.clock_tree.generator_periods_ns or [10.0] * config.clock_tree.generators
    if len(periods) < config.clock_tree.generators:
        periods += [10.0] * (config.clock_tree.generators - len(periods))
  %>
  real gen_period_0;
  initial begin
    if ($test$plusargs("fast_boot")) begin
      gen_period_0 = 20.0; // 50 MHz for fast boot to avoid CDC lock
    end else begin
      gen_period_0 = ${periods[0]}; // Default period from configuration
    end
  end


  % for i in range(config.clock_tree.generators):
  initial begin
    domain_clk_i[${i}] = 1'b0;
    // Set clock period: ${periods[i]} ns
    % if i == 0:
    #0.1; // Small initial phase alignment delay
    forever #(gen_period_0 / 2.0) domain_clk_i[0] = ~domain_clk_i[0];
    % else:
      % if i > 0 and periods[i] == 10.0:
    #${round(1.1 * i, 1)}; // Phase offset to prevent simulation clock races
      % endif
    forever #${periods[i] / 2.0} domain_clk_i[${i}] = ~domain_clk_i[${i}];
    % endif
  end
  % endfor
% else:
  initial begin
    clk_i = 1'b0;
    forever #5 clk_i = ~clk_i;
  end
% endif
% if has_rt_clk:
  <%
    rt_period = getattr(config.clock_tree, 'rt_clk_period_ns', 1000.0)
    if rt_period is None:
        rt_period = 1000.0
    rt_half_period = rt_period / 2.0
  %>\
  initial begin
    rt_clk_i = 1'b0;
    forever #${rt_half_period} rt_clk_i = ~rt_clk_i;
  end
% endif

  // ===========================================================================
  // Reset Generation
  // ===========================================================================
  // Standard Power-On Reset (POR) sequence.
  // It holds the reset low, applies clocks, and then releases it.
  initial begin
    pwr_on_rst_ni = 1'b0;
    test_mode_i   = 1'b0;
    boot_mode_i   = 2'b0;
<%
    reset_initials = []
    for p_name, p_info in top_level_ports.items():
        if p_name in ['clk_i', 'rst_ni', 'pwr_on_rst_ni', 'test_mode_i', 'boot_mode_i', 'domain_clk_i', 'clk_gen_lock_i', 'fll_lock_i', 'clk_rst_bypass_i', 'rt_clk_i']:
            continue
        if p_info["dir"] == 'input':
            if p_name == 'uart_rx_i':
                reset_initials.append("    uart_rx_i = 1'b1; // UART RX idle-high")
            else:
                reset_initials.append(f"    {p_name} = '0;")
    reset_initials_str = "\n".join(reset_initials)
%>\
${reset_initials_str}
% if config.clock_tree.generators > 0:
    clk_gen_lock_i = '0;
% else:
    rst_ni        = 1'b0;
% endif
% if config.topology.type == "noc":
    clk_rst_bypass_i = 1'b0;
% endif
    #100;
    pwr_on_rst_ni = 1'b1;
% if config.clock_tree.generators > 0:
    #1000;
    clk_gen_lock_i = '1; // Assert FLL lock after reset is stable
% else:
    rst_ni        = 1'b1;
% endif
  end

  // ===========================================================================
  // DUT Instantiation
  // ===========================================================================
  // Instantiates the absolute Top-Level of the generated SoC.
<%
  dut_ports = []
  dut_ports.append("    .pwr_on_rst_ni (pwr_on_rst_ni)")
  dut_ports.append("    .test_mode_i   (test_mode_i)")
  dut_ports.append("    .boot_mode_i   (boot_mode_i)")
  if has_rt_clk:
      dut_ports.append("    .rt_clk_i      (rt_clk_i)")
  if config.clock_tree.generators > 0:
      dut_ports.append("    .domain_clk_i  (domain_clk_i)")
      lock_name = 'fll_lock_i' if config.topology.type == "noc" else 'clk_gen_lock_i'
      dut_ports.append(f"    .{lock_name} (clk_gen_lock_i)")
  else:
      dut_ports.append("    .clk_i         (clk_i)")
      dut_ports.append("    .rst_ni        (rst_ni)")
  if config.topology.type == "noc":
      dut_ports.append("    .clk_rst_bypass_i (clk_rst_bypass_i)")
      
  # Automatically mapped top-level ports
  for p_name in top_level_ports.keys():
      if p_name in ['clk_i', 'rst_ni', 'pwr_on_rst_ni', 'test_mode_i', 'boot_mode_i', 'domain_clk_i', 'clk_gen_lock_i', 'fll_lock_i', 'clk_rst_bypass_i', 'rt_clk_i']:
          continue
      dut_ports.append(f"    .{p_name} ({p_name})")
      
  dut_ports_str = ",\n".join(dut_ports)
%>\
  ${top_level_module_name} \
% if has_axi_ports or has_axi_mst_ports:
  #(
<%
    params = []
    if has_axi_ports:
      params.append(".axi_req_t(axi_req_t)")
      params.append(".axi_resp_t(axi_resp_t)")
    if has_axi_mst_ports:
      params.append(".axi_master_req_t(axi_master_req_t)")
      params.append(".axi_master_resp_t(axi_master_resp_t)")
%>\
    ${",\n    ".join(params)}
  ) \
% endif
  dut (
${dut_ports_str}
  );

  // ===========================================================================
  // Memory Preload ($readmemh)
  // ===========================================================================
  // Extracts the 'preload_memories' configuration from the YAML testbench 
  // section. It uses standard $readmemh to inject compiled firmware (hex) 
  // directly into the hierarchical SRAM instances before the boot sequence.
  // This avoids the need for complex JTAG/SPI boot preloaders in simulation.
<%
testbench_cfg = config.testbench or {}
preload_mems = testbench_cfg.get("preload_memories", [])
all_comps = [config.host] + (config.components if config.components else [])

def resolve_param_val(val, comp, fixed_params=None):
    import re
    if not val:
        return 0
    if str(val).isdigit():
        return int(val)
    params = {}
    if comp and comp.parameters:
        params.update(comp.parameters)
    if fixed_params:
        for k, v in fixed_params.items():
            if k not in params:
                params[k] = v
    if "AxiDataWidth" not in params:
        if config.topology.type == "noc":
            interfaces = getattr(comp, "interfaces", {}) or {}
            noc_nets = interfaces.get("noc_networks", {}) or {}
            noc_mode = noc_nets.get("noc_mode", "")
            slv_nets = noc_nets.get("slave", [])
            mst_nets = noc_nets.get("master", [])
            if "wide" in slv_nets or "wide" in mst_nets or noc_mode == "joined":
                params["AxiDataWidth"] = 512
            else:
                params["AxiDataWidth"] = 64
        else:
            params["AxiDataWidth"] = 64
    val_str = str(val)
    for pk, pv in params.items():
        val_str = re.sub(rf'\b{pk}\b', str(pv), val_str)
    val_str = re.sub(rf'\(int unsigned\)|\(int\)', '', val_str)
    try:
        val_str = val_str.replace('/', '//')
        return int(eval(val_str, {"__builtins__": None}, {}))
    except Exception:
        digits = re.findall(r'\d+', val_str)
        if digits:
            return int(digits[0])
        return 1
%>
% if preload_mems:
  % for mem in preload_mems:
    <%
    comp_name = mem['instance']
    matched_comp = find_component(comp_name, config)
    comp_key = matched_comp.name if matched_comp else comp_name
    c_info = comp_info.get(comp_key) or {}
    fixed_params = c_info.get("fixed_params", {})
    supported_params = c_info.get("supported_params", {})
    preload_type = fixed_params.get("PreloadType", "").strip('"\'')
    %>
    % if preload_type == "interleaved":
      <%
      preload_template = fixed_params.get("PreloadTemplate", "").strip('"\'')
      bank_width = resolve_param_val(fixed_params.get("PreloadBankWidth"), matched_comp, fixed_params)
      num_groups = resolve_param_val(fixed_params.get("PreloadNumGroups"), matched_comp, fixed_params)
      num_banks_per_group = resolve_param_val(fixed_params.get("PreloadBanksPerGroup"), matched_comp, fixed_params)
      if num_banks_per_group == 0 and bank_width > 0:
          data_width = resolve_param_val("AxiDataWidth", matched_comp, fixed_params)
          num_banks_per_group = data_width // bank_width
      basename, ext = mem['file'].rsplit('.', 1)
      %>
      initial begin
        // Wait for reset to be released on the memory wrapper
        @(posedge dut.${comp_name}.rst_ni);
        #10;
      % for g in range(num_groups):
        % for b in range(num_banks_per_group):
          <%
          instance_path = preload_template.format(group=g, bank=b)
          if comp_name.endswith('.i_isle') and instance_path.startswith('i_isle.'):
              instance_path = instance_path[len('i_isle.'):]
          elif comp_name.endswith('.i_subtile') and instance_path.startswith('i_subtile.'):
              instance_path = instance_path[len('i_subtile.'):]
          %>
          $display("[TB] Preloading interleaved memory G${g}B${b} with ${basename}_g${g}_b${b}.${ext}...");
          $readmemh("${basename}_g${g}_b${b}.${ext}", dut.${comp_name}.${instance_path});
        % endfor
      % endfor
      end
    % else:
      initial begin
        // Wait for reset to be released on the memory wrapper
        @(posedge dut.${comp_name}.rst_ni);
        #10;
        $display("[TB] Preloading memory ${comp_name} with ${mem['file']}...");
        $readmemh("${mem['file']}", dut.${comp_name});
      end
    % endif
  % endfor
% endif

<%
uart_base = None
import re
uart_tx_port = None
ports_to_search = (top_ports or []) + (all_extra_ports or [])
for port_decl in ports_to_search:
    words = re.findall(r'\b[a-zA-Z_][a-zA-Z0-9_]*\b', port_decl)
    for w in words:
        if "uart" in w.lower() and "tx" in w.lower() and "output" in port_decl:
            uart_tx_port = w
            break
    if uart_tx_port:
        break

all_comps = [config.host] + (config.components if config.components else [])
for comp in all_comps:
    c_name = getattr(comp, "name", "").lower()
    c_type = getattr(comp, "type", "").lower()
    if "uart" in c_name or "uart" in c_type:
        interfaces = getattr(comp, "interfaces", {}) or {}
        slaves = interfaces.get("axi_slave", [])
        if isinstance(slaves, dict): slaves = [slaves]
        reg_slaves = interfaces.get("regbus_slave", [])
        if isinstance(reg_slaves, dict): reg_slaves = [reg_slaves]
        all_slaves = slaves + reg_slaves
        if all_slaves:
            b_addr = all_slaves[0].get("base_addr", 0)
            uart_base = hex(b_addr) if isinstance(b_addr, int) else str(b_addr)
            break

if not uart_base:
    if is_cheshire and getattr(config.host, "parameters", {}).get("Uart", True):
        uart_base = "0x03002000"
%>

% if preload_mems:
  // ===========================================================================
  // AXI Transaction Monitor variables
  // ===========================================================================
  % for mem in preload_mems:
    <%
    comp_name = mem['instance']
    clean_name = comp_name
    is_hier = '.' in comp_name
    if is_hier:
        comp_instance = comp_name.split('.')[0]
        clean_name = comp_instance
    if clean_name.startswith("i_"):
        clean_name = clean_name[2:]
        
    ports = 1
    for comp in config.components:
        if comp.name == clean_name:
            interfaces = getattr(comp, "interfaces", {}) or {}
            slaves = interfaces.get("axi_slave", [])
            if slaves:
                ports = slaves[0].get("ports", 1)
            break
    %>
    % for p in range(ports):
  logic ${comp_name.replace('.', '_')}_p${p}_ar_pending;
  initial ${comp_name.replace('.', '_')}_p${p}_ar_pending = 0;
    % endfor
  % endfor
% endif

% if uart_base:
  // ===========================================================================
  // UART TX Monitor (Self-contained serial receiver dynamically bound to top-level UART port)
  // ===========================================================================
  localparam real BaudRate = 115200.0;
  localparam real BitPeriodNs = 1_000_000_000.0 / BaudRate; // ~8680.55 ns per bit

  logic [7:0] rx_char;
  string rx_string;
  int rx_char_num = 0;

  initial begin
    rx_string = "";
  end

  always begin
    // 1. Wait for falling edge on uart_tx_o (Start bit)
    @(negedge dut.${uart_tx_port});
    
    // 2. Wait 1.5 bit periods to align sampling at the center of the first data bit
    #(BitPeriodNs * 1.5);
    
    // 3. Sample 8 data bits at 1.0 bit period intervals
    for (int i = 0; i < 8; i++) begin
      rx_char[i] = dut.${uart_tx_port};
      #(BitPeriodNs);
    end
    
    // 4. Print the character or accumulate the line of text
    if (rx_char == 8'h04) begin // EOT (End of Transmission)
      $display("[TB] EOT received. Simulation finished.");
      $finish;
    end else if (rx_char == 8'h0A) begin // Newline (\n)
      $write("[UART]: \"%s\"\n", rx_string);
      $fflush(32'h8000_0001); // Flush stdout to see character immediately
      rx_string = "";
      rx_char_num = 0;
    end else if (rx_char >= 32 && rx_char <= 126) begin // Printable ASCII
      rx_string = {rx_string, rx_char};
      rx_char_num = rx_char_num + 1;
    end
  end
% endif

  // ===========================================================================
  // Fast Simulation Boot Mode (+fast_boot)
  // ===========================================================================
  // Bypasses the real-time clock dividers in simulation to speed up the 
  // bootrom's core frequency measurement phase.
  initial begin
    if ($test$plusargs("fast_boot")) begin
      $display("[TB] Fast boot mode enabled: bypassing real-time clock divider.");
<%
  fast_boots = []
  for dom in config.clock_tree.domains:
      if dom.is_real_time and dom.static_div is not None and dom.static_div > 1:
          fast_boots.append(f"      force dut.i_{dom.name}_static_div.test_mode_en_i = 1'b1;")
  fast_boots_str = "\n".join(fast_boots)
%>\
% if fast_boots_str:
${fast_boots_str}
% endif
    end
  end

  // ===========================================================================
  // Test Sequence
  // ===========================================================================
  initial begin
    $timeformat(-6, 3, " us", 12);
    $display("[TB] Starting Simulation for ${config.project.name}...");
    // Wait for reset deassertion
    @(posedge pwr_on_rst_ni);
    $display("[TB] Reset deasserted. Running...");
    
    // =========================================================================
    // CUSTOM TEST STIMULI
    // =========================================================================
    // You can write your custom SystemVerilog tests here.
    // Use the PeakRDL macros (e.g., `${config.project.name.upper()}_SYS_CTRL_BASE_ADDR`) 
    // to drive AXI VIPs or directly peek into the design.
<%
  host_info = comp_info.get(config.host.name) or {}
  host_fixed = host_info.get("fixed_params", {})
  has_force_boot = host_fixed.get("HasForceBoot", "0").strip('"\'') == "1"
  testbench_cfg = config.testbench or {}
  sim_timeout_ns = testbench_cfg.get("sim_timeout_ns", 10000000)
  if config.topology.type == "noc":
      host_instance_name = f"i_tile_{config.host.placement['logical']['x']}_{config.host.placement['logical']['y']}"
  else:
      host_instance_name = f"i_{config.host.name}"
%>
% if has_force_boot:
<%
  entry_point = 0x78000000 # default fallback
  preload_mems = testbench_cfg.get("preload_memories", [])
  boot_force_delay_ns = testbench_cfg.get("boot_force_delay_ns", 5000000)
  boot_force_fast_delay_ns = testbench_cfg.get("boot_force_fast_delay_ns", 1000000)
  boot_timeout_ns = testbench_cfg.get("boot_timeout_ns", 10000000)
  boot_timeout_fast_ns = testbench_cfg.get("boot_timeout_fast_ns", 2000000)
  for mem in preload_mems:
      comp_name = mem['instance']
      comp = find_component(comp_name, config)
      if comp:
          interfaces = getattr(comp, "interfaces", {}) or {}
          slaves = interfaces.get("axi_slave", [])
          if slaves:
              entry_point = slaves[0].get("base_addr", entry_point)
              break
  host_clk = config.host.clock_domain or "system_clk"
  managed_domains = [d for d in config.clock_tree.domains if not d.is_real_time and d.name != host_clk]
%>
  // Release CPU from passive boot loop by pointing scratch registers to preloaded memory (0x${f"{entry_point:08x}"})
  #1200;
<%
  release_passive_initials = []
  for dom in managed_domains:
      reg_name = dom.name.replace("_clk", "")
      release_passive_initials.append(f"  force dut.i_sys_ctrl_regs.field_storage.{reg_name}_rst.{reg_name}_rst.value = 32'h00000000;")
  release_passive_initials_str = "\n".join(release_passive_initials)
%>\
${release_passive_initials_str}
  #10;
  force dut.${host_instance_name}.${host_fixed.get("ForceBootPath").strip('"\'')} = 32'h${f"{entry_point:08x}"};
  % if is_cheshire:
  // Cheshire specific boot arguments (argc = 0, boot mode = 2 (L2 boot))
  % if config.topology.type == "noc":
  force dut.${host_instance_name}.i_isle.i_cheshire_soc.i_regs.field_storage.scratch[1].scratch.value = 32'h00000000;
  force dut.${host_instance_name}.i_isle.i_cheshire_soc.i_regs.field_storage.scratch[2].scratch.value = 32'h00000002;
  % else:
  force dut.${host_instance_name}.i_cheshire_soc.i_regs.field_storage.scratch[1].scratch.value = 32'h00000000;
  force dut.${host_instance_name}.i_cheshire_soc.i_regs.field_storage.scratch[2].scratch.value = 32'h00000002;
  % endif
  % endif
  
  // Dynamic exit strategy for passive boot loop: release forces as soon as CPU accesses preloaded memory
  % if preload_mems:
    <%
    active_mem = preload_mems[0]['instance']
    %>
  // Reset the monitor flag to clear any spurious pre-boot/reset glitches
  ${active_mem.replace('.', '_')}_p0_ar_pending = 0;
  $display("[TB] Waiting for CPU to start execution from preloaded memory (%s)...", "${active_mem}");
  fork
    begin
      wait (${active_mem.replace('.', '_')}_p0_ar_pending === 1'b1);
    end
    begin
      if ($test$plusargs("fast_boot")) begin
        #${boot_timeout_fast_ns}; // Timeout for fast boot to account for CPU bootrom execution overhead
      end else begin
        #${boot_timeout_ns}; // Timeout for standard boot
      end
      $display("[ERROR] Timeout waiting for CPU to boot and access preloaded memory!");
      $finish;
    end
  join_any
  disable fork;
  #100; // Small guard delay to ensure stability
  % else:
  begin
    real force_delay;
    if ($test$plusargs("fast_boot")) begin
      force_delay = ${boot_force_fast_delay_ns}.0; // Hold duration for fast boot to ensure CPU reads the forced registers
    end else begin
      force_delay = ${boot_force_delay_ns}.0; // Default/configured boot force delay
    end
    #(force_delay);
  end
  % endif
  
  % if has_force_boot:
  // Release Host boot force
  release dut.${host_instance_name}.${host_fixed.get("ForceBootPath").strip('"\'')};
  % if is_cheshire:
  % if config.topology.type == "noc":
  release dut.${host_instance_name}.i_isle.i_cheshire_soc.i_regs.field_storage.scratch[1].scratch.value;
  release dut.${host_instance_name}.i_isle.i_cheshire_soc.i_regs.field_storage.scratch[2].scratch.value;
  % else:
  release dut.${host_instance_name}.i_cheshire_soc.i_regs.field_storage.scratch[1].scratch.value;
  release dut.${host_instance_name}.i_cheshire_soc.i_regs.field_storage.scratch[2].scratch.value;
  % endif
  % endif
  % endif
<%
  release_passive_forces = []
  for dom in managed_domains:
      reg_name = dom.name.replace("_clk", "")
      release_passive_forces.append(f"  release dut.i_sys_ctrl_regs.field_storage.{reg_name}_rst.{reg_name}_rst.value;")
  release_passive_forces_str = "\n".join(release_passive_forces)
%>\
${release_passive_forces_str}
% endif

    #${sim_timeout_ns};
    
    $display("[TB] Simulation finished.");
    $finish;
  end

% if preload_mems:
  // ===========================================================================
  // AXI Transaction Monitor for Preloaded Memories
  // ===========================================================================
  % for mem in preload_mems:
    <%
    comp_name = mem['instance']
    comp = find_component(comp_name, config)
    is_hier = '.' in comp_name
    if is_hier:
        comp_instance = comp_name.split('.')[0]
    ports = 1
    if comp:
        interfaces = getattr(comp, "interfaces", {}) or {}
        slaves = interfaces.get("axi_slave", [])
        if slaves:
            ports = slaves[0].get("ports", 1)
    %>
    % for p in range(ports):
      <%
      var_name = comp_name.replace('.', '_')
      if is_hier:
          clk_path = f"dut.{comp_instance}.clk_i"
          rst_path = f"dut.{comp_instance}.rst_ni"
          req_expr = f"dut.{comp_instance}.i_isle.axi_req_i.ar_valid"
          addr_expr = f"dut.{comp_instance}.i_isle.axi_req_i.ar.addr"
          req_ready_expr = f"dut.{comp_instance}.i_isle.axi_resp_o.ar_ready"
          r_valid_expr = f"dut.{comp_instance}.i_isle.axi_resp_o.r_valid"
          r_ready_expr = f"dut.{comp_instance}.i_isle.axi_req_i.r_ready"
          r_data_expr = f"dut.{comp_instance}.i_isle.axi_resp_o.r.data"
      else:
          clk_path = f"dut.{comp_name}.clk_i"
          rst_path = f"dut.{comp_name}.rst_ni"
          req_expr = f"dut.{comp_name}.axi_async_req[{p}].ar_valid"
          addr_expr = f"dut.{comp_name}.axi_async_req[{p}].ar.addr"
          req_ready_expr = f"dut.{comp_name}.axi_async_rsp[{p}].ar_ready"
          r_valid_expr = f"dut.{comp_name}.axi_async_rsp[{p}].r_valid"
          r_ready_expr = f"dut.{comp_name}.axi_async_req[{p}].r_ready"
          r_data_expr = f"dut.{comp_name}.axi_async_rsp[{p}].r.data"
      %>
  always @(posedge ${clk_path} or negedge ${rst_path}) begin
    if (!${rst_path}) begin
      ${var_name}_p${p}_ar_pending <= 0;
    end else begin
      if (${req_expr} && !${var_name}_p${p}_ar_pending) begin
        $display("[TB_AXI_MON] ${comp_name} Port ${p} AR Request started: addr=0x%08h", ${addr_expr});
        ${var_name}_p${p}_ar_pending <= 1;
      end
      if (${req_expr} && ${req_ready_expr} && ${var_name}_p${p}_ar_pending) begin
        $display("[TB_AXI_MON] ${comp_name} Port ${p} AR Request accepted (READY)");
        ${var_name}_p${p}_ar_pending <= 0;
      end
      if (${r_valid_expr} && ${r_ready_expr}) begin
        $display("[TB_AXI_MON] ${comp_name} Port ${p} Read data: 0x%016h", ${r_data_expr});
      end
    end
  end
    % endfor
  % endfor
% endif
<%
package_name = f"{config.project.name}_soc_pkg"
def fmt_name(name): return name.replace('_clk', '').replace('_rst', '').lower()
gateable_domains = [d for d in config.clock_tree.domains if not d.is_real_time and d.name != 'host_clk']
sensitivity_list = " or ".join([f"dut.rsts_n[{package_name}::DomainIdx_{fmt_name(d.name)}]" for d in gateable_domains])
%>
% if sensitivity_list:
  // Reset monitor debug block: Dynamically monitors physical changes on reset signals 
  // for all clock domains configured in the clock tree.
  always @(${sensitivity_list}) begin
    $display("[TB_DEBUG] Reset wires state changed:");
<%
  reset_displays = []
  for d in gateable_domains:
      reset_displays.append(f'    $display("  - Domain {fmt_name(d.name)} reset (rsts_n[{fmt_name(d.name)}]) = %0b", dut.rsts_n[{package_name}::DomainIdx_{fmt_name(d.name)}]);')
  reset_displays_str = "\n".join(reset_displays)
%>\
${reset_displays_str}
  end
% endif

  // Periodic time progress display block for simulation monitoring
  always begin
    #100000; // Print every 100 us (100,000 ns = 100 us)
    $display("[TB_TIME] Simulation time: %0t", $realtime);
  end

endmodule
