<%
  # ============================================================================
  # MAKO TEMPLATE FOR THE SOC MEMORY MAP (C HEADER)
  # ============================================================================
  p_name = config.project.name.upper()
  
  def fmt_name(name):
      return name.upper()
      
  def parse_hex(val):
      if isinstance(val, int): return f"{val:08X}"
      return str(val).replace('0x', '').replace('_', '').upper().zfill(8)
%><%namespace file="/license_header.mako" import="license"/>\
${license()}\
//
// AUTOMATICALLY GENERATED BY OLLIVANDER - DO NOT EDIT DIRECTLY
//
// C Header for SoC Global Memory Map and Interrupt Routing

#ifndef _${p_name}_SOC_MAP_H_
#define _${p_name}_SOC_MAP_H_

#ifdef __cplusplus
extern "C" {
#endif

// ============================================================================
// MEMORY MAP
// ============================================================================

% if config.system_controller:
// System Controller (PCRs)
#define ${p_name}_${fmt_name(config.system_controller.name)}_BASE_ADDR 0x${parse_hex(config.system_controller.base_addr)}
#define ${p_name}_${fmt_name(config.system_controller.name)}_SIZE      0x${parse_hex(config.system_controller.size)}
% endif

% for comp in config.components:
// --- ${comp.name} ---
 % if comp.interfaces:
  % if 'axi_slave' in comp.interfaces:
   % for slv in (comp.interfaces['axi_slave'] if isinstance(comp.interfaces['axi_slave'], list) else [comp.interfaces['axi_slave']]):
#define ${p_name}_${fmt_name(comp.name)}_BASE_ADDR 0x${parse_hex(slv['base_addr'])}
#define ${p_name}_${fmt_name(comp.name)}_SIZE      0x${parse_hex(slv.get('size', slv.get('size_per_instance', '0x1000')))}
   % endfor
  % endif
  % if 'regbus_slave' in comp.interfaces:
   % for slv in (comp.interfaces['regbus_slave'] if isinstance(comp.interfaces['regbus_slave'], list) else [comp.interfaces['regbus_slave']]):
#define ${p_name}_${fmt_name(comp.name)}_REG_BASE_ADDR 0x${parse_hex(slv['base_addr'])}
#define ${p_name}_${fmt_name(comp.name)}_REG_SIZE      0x${parse_hex(slv.get('size', '0x1000'))}
   % endfor
  % endif
 % endif
 % if comp.components:
  % for sub in comp.components:
   % if sub.base_addr:
#define ${p_name}_${fmt_name(comp.name)}_${fmt_name(sub.name)}_BASE_ADDR 0x${parse_hex(sub.base_addr)}
#define ${p_name}_${fmt_name(comp.name)}_${fmt_name(sub.name)}_SIZE      0x${parse_hex(sub.size)}
   % endif
  % endfor
 % endif

% endfor

// ============================================================================
// INTERRUPT ROUTING MAP (HOST)
// ============================================================================
<%
  import re
  irq_map = []
  if config.host.interrupts:
      for irq_name, irq_cfg in config.host.interrupts.items():
          if 'intr_ext' in irq_name:
              src = str(irq_cfg.get('source', ''))
              matches = re.findall(r'\[(\d+)(?::\d+)?\]\s*:\s*([a-zA-Z0-9_]+)\.([a-zA-Z0-9_]+)', src)
              for idx, comp_name, port_name in matches:
                  irq_map.append((int(idx), comp_name, port_name.replace('_o', '').replace('_i', '')))
  irq_map.sort(key=lambda x: x[0])
%>
% for idx, comp_name, port_name in irq_map:
#define ${p_name}_IRQ_${fmt_name(comp_name)}_${fmt_name(port_name)} ${idx}
% endfor

#ifdef __cplusplus
}  // extern "C"
#endif

#endif // _${p_name}_SOC_MAP_H_