#!/usr/bin/env python3
# Copyright 2026 Fondazione Chips-IT.
# Solderpad Hardware License, Version 0.51, see LICENSE for details.
# SPDX-License-Identifier: SHL-0.51
"""
bin2header.py - wrap a raw binary image into a C header.

Part of the offload test flow: the cluster payload is compiled stand-alone for the
target's ISA, flattened with objcopy -O binary, and embedded here into the HOST
firmware as a const word array, so that a single host ELF carries everything the test
needs (the pattern of astral's elf2header.py, reduced to stdlib-only: no pyelftools,
because the payload linker script keeps the loadable sections contiguous from the
image base, which makes the flat objcopy output exactly the bytes to copy).

The emitted header provides, for a symbol NAME (upper-cased in the macros):
  - NAME_BASE        : the load address the image was linked at (--base)
  - NAME_SIZE_WORDS  : number of 32-bit words in the array
  - name_image[]     : the image itself, little-endian packed 32-bit words

A copy of this script is placed in the generated sw/ directory at generation time, so
the generated Makefile never needs a path into the Ollivander tree.
"""

import argparse
import struct
import sys
from pathlib import Path


def main() -> int:
    parser = argparse.ArgumentParser(description="Embed a raw binary as a C uint32_t array.")
    parser.add_argument("--binary", required=True, help="Input raw binary (objcopy -O binary output).")
    parser.add_argument("--output", required=True, help="Output C header path.")
    parser.add_argument("--symbol", required=True, help="C symbol base name (e.g. payload_pulp_cluster).")
    parser.add_argument("--base", required=True, help="Load address the image was linked at (hex or dec).")
    args = parser.parse_args()

    data = Path(args.binary).read_bytes()
    if not data:
        print(f"[bin2header] ERROR: '{args.binary}' is empty - nothing to embed.", file=sys.stderr)
        return 1

    # Pad to a multiple of 4 so the copy loop can move whole words; the padding lands
    # in the payload's own memory image and is never executed.
    data += b"\x00" * (-len(data) % 4)
    words = struct.unpack(f"<{len(data) // 4}I", data)

    sym = args.symbol.lower()
    mac = args.symbol.upper()
    base = int(args.base, 0)

    lines = [
        "/* Auto-generated by bin2header.py - do not edit. */",
        f"#ifndef {mac}_H",
        f"#define {mac}_H",
        "",
        "#include <stdint.h>",
        "",
        f"#define {mac}_BASE       0x{base:08x}u",
        f"#define {mac}_SIZE_WORDS {len(words)}u",
        "",
        f"static const uint32_t {sym}_image[{len(words)}] = {{",
    ]
    for i in range(0, len(words), 8):
        chunk = ", ".join(f"0x{w:08x}u" for w in words[i:i + 8])
        lines.append(f"    {chunk},")
    lines += ["};", "", f"#endif /* {mac}_H */", ""]

    Path(args.output).write_text("\n".join(lines), encoding="utf-8")
    print(f"[bin2header] {args.binary} -> {args.output} ({len(words)} words @ 0x{base:08x})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
