# Copyright 2026 Fondazione Chips-IT.
# Solderpad Hardware License, Version 0.51, see LICENSE for details.
# SPDX-License-Identifier: SHL-0.51

"""
Boundary geometry of a nested macro, and the NoC ID widths derived from it.

A macro is generated by its own Ollivander run and consumed by another, so the
parent cannot recompute what the macro exports: the master ID width of a crossbar
macro is `AxiIdWidth + $clog2(<number of masters>)`, and that count is known only
inside the project that generated it. The macro therefore *publishes* the numbers
as plain literals in its SoC package (see the "boundary geometry" block emitted by
crossbar_soc_pkg.sv.mako and noc_soc_pkg.sv.mako), and this module reads them back.

Two kinds of number cross the boundary, and the distinction drives everything here:

  * what a macro **imposes**. The exported master port of an isle macro carries the
    ID width of the crossbar behind it. Nothing can retype it narrower without
    aliasing IDs, so the network it plugs into must be at least that wide.
  * what a macro **accepts**. A subtile macro plugs its slave ports straight into
    its own internal chimneys, which accept the InIdWidth of the network FlooGen
    generated for it. A parent network wider than that would be truncated at the
    boundary, so this is an upper bound, not something to adapt.

The width of a network is therefore a property shared by every macro attached to
it, while the macros are generated independently and none of them can see the
others. The consequence is deliberate: the value is derived where it can be
(the maximum over what the attached macros impose) and **refused** where it cannot
(a maximum that exceeds what an attached macro accepts), never silently adapted.
"""

import re
import sys

# The published literals. Kept as one table so the emitting templates and this
# reader cannot drift apart silently: a name that stops being emitted stops being
# found, and read_macro_boundary reports it.
_IMPOSED = "MacroMstIdWidth"
_ACCEPTED = {"narrow": "MacroNarrowInIdWidth", "wide": "MacroWideInIdWidth"}
_USER_SPAN = "MacroMstUserSpan"
_USER_WIDTH = "MacroMstUserWidth"

# FlooNoC's own defaults for the input side of each network, kept here rather than in
# the FlooGen config template so that the package and the config agree by
# construction.
_DEFAULT_ID_WIDTH = {"narrow": 4, "wide": 3}

# The output side of each network: the compressed ID width a subordinate receives from
# a chimney. A FlooNoC design choice rather than a property of the attached components,
# so it is not derived from anything - but it is the other half of the capacity check
# (a component must accept at least this many bits), so it lives next to the input
# defaults and the FlooGen template renders it from here.
NOC_OUTPUT_ID_WIDTH = {"narrow": 2, "wide": 1}


def clog2(value: int) -> int:
    """
    Integer $clog2, matching SystemVerilog exactly.

    Written with bit_length rather than math.log2 so that an exact power of two
    cannot round the wrong way: $clog2(8) is 3, and ceil(log2(8)) computed in
    floating point is one rounding error away from 4.
    """
    return max(value - 1, 1).bit_length()


def read_macro_boundary(macro_type, component_paths):
    """
    Read the boundary geometry a nested macro publishes.

    `macro_type` is the component 'type' naming the macro, which is also the stem
    of its generated files, so the package sits beside the module: `crux_isle.sv`
    and `crux_isle_soc_pkg.sv`. Returns a dict of the literals found, empty if the
    package is not among the component paths - which is not an error here, since
    the same lookup is what tells a plain component apart from a nested macro.
    """
    pkg_name = f"{macro_type}_soc_pkg.sv"
    for cp in component_paths:
        try:
            pkg_path = next(cp.rglob(pkg_name))
        except StopIteration:
            continue
        try:
            text = pkg_path.read_text(encoding="utf-8")
        except OSError as e:
            print(f"  [WARNING] Cannot read the package of macro '{macro_type}' at '{pkg_path}': {e}")
            return {}
        found = {}
        for name in [_IMPOSED, _USER_SPAN, _USER_WIDTH, *_ACCEPTED.values()]:
            m = re.search(rf"localparam\s+int\s+unsigned\s+{name}\s*=\s*(\d+)\s*;", text)
            if m:
                found[name] = int(m.group(1))
        return found
    return {}


def crossbar_master_count(soc_config):
    """
    Number of managers on the crossbar of a crossbar-topology SoC: the host's internal
    ones, counted from its feature parameters, plus one per component exporting an AXI
    master. This is the count behind the slave-side ID width, extracted here so that the
    SoC package template, the boundary geometry it publishes and the connection checks
    in wiring.py all derive the width from the same formula - it used to live inline in
    the template, and everything else either duplicated it or hardcoded its result.
    """
    host_params = (soc_config.host.parameters or {}) if soc_config.host else {}
    internal = (int(host_params.get('NumCores', 1))
                + 1                                                 # debug module, always present
                + (1 if host_params.get('Dma', True) else 0)
                + (1 if host_params.get('SerialLink', True) else 0)
                + (1 if host_params.get('Vga', True) else 0)
                + (1 if host_params.get('Usb', True) else 0))
    external = sum(1 for c in (soc_config.components or [])
                   if c.interfaces and c.interfaces.get('axi_master'))
    return internal + external


def crossbar_slv_id_width(soc_config):
    """Slave-side AXI ID width of the crossbar: the manager ID plus the arbitration bits."""
    return (soc_config.topology.global_bus.mst_id_width
            + clog2(max(crossbar_master_count(soc_config), 2)))


def user_span(soc_config):
    """
    Number of AXI user bits that carry semantics, from the SoC's own mapping: the span
    up to the highest of the AMO reservation bits and the ECC error flag. Everything
    above it is spare, and is what a macro boundary may truncate without losing
    anything. One definition, used by both the crossbar and the NoC package templates.
    """
    um = soc_config.system_settings.user_mapping if soc_config.system_settings else None
    return (max(um.amo_msb, um.ecc_err_bit) + 1) if um else 1


def resolve_noc_user_widths(soc_config):
    """
    Width of the AXI user field each network carries.

    The narrow network carries the span of the SoC user mapping that has defined
    semantics, up to the highest of the AMO reservation bits and the ECC error flag.
    The wide network deliberately carries one bit: every endpoint reading user bits
    sits behind a narrow/wide join and floo_pkg::axi_join_cfg takes UserWidth as the
    maximum of the two, so widening the wide one gains nothing and costs a mismatch
    against snitch_cluster's own one-bit user_dma_t. The reasoning is spelled out in
    floogen_cfg.yml.mako, which renders these values; they live here so that the
    boundary check below and the network configuration cannot disagree about them.
    """
    return {"narrow": user_span(soc_config), "wide": 1}


def resolve_noc_id_widths(soc_config, component_paths, original_types=None, report=True):
    """
    Resolve the per-network ID width of a NoC, and refuse an inconsistent one.

    Returns {'narrow': <int>, 'wide': <int>} for the input side of each network.
    A network declaring 'id_width' keeps that value and is only checked; a network
    leaving it unset takes the maximum imposed by the macros attached to it, with
    the FlooNoC minimum as the floor.

    `original_types` maps a component name to the type it was declared with. It is
    required, not optional in practice: by the time the templates are rendered the
    generator has rewritten every component's type to the name of its tile wrapper
    ('crux_subsystem_tile'), and the macro's package is named after the declared type
    ('crux_isle_soc_pkg.sv'). Without the map every lookup misses and every network
    silently falls back to the FlooNoC default.
    """
    original_types = original_types or {}
    noc = soc_config.topology.noc_settings
    networks = (noc.networks if noc else None) or {}
    user_widths = resolve_noc_user_widths(soc_config)
    resolved, floors = {}, {}

    # What the attached macros impose, and what they accept, gathered in one pass so
    # that both diagnostics can name the component the user actually wrote.
    imposed, accepted = {}, {}
    for comp in soc_config.components or []:
        published = read_macro_boundary(original_types.get(comp.name, comp.type), component_paths)
        if not published:
            continue
        nets = ((comp.interfaces or {}).get("noc_networks") or {})
        for net in nets.get("master", []) or []:
            if _IMPOSED in published:
                imposed.setdefault(net, []).append((comp.name, published[_IMPOSED]))
            # The user field is the one part of the boundary that is *truncated* rather
            # than adapted: the macro drops the bits above its own span on the way out,
            # which is lossless only while the network carries that whole span. It is
            # checked here rather than left to the truncation, because a silent loss of
            # the AMO reservation id would surface as a livelock, not as a warning.
            span = published.get(_USER_SPAN)
            if span is not None and span > user_widths.get(net, 0):
                print(f"\n[ERROR] The macro '{comp.name}' carries {span} meaningful user bits on its master "
                      f"port, but the '{net}' network carries {user_widths.get(net, 0)}.\n"
                      f"        Its {_USER_WIDTH.replace('MacroMst', '')} is {published.get(_USER_WIDTH, '?')} "
                      f"bits, of which the span up to the highest of the AMO reservation and the ECC error flag "
                      f"has semantics and cannot be dropped.\n"
                      f"        Align 'system_settings.user_mapping' of the two projects, or inject this macro "
                      f"on a network that carries its span.")
                sys.exit(1)
        for net in nets.get("slave", []) or []:
            name = _ACCEPTED.get(net)
            if name and name in published:
                accepted.setdefault(net, []).append((comp.name, published[name]))

    for net_name, net in networks.items():
        if net_name not in _DEFAULT_ID_WIDTH:
            continue
        floor = getattr(net, "id_width", None)
        needed = max([w for _, w in imposed.get(net_name, [])] or [0])
        floors[net_name] = floor
        resolved[net_name] = floor if floor is not None else max(needed, _DEFAULT_ID_WIDTH[net_name])

        if floor is not None and needed > floor:
            culprits = ", ".join(f"'{n}' ({w} bits)" for n, w in imposed[net_name] if w > floor)
            print(f"\n[ERROR] The '{net_name}' network declares 'id_width: {floor}', but the master port of "
                  f"{culprits} imposes more.\n"
                  f"        A macro master port cannot be retyped narrower without aliasing its IDs. Either raise "
                  f"'id_width' to {needed} or remove it, in which case it is derived.")
            sys.exit(1)

        for comp_name, limit in accepted.get(net_name, []):
            if resolved[net_name] > limit:
                print(f"\n[ERROR] The '{net_name}' network resolves to an ID width of {resolved[net_name]} bits, but "
                      f"the macro '{comp_name}' accepts at most {limit}.\n"
                      f"        Its slave port feeds the chimneys of its own network, so the extra bits would be "
                      f"truncated at the boundary and transactions would alias.\n"
                      f"        Declare 'id_width: {resolved[net_name]}' on the '{net_name}' network of the project "
                      f"that generates '{comp_name}' and regenerate it.")
                sys.exit(1)

    # Reported because the value is invisible from inside the project once derived: it
    # comes from a macro generated elsewhere, and a network silently one bit too narrow
    # is exactly the failure this module exists to prevent. Callers that resolve only to
    # check (the schema validation) pass report=False, so the provenance is printed once
    # per generation rather than once per caller.
    if not report:
        return resolved
    for net_name in sorted(resolved):
        if floors[net_name] is not None:
            origin = "declared"
        elif imposed.get(net_name):
            origin = "imposed by " + ", ".join(f"'{n}'" for n, w in imposed[net_name]
                                               if w == resolved[net_name])
        else:
            origin = "FlooNoC default"
        print(f"  -> {net_name.capitalize()} network ID width: {resolved[net_name]} ({origin})")

    return resolved
