# Copyright 2026 Fondazione Chips-IT.
# Solderpad Hardware License, Version 0.51, see LICENSE for details.
# SPDX-License-Identifier: SHL-0.51

import sys
import re
from pathlib import Path
from core.utils import strip_comments


def generate_stubs(outdir_path: Path, soc_config, env_dependencies, base_dir: Path):
    """
    Generates 'faithful' black-box stubs for external IPs for fast compilation.
    It extracts the exact module signature (parameters and ports) to validate
    the connectivity without compiling the full implementation.
    
    This approach drastically reduces structural verification time (from minutes
    to seconds) because it avoids analyzing/elaborating complex internal logic,
    allowing developers to quickly check if the Top-Level wiring generated by
    Ollivander is syntactically and dimensionally correct.
    """
    project_name = soc_config.project.name
    hw_dir = outdir_path / "hw"
    stubs_dir = outdir_path / ".stubs"
    stubs_dir.mkdir(exist_ok=True)

    # 1. Discover target boundary modules from our generated files
    # We consider all files generated by Ollivander and the basic infrastructure
    # to figure out which modules are missing (i.e. instantiated but not defined).
    our_files = list(hw_dir.rglob("*.sv"))
    
    infra_dir = base_dir / "components" / "infrastructure"
    if infra_dir.exists():
        our_files.extend(list(infra_dir.glob("*.sv")))
        
    defined_modules = set()
    inst_modules = set()

    # Scan generated code to build a list of all instantiated modules
    for f in our_files:
        if 'stubs.sv' in f.name: continue
        try:
            content = f.read_text(encoding='utf-8', errors='ignore')
            # Strip strings and comments to avoid false positive matches
            clean = strip_comments(content)

            
            # Track declared modules
            for m in re.finditer(r'\bmodule\s+([a-zA-Z_][a-zA-Z0-9_]*)\b', clean):
                defined_modules.add(m.group(1))
            
            # Track instantiated modules (heuristic regex for SV instantiation)
            for m in re.finditer(r'^\s*([a-zA-Z_][a-zA-Z0-9_]*)\s*(?:#\s*\([^;]*?\)\s*)?[a-zA-Z_][a-zA-Z0-9_]*\s*(?:\[[^;]*?\]\s*)?\(', clean, flags=re.MULTILINE):
                inst_modules.add(m.group(1))
        except Exception:
            pass

    # Filter out SystemVerilog keywords that might have triggered the instantiation regex
    keywords = {'if', 'case', 'for', 'while', 'always', 'always_comb', 'always_ff', 'always_latch', 'assign', 'logic', 'wire', 'reg', 'bit', 'int', 'struct', 'typedef', 'enum', 'return', 'else', 'begin', 'end'}
    # The missing modules are those instantiated but not defined in our outputs
    targets = (inst_modules - defined_modules) - keywords

    # Handle excludes and predefined stubs from the environment config
    # Some IPs (like complex memory macros or analog blocks) might need custom
    # predefined stubs or should be completely excluded from fast-check.
    excludes = set()
    fast_check_stubs = []
    for dep_info in env_dependencies.values():
        if "fast_check_exclude" in dep_info:
            excludes.update(dep_info["fast_check_exclude"])
        if "fast_check_stubs" in dep_info:
            fast_check_stubs.extend(dep_info["fast_check_stubs"])
            
    targets -= excludes

    # 2. Extract paths from the Bender-generated compile script
    # We use the standard QuestaSim compile script generated by Bender to locate
    # the actual source files of the external dependencies in the workspace.
    tcl_path = outdir_path / "compile_vsim.tcl"
    if not tcl_path.exists():
        print(f"[ERROR] {tcl_path} not found. Ensure 'make prep-sim' ran successfully.")
        sys.exit(1)

    # Read and clean the TCL script, merging lines broken by the continuation character '\'
    tcl_code = tcl_path.read_text(encoding='utf-8')
    tcl_code_clean = re.sub(r'\\\s*\n', ' ', tcl_code)
    
    sv_files = []
    global_options = []
    seen_defines = set()
    for line in tcl_code_clean.split('\n'):
        if 'vlog ' in line: # Process only QuestaSim compilation commands
            for p in line.split():
                p_raw = p.strip('\"\'')
                
                # Extract and store include directories to pass them to the fast-compile
                if p_raw.startswith('+incdir+'):
                    if p not in global_options:
                        global_options.append(p)
                # Extract and store macro definitions, ensuring no duplicates by name
                elif p_raw.startswith('+define+'):
                    def_name = p_raw.split('+')[2].split('=')[0]
                    if def_name not in seen_defines:
                        seen_defines.add(def_name)
                        global_options.append(p)
                        
                # Resolve paths containing the $ROOT environment variable (used by Bender)
                p_clean = p_raw.replace('$ROOT', '.')
                p_path = Path(p_clean).resolve()
                # Collect standalone SystemVerilog/Verilog source files
                if (p_clean.endswith('.sv') or p_clean.endswith('.v')) and p_path.exists():
                    sv_files.append(str(p_path))
                # Parse file lists (.bld, .f, .F) and collect the source files listed inside
                elif p_clean.endswith('.bld') or p_clean.endswith('.f') or p_clean.endswith('.F'):
                    try:
                        bld_path = Path(p_clean.replace('$ROOT', '.'))
                        bld_content = bld_path.read_text(encoding='utf-8')
                        for bp in bld_content.split():
                            bp_clean = bp.strip('\"\'')
                            if (bp_clean.endswith('.sv') or bp_clean.endswith('.v')) and not bp_clean.startswith('+'):
                                if bp_clean.startswith('$ROOT'):
                                    bp_path = Path(bp_clean.replace('$ROOT', '.'))
                                else:
                                    bp_path = Path(bp_clean)
                                    # Fallback: check if the path is relative to the file list's directory
                                    if not bp_path.exists() and (bld_path.parent / bp_path).exists():
                                        bp_path = bld_path.parent / bp_path
                                if bp_path.exists():
                                    sv_files.append(str(bp_path))
                    except Exception:
                        pass

    # 3. Extract exact signatures
    stubs_out = []
    
    def extract_from_path(path):
        """
        Scans a SystemVerilog source file for specific module definitions (targets).
        If found, it extracts the module signature (ports and parameters), relevant
        includes, and imports to generate a faithful black-box stub.
        """
        try:
            content = Path(path).read_text(encoding='utf-8', errors='ignore')
            clean_content = strip_comments(content)

            # Mask semicolons in import statements to prevent premature signature termination
            masked_content = re.sub(r'\bimport\s+[^;]+;', lambda m: m.group(0).replace(';', ' '), clean_content)
        except Exception:
            return

        # For every missing target module, check if it's defined in this file
        for t in list(targets):
            pattern = r'\bmodule\s+' + re.escape(t) + r'\b'
            match = re.search(pattern, clean_content)
            if match:
                start_idx = match.start()
                paren_count = 0
                idx = start_idx
                in_string = False
                # Walk through the character array to find the closing semicolon of the module signature
                while idx < len(masked_content):
                    c = masked_content[idx]
                    if c == '"':
                        in_string = not in_string
                    elif not in_string:
                        # Keep track of parenthesis nesting to not mistake a semicolon inside parameters for the end
                        if c == '(': paren_count += 1
                        elif c == ')': paren_count -= 1
                        # If we find a semicolon at the root parenthesis level, the signature is complete
                        elif c == ';' and paren_count == 0:
                            sig = clean_content[start_idx:idx+1]
                            
                            # Preserve type definitions by importing wildcards from preceding packages
                            head = clean_content[:start_idx]
                            imports = re.findall(r'\bimport\s+[^;]+;', head)
                            # Also grab imports inside the module signature
                            imports.extend(re.findall(r'\bimport\s+[^;]+;', sig))
                            wild_imports = {re.sub(r'::\s*[a-zA-Z_0-9]+', '::*', imp) for imp in imports}
                            
                            # Preserve `include directives required by the signature
                            raw_includes = re.findall(r'`include\s+"[^"]+"', head)
                            raw_includes.extend(re.findall(r'`include\s+"[^"]+"', sig))
                            unique_includes = []
                            for inc in sorted(list(set(raw_includes))):
                                # Exclude assertion headers as they cause macro redefinition conflicts
                                if 'assert' not in inc.lower():
                                    unique_includes.append(inc)
                            
                            # Assemble the final stub: Includes + Imports + Signature + endmodule
                            stub = "\n".join(unique_includes) + "\n" + "\n".join(sorted(list(wild_imports))) + "\n" + sig + "\nendmodule"
                            stubs_out.append(stub)
                            targets.remove(t)
                            break
                    idx += 1

    for path in sv_files:
        if not targets: break
        extract_from_path(path)
        
    if targets:
        # Fallback: if some targets are still missing (e.g. Bender didn't include them 
        # in the main target), aggressively search all .sv files in the workspace.
        print(f"  [INFO] Fallback search in bender_work for missing stubs: {', '.join(targets)}")
        for path in Path('bender_work').rglob("*.sv"):
            if not targets: break
            if str(path) in sv_files: continue
            extract_from_path(path)

    if "tc_pad_bidir" in targets:
        fast_check_stubs.append({
            "name": "padframe_stubs.sv",
            "content": """// Copyright 2026 Fondazione Chips-IT.
// SPDX-License-Identifier: Apache-2.0

package tc_pad_pkg;
  localparam V = 1;
  localparam H = 0;
  typedef struct packed {
    logic dummy;
  } tc_pad_config_t;
  localparam tc_pad_config_t gf22_invecas_tc_pad_config = '{dummy: 1'b0};
endpackage

`ifndef io_pad_internals
`define io_pad_internals dummy_int_io
`endif

module tc_pad_bidir #(
  parameter int tc_pad_orientation = 0,
  parameter tc_pad_config = 0
) (
  inout wire pad_io,
  output logic pad2chip_o,
  input logic input_en_i,
  input logic pu_en_i,
  input logic pd_en_i,
  input logic schmitt_en_i,
  input logic nand_in_i,
  output logic nand_out_o,
  input logic chip2pad_i,
  input logic output_en_i,
  input logic slew_en_i,
  input logic [1:0] drive_strength_i,
  inout wire int_io
);
  wire dummy_int_io;
endmodule
"""
        })
        if "tc_pad_bidir" in targets:
            targets.remove("tc_pad_bidir")

    with open(stubs_dir / f"{project_name}_stubs.sv", "w") as f:
        f.write("// AUTO-GENERATED STUBS FOR FAST-CHECK\n\n")
        f.write("\n\n".join(stubs_out))

    for stub in fast_check_stubs:
        with open(stubs_dir / stub["name"], "w") as f:
            f.write(stub["content"])

    def is_fast_compile_target(p_clean, outdir_path, bld_dir=None):
        """
        Evaluates whether a given source file should be kept intact during a fast compile,
        or if its contents should be replaced by a stub.
        We want to compile ONLY the top-level structure, while dropping the RTL
        implementation of all leaves to maximize speed.
        """
        # Always keep generated files (like packages or top-level) and headers intact
        if outdir_path.name in p_clean or p_clean.endswith('.svh'):
            return True
            
        # Compile infrastructure primitives completely to avoid stubbing issues
        if 'infrastructure' in p_clean:
            return True
            
        # Compile pad reference/behavioral models completely
        if 'components/padframe' in p_clean or 'components/padframes' in p_clean:
            return True
            
        # External testbench files are not required for structural SoC elaboration.
        if 'bender_work' in p_clean and re.search(r'/(?:test|tests|tb)/', p_clean, re.IGNORECASE):
            return False
            
        # Resolve the actual file path
        if p_clean.startswith('$ROOT'):
            p_path = Path(p_clean.replace('$ROOT', '.')).resolve()
        else:
            p_path = Path(p_clean).resolve()
            if not p_path.exists() and bld_dir and (bld_dir / p_path).exists():
                p_path = (bld_dir / p_path).resolve()

        try:
            # Read and sanitize file content
            c = p_path.read_text(encoding='utf-8', errors='ignore')
            c_clean = strip_comments(c)

            c_clean = re.sub(r'"[^"]*"', '', c_clean) # Ignore string literals
            
            # Always keep files defining a package or an interface, even if they also contain a module
            if re.search(r'\b(?:package|interface)\s+[a-zA-Z_0-9]+', c_clean):
                return True
                
            # If the file does not contain any module, macromodule, program, or class, keep it intact
            if not re.search(r'\b(?:module|macromodule|program|class)\b', c_clean):
                return True
        except Exception:
            # If we cannot read or resolve the file (e.g., due to env vars in the path),
            # keep it intact and let QuestaSim handle it.
            return True
            
        # Default behavior: replace with a stub
        return False

    # 4. Create compile_vsim_fast.tcl
    # Prepare the initial TCL commands for creating the work library
    # This new TCL script will be a clone of the Bender one, but it will omit
    # the compilation of all "stubbed" files, compiling our auto-generated 
    # stubs file instead.
    fast_tcl = ['onerror {quit -code 1}', 'if {[file exists work]} { file delete -force work }', 'vlib work']
    tcl_code_clean = tcl_code_clean.replace('return 1', 'quit -code 1')
    
    for line in tcl_code_clean.split('\n'):
        if 'vlog ' in line:
            new_tokens = []
            for p in line.split():
                p_clean = p.strip('\"\'')
                # Process standalone Verilog/SystemVerilog sources
                if (p_clean.endswith('.sv') or p_clean.endswith('.v')) and not p.startswith('+'):
                    if is_fast_compile_target(p_clean, outdir_path):
                        new_tokens.append(p)
                # Process file lists and filter their contents to create '.fast' versions
                elif p_clean.endswith('.bld') or p_clean.endswith('.f') or p_clean.endswith('.F'):
                    try:
                        bld_path = Path(p_clean.replace('$ROOT', '.'))
                        bld_content = bld_path.read_text(encoding='utf-8')
                        bld_tokens = []
                        for bp in bld_content.split():
                            bp_clean = bp.strip('\"\'')
                            if (bp_clean.endswith('.sv') or bp_clean.endswith('.v')) and not bp.startswith('+'):
                                if is_fast_compile_target(bp_clean, outdir_path, bld_path.parent):
                                    bld_tokens.append(bp)
                            else:
                                bld_tokens.append(bp)
                                
                        if bld_tokens:
                            fast_bld_name = bld_path.stem + "_fast" + bld_path.suffix
                            fast_bld_path = bld_path.with_name(fast_bld_name)
                            fast_bld_path.write_text("\n".join(bld_tokens), encoding='utf-8')
                            new_tokens.append(p.replace(bld_path.name, fast_bld_name))
                    except Exception:
                        new_tokens.append(p)
                else:
                    new_tokens.append(p)
            
            # Check if there are still any sources left to compile in this line
            has_sources = False
            for t in new_tokens:
                tc = t.strip('\"\'')
                if (tc.endswith('.sv') or tc.endswith('.v') or tc.endswith('.bld') or tc.endswith('.f') or tc.endswith('.F')) and not tc.startswith('+'):
                    has_sources = True
                    
            if has_sources:
                # Ensure the floo_noc package is compiled BEFORE the soc package if both are present
                noc_idx, soc_idx = -1, -1
                for i, t in enumerate(new_tokens):
                    if '_noc_pkg.sv' in t: noc_idx = i
                    elif '_soc_pkg.sv' in t: soc_idx = i
                if noc_idx != -1 and soc_idx != -1 and soc_idx < noc_idx:
                    new_tokens[soc_idx], new_tokens[noc_idx] = new_tokens[noc_idx], new_tokens[soc_idx]
                    
                # Add the -suppress flag to suppress unnecessary warnings during the fast compile
                fast_line = ' '.join(new_tokens).replace('vlog ', 'vlog -suppress 13314 ')
                fast_tcl.append(fast_line)
        else:
            fast_tcl.append(line)

    # Finally, append the compilation command for the generated stubs
    opts_str = " ".join(global_options)
    fast_tcl.append(f'vlog -suppress 13314 {opts_str} -sv {outdir_path}/.stubs/{project_name}_stubs.sv')
    for stub in fast_check_stubs:
        fast_tcl.append(f'vlog -suppress 13314 {opts_str} -sv {outdir_path}/.stubs/{stub["name"]}')

    with open(outdir_path / "compile_vsim_fast.tcl", "w") as f:
        f.write('\n'.join(fast_tcl))