# Copiright Fondazione Chips-IT
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0
#

OLLIVANDER_ROOT := ../..
SOC_YAML        := $(OLLIVANDER_ROOT)/soc_cfg_examples/noc_subtile/mesh_subtile.yml
ENV_YAML        := $(OLLIVANDER_ROOT)/soc_cfg_examples/noc_subtile/mesh_subtile_env.yml
OUT_DIR         := generated

include $(OLLIVANDER_ROOT)/ollivander.mk