<%namespace name="lh" file="../license_header.mako"/>\
${lh.license()}
// AUTOMATICALLY GENERATED BY OLLIVANDER
//
// Top-Level Physical Chip Wrapper for ${project_name}
// Instantiates the SoC Core and the Padframe Ring.
//

module ${project_name}_chip (
<%
    all_pads = []
    for dom in pad_domains:
        for pad in dom['pad_list']:
            all_pads.append(pad['name'])
%>
% for pad_name in all_pads:
    inout wire logic ${pad_name}${"" if loop.last else ","}
% endfor
);

    import ${project_name}_soc_pkg::*;
    import pkg_${project_name}_padframe::*;

<%
    has_dynamic_pads = any(not pad.get('is_static', False) for dom in pad_domains for pad in dom['pad_list'])
    has_static_pads = any(pad.get('is_static', False) for dom in pad_domains for pad in dom['pad_list'])
%>
% if has_static_pads:
    static_connection_signals_pad2soc_t static_pad2soc;
    static_connection_signals_soc2pad_t static_soc2pad;
% endif
% if has_dynamic_pads:
    port_signals_pad2soc_t              port_pad2soc;
    port_signals_soc2pad_t              port_soc2pad;
% endif

<%
    ext_reg_slaves = []
    for c in config.components:
        if c.interfaces and 'regbus_slave' in c.interfaces:
            for intf in c.interfaces['regbus_slave']:
                if intf.get('external', False):
                    ext_reg_slaves.append(c)
%>
% if ext_reg_slaves:
    // ---------------------------------------------------------------------
    // External RegBus Interfaces (PLL, Padframe, etc.)
    // ---------------------------------------------------------------------
    logic         [${len(ext_reg_slaves)-1}:0] ext_reg_async_slv_req_o;
    logic         [${len(ext_reg_slaves)-1}:0] ext_reg_async_slv_ack_i;
    soc_reg_req_t [${len(ext_reg_slaves)-1}:0] ext_reg_async_slv_data_o;
    logic         [${len(ext_reg_slaves)-1}:0] ext_reg_async_slv_req_i;
    logic         [${len(ext_reg_slaves)-1}:0] ext_reg_async_slv_ack_o;
    soc_reg_rsp_t [${len(ext_reg_slaves)-1}:0] ext_reg_async_slv_data_i;
% endif

    // ---------------------------------------------------------------------
    // Core <-> Padframe Wiring
    // ---------------------------------------------------------------------
% for conn in validated_connections:
    ${conn['sv_type']} ${conn['sig_name']};
    % if conn.get('is_inout', False):
    // inout connections are directly routed to the padframe ports below
    % elif 'assignments' in conn:
    % for assign in conn['assignments']:
    assign ${assign['lhs']} = ${assign['rhs']};
    % endfor
    % elif conn['is_input_to_soc']:
    assign ${conn['sig_name']} = ${conn['struct_path']};
    % else:
    assign ${conn['struct_path']} = ${conn['sig_name']};
    % endif
% endfor

<%
    sys_rst_n = "pwr_on_rst_ni" if getattr(config.clock_tree, 'generators', 0) > 0 else "rst_ni"
    sys_clk = "ref_clk_i" if getattr(config.clock_tree, 'generators', 0) > 0 else "clk_i"
%>
% if getattr(config.clock_tree, 'generators', 0) > 0:
<%
    ref_clk_dom = core_sig_to_domain.get("ref_clk_i", "domain_0")
%>
    // The reference clock comes statically from the PAD_CLK pad
    var type(static_pad2soc.${ref_clk_dom}.ref_clk_i) ref_clk_i;
    assign ref_clk_i = static_pad2soc.${ref_clk_dom}.ref_clk_i;
% endif

<%
    pf_idx = next((i for i, c in enumerate(ext_reg_slaves) if c.name == "padframe_config"), -1)
%>
% if pf_idx != -1:
    // ---------------------------------------------------------------------
    // Padframe Configuration CDC (Async -> Sync)
    // ---------------------------------------------------------------------
    ${project_name}_soc_pkg::soc_reg_req_t pf_reg_req;
    ${project_name}_soc_pkg::soc_reg_rsp_t pf_reg_rsp;

    reg_cdc_dst #(
        .CDC_KIND ("cdc_4phase"),
        .req_t    (${project_name}_soc_pkg::soc_reg_req_t),
        .rsp_t    (${project_name}_soc_pkg::soc_reg_rsp_t)
    ) i_padframe_reg_cdc (
        .dst_clk_i    (${sys_clk}),
        .dst_rst_ni   (${sys_rst_n}),
        .async_req_i  (ext_reg_async_slv_req_o[${pf_idx}]),
        .async_ack_o  (ext_reg_async_slv_ack_i[${pf_idx}]),
        .async_data_i (ext_reg_async_slv_data_o[${pf_idx}]),
        .async_req_o  (ext_reg_async_slv_req_i[${pf_idx}]),
        .async_ack_i  (ext_reg_async_slv_ack_o[${pf_idx}]),
        .async_data_o (ext_reg_async_slv_data_i[${pf_idx}]),
        .dst_req_o    (pf_reg_req),
        .dst_rsp_i    (pf_reg_rsp)
    );
% endif

    // ---------------------------------------------------------------------
    // Padframe Instantiation
    // ---------------------------------------------------------------------
    ${project_name}_padframe i_padframe (
        .clk_i (${sys_clk}),
        .rst_ni(${sys_rst_n}),
% if has_static_pads:
        .static_connection_signals_pad2soc(static_pad2soc),
        .static_connection_signals_soc2pad(static_soc2pad),
% endif
% if has_dynamic_pads:
        .port_signals_pad2soc(port_pad2soc),
        .port_signals_soc2pad(port_soc2pad),
% endif
% for dom in pad_domains:
 % for pad in dom['pad_list']:
        .pad_${dom['name']}_${pad['name']}_pad(${pad['name']}),
 % endfor
% endfor
% for conn in validated_connections:
 % if conn.get('is_inout', False):
        .${conn['sig_name']}(${conn['sig_name']}),
 % endif
% endfor
% if pf_idx != -1:
        .config_req_i(pf_reg_req),
        .config_rsp_o(pf_reg_rsp)
% else:
        .config_req_i('0),
        .config_rsp_o()
% endif
    );

    // ---------------------------------------------------------------------
    // Clock Generation (FLL/PLL)
    // ---------------------------------------------------------------------
% if getattr(config.clock_tree, 'generators', 0) > 0:
    logic [${config.clock_tree.generators - 1}:0] domain_clk_i;
    logic [${config.clock_tree.generators - 1}:0] clk_gen_lock_i;

<%
    pll_idx = next((i for i, c in enumerate(ext_reg_slaves) if c.name == "pll_config"), -1)
%>
    // Instantiate the physical Clock Generation cluster.
    olli_clk_gen #(
        .NUM_CLOCKS(${config.clock_tree.generators}),
        .reg_req_t (${project_name}_soc_pkg::soc_reg_req_t),
        .reg_rsp_t (${project_name}_soc_pkg::soc_reg_rsp_t)
    ) i_clk_gen (
        .ref_clk_i   (ref_clk_i),
        .clk_o       (domain_clk_i),
        .lock_o      (clk_gen_lock_i),
% if pll_idx != -1:
        // Configuration interface (RegBus Async)
        .cfg_req_i   (ext_reg_async_slv_req_o[${pll_idx}]),
        .cfg_ack_o   (ext_reg_async_slv_ack_i[${pll_idx}]),
        .cfg_data_i  (ext_reg_async_slv_data_o[${pll_idx}]),
        .cfg_req_o   (ext_reg_async_slv_req_i[${pll_idx}]),
        .cfg_ack_i   (ext_reg_async_slv_ack_o[${pll_idx}]),
        .cfg_data_o  (ext_reg_async_slv_data_i[${pll_idx}])
% else:
        .cfg_req_i   (1'b0),
        .cfg_ack_o   (),
        .cfg_data_i  ('0),
        .cfg_req_o   (),
        .cfg_ack_i   (1'b0),
        .cfg_data_o  ()
% endif
    );
% endif

    // ---------------------------------------------------------------------
    // SoC Core Instantiation
    // ---------------------------------------------------------------------
    ${project_name} i_core (
<%
    core_conns = []
    if ext_reg_slaves:
        core_conns.append(".ext_reg_async_slv_req_o(ext_reg_async_slv_req_o)")
        core_conns.append(".ext_reg_async_slv_ack_i(ext_reg_async_slv_ack_i)")
        core_conns.append(".ext_reg_async_slv_data_o(ext_reg_async_slv_data_o)")
        core_conns.append(".ext_reg_async_slv_req_i(ext_reg_async_slv_req_i)")
        core_conns.append(".ext_reg_async_slv_ack_o(ext_reg_async_slv_ack_o)")
        core_conns.append(".ext_reg_async_slv_data_i(ext_reg_async_slv_data_i)")
        
    for conn in validated_connections:
        core_conns.append(f".{conn['sig_name']}({conn['sig_name']})")
    if getattr(config.clock_tree, 'generators', 0) > 0:
        core_conns.append(".domain_clk_i(domain_clk_i)")
        core_conns.append(".clk_gen_lock_i(clk_gen_lock_i)")
%>
% for conn in core_conns:
        ${conn}${"" if loop.last else ","}
% endfor
    );

endmodule