<%
  # ============================================================================
  # MAKO TEMPLATE FOR THE SOC GLOBAL PACKAGE
  # ============================================================================
  # This template generates the main SystemVerilog package for the SoC.
  # It acts as the Single Source of Truth (SSoT) for address maps and routing.
  p_name = config.project.name
  pkg = "ollivander_soc_pkg"
  
  aw = config.topology.global_bus.addr_width
  # Formatting helpers
  def fmt_name(name): return name.replace('_clk', '').replace('_rst', '').lower()
  def camel_case(name): return ''.join(word.title() for word in name.split('_'))
  def parse_hex(val):
      if isinstance(val, int): return f"{val:X}"
      return str(val).replace('0x', '').replace('_', '').upper()

  # ============================================================================
  # 1. CLOCK DOMAINS EXTRACTION
  # ============================================================================
  # We only need indices for gateable (non-real-time) domains to generate the
  # reset arrays. The host clock is excluded as it is the root domain.
  gateable_domains = [d for d in config.clock_tree.domains if not d.is_real_time and d.name != 'host_clk']
  
  # ============================================================================
  # 2. AXI SLAVES (CROSSBAR TARGETS) EXTRACTION
  # ============================================================================
  # Scans all components for AXI slave interfaces. It unrolls multiple ports of 
  # the same component (e.g., a dual-port L2 Memory) into discrete routing targets 
  # for the central crossbar, categorizing them by synchronous/asynchronous domains.
  axi_slaves_async = []
  axi_slaves_sync = []
  for c in config.components:
      if c.interfaces and 'axi_slave' in c.interfaces:
          for slv in c.interfaces['axi_slave']:
              is_sync = slv.get('sync_domain', False)
              ports = slv.get('ports', 1)
              for p in range(ports):
                  name_suffix = f"_{p}" if ports > 1 else ""
                  obj = {
                      'name': f"{c.name}{name_suffix}",
                      'base': slv['base_addr'],
                      'size': slv.get('size', slv.get('size_per_instance', '0x1000'))
                  }
                  if is_sync: axi_slaves_sync.append(obj)
                  else: axi_slaves_async.append(obj)
                  
  if config.project.build_mode == "macro" and config.project.macro_settings and config.project.macro_settings.masters:
      for idx, mst in enumerate(config.project.macro_settings.masters):
          axi_slaves_sync.append({
              'name': f'macro_export_{idx}',
              'base': '0',
              'size': '0'
          })

  axi_slaves = axi_slaves_async + axi_slaves_sync
                  
  # ============================================================================
  # 3. AXI MASTERS (CROSSBAR INITIATORS) EXTRACTION
  # ============================================================================
  axi_masters = []
  for c in config.components:
      if c.interfaces and c.interfaces.get('axi_master'):
          axi_masters.append(c.name)
          
  # ============================================================================
  # 4. REGBUS SLAVES (PERIPHERAL TARGETS) EXTRACTION
  # ============================================================================
  # Scans for low-speed peripheral slaves on the RegBus. It separates synchronous
  # from asynchronous targets to route them to the correct conversion pipelines 
  # in the top-level.
  reg_sync = []
  reg_async = []
  # The central System Controller is always a synchronous RegBus slave
  reg_sync.append({
      'name': config.system_controller.name,
      'base': config.system_controller.base_addr,
      'size': config.system_controller.size if config.system_controller.size else '0x1000'
  })
  for c in config.components:
      if c.interfaces and 'regbus_slave' in c.interfaces:
          for slv in c.interfaces['regbus_slave']:
              is_sync = slv.get('sync_domain', False)
              obj = {
                  'name': c.name,
                  'base': slv['base_addr'],
                  'size': slv.get('size', '0x1000')
              }
              if is_sync: reg_sync.append(obj)
              else: reg_async.append(obj)
              
  all_reg_slaves = reg_sync + reg_async
%>// Copyright 2026 Fondazione Chips-IT.
// Solderpad Hardware License, Version 0.51, see LICENSE for details.
// SPDX-License-Identifier: SHL-0.51
//
// AUTOMATICALLY GENERATED BY OLLIVANDER - DO NOT EDIT DIRECTLY
//
// SoC Global SystemVerilog Package for ${p_name.upper()}
// Contains Memory Maps, Routing Indices, and architectural constants.

// BENDER: name="axi"
// BENDER: name="register_interface"

`include "axi/typedef.svh"
`include "register_interface/typedef.svh"

package ${pkg};

  // =========================================================================
  // 1. GLOBAL ARCHITECTURE PARAMETERS
  // =========================================================================
  // Extracted from the YAML `global_bus` section. Used to dimension the 
  // central AXI crossbars and generate the standard struct macros.
  localparam int unsigned AxiAddrWidth     = ${config.topology.global_bus.addr_width};
  localparam int unsigned AxiDataWidth     = ${config.topology.global_bus.data_width};
  localparam int unsigned AxiUserWidth     = ${config.topology.global_bus.user_width};
  localparam int unsigned AxiIdWidth       = ${config.topology.global_bus.mst_id_width};
  
  localparam int unsigned ExtSlvIdWidth    = AxiIdWidth + $clog2(${len(axi_masters)} > 1 ? ${len(axi_masters)} : 2);
  localparam int unsigned LlcIdWidth       = ExtSlvIdWidth + 1; // Margin for LLC bypass bit

  // L2 Memory Base Addresses (Extracted from components)
<%
  l2_slv = next((s for s in axi_slaves if 'l2' in s['name']), None)
  l2_base = l2_slv['base'] if l2_slv else 0
  l2_size = l2_slv['size'] if l2_slv else 0
%>\
  localparam logic [63:0] L2Port0InterlBase    = 64'h${parse_hex(l2_base)};
  localparam logic [63:0] L2Port0NonInterlBase = 64'h${parse_hex(l2_base)} + 64'h${parse_hex(l2_size)}/2;
  localparam logic [63:0] L2Port1InterlBase    = 64'h${parse_hex(l2_base)};
  localparam logic [63:0] L2Port1NonInterlBase = 64'h${parse_hex(l2_base)} + 64'h${parse_hex(l2_size)}/2;
  
  localparam int unsigned AxiUserAmoMsb    = ${config.system_settings.user_mapping.amo_msb};
  localparam int unsigned AxiUserAmoLsb    = ${config.system_settings.user_mapping.amo_lsb};
  localparam int unsigned AxiUserEccErrBit = ${config.system_settings.user_mapping.ecc_err_bit};

  // =========================================================================
  // 1a. GLOBAL BUS TYPES
  // =========================================================================
  // Defines the SystemVerilog structs and channels for the AXI and RegBus
  // interconnects. These types are used globally across all component wrappers.
  localparam int unsigned LogDepth   = 3;
  localparam int unsigned LlcAwWidth = (2**LogDepth)*axi_pkg::aw_width(AxiAddrWidth, LlcIdWidth, AxiUserWidth);
  localparam int unsigned LlcWWidth  = (2**LogDepth)*axi_pkg::w_width(AxiDataWidth, AxiUserWidth);
  localparam int unsigned LlcBWidth  = (2**LogDepth)*axi_pkg::b_width(LlcIdWidth, AxiUserWidth);
  localparam int unsigned LlcArWidth = (2**LogDepth)*axi_pkg::ar_width(AxiAddrWidth, LlcIdWidth, AxiUserWidth);
  localparam int unsigned LlcRWidth  = (2**LogDepth)*axi_pkg::r_width(AxiDataWidth, LlcIdWidth, AxiUserWidth);

  typedef logic [AxiAddrWidth-1:0] soc_reg_addr_t;
  typedef logic [31:0] soc_reg_data_t;
  typedef logic [ 3:0] soc_reg_strb_t;
  `REG_BUS_TYPEDEF_ALL(soc_reg, soc_reg_addr_t, soc_reg_data_t, soc_reg_strb_t)

  typedef logic [AxiAddrWidth-1:0]   soc_axi_addr_t;
  typedef logic [AxiDataWidth-1:0]   soc_axi_data_t;
  typedef logic [AxiDataWidth/8-1:0] soc_axi_strb_t;
  typedef logic [AxiUserWidth-1:0]   soc_axi_user_t;
  typedef logic [AxiIdWidth-1:0]     soc_axi_mst_id_t;
  typedef logic [ExtSlvIdWidth-1:0]  soc_axi_slv_id_t;
  typedef logic [LlcIdWidth-1:0]     soc_axi_llc_id_t;

  `AXI_TYPEDEF_ALL(soc_axi, soc_axi_addr_t, soc_axi_mst_id_t, soc_axi_data_t, soc_axi_strb_t, soc_axi_user_t)
  `AXI_TYPEDEF_ALL(soc_axi_slv, soc_axi_addr_t, soc_axi_slv_id_t, soc_axi_data_t, soc_axi_strb_t, soc_axi_user_t)
  `AXI_TYPEDEF_ALL(soc_axi_llc, soc_axi_addr_t, soc_axi_llc_id_t, soc_axi_data_t, soc_axi_strb_t, soc_axi_user_t)

  // =========================================================================
  // 1b. SYSTEM MICROARCHITECTURE PARAMETERS
  // =========================================================================
  // Deep microarchitectural sizing for transaction tracking FIFOs and RISC-V 
  // Atomic Memory Operations (AMOs) adapters within the crossbar.
  localparam int unsigned LlcMaxReadTxns  = ${config.system_settings.llc.max_read_txns};
  localparam int unsigned LlcMaxWriteTxns = ${config.system_settings.llc.max_write_txns};
  localparam int unsigned LlcAmoNumCuts   = ${config.system_settings.llc.amo_num_cuts};
  localparam bit          LlcAmoPostCut   = ${'1' if config.system_settings.llc.amo_post_cut else '0'};

  localparam int unsigned RegMaxReadTxns  = ${config.system_settings.reg_bus.max_read_txns};
  localparam int unsigned RegMaxWriteTxns = ${config.system_settings.reg_bus.max_write_txns};
  localparam int unsigned RegAmoNumCuts   = ${config.system_settings.reg_bus.amo_num_cuts};
  localparam bit          RegAmoPostCut   = ${'1' if config.system_settings.reg_bus.amo_post_cut else '0'};

  // =========================================================================
  // 2. CLOCK & RESET DOMAINS
  // =========================================================================
  // Enums used as array indices to map components to their respective reset wires.
  localparam int unsigned NumClkGen  = ${config.clock_tree.generators};
  localparam int unsigned NumDomains = ${len(gateable_domains)};
  
  typedef enum int {
% for dom in gateable_domains:
    DomainIdx_${fmt_name(dom.name)} = ${loop.index}${"," if not loop.last else ""}
% endfor
  } domain_idx_e;

  // =========================================================================
  // 3. AXI CROSSBAR (SYSTEM MEMORY MAP)
  // =========================================================================
  // Master and Slave enumeration indices. These are crucial to correctly wire 
  // components to specific ports of the central multidimensional AXI crossbar.
  localparam int unsigned NumAxiMasters = ${len(axi_masters)};
  localparam int unsigned NumAxiMastersSync = ${config.host.parameters.get('AxiNumMstSync', 0)};
  typedef enum int {
% for mst in axi_masters:
    AxiMstIdx_${camel_case(mst)} = ${loop.index}${"," if not loop.last else ""}
% endfor
  } axi_mst_idx_e;

  localparam int unsigned NumAxiSlavesAsync = ${len(axi_slaves_async)};
  localparam int unsigned NumAxiSlavesSync  = ${config.host.parameters.get('AxiNumSlvSync', len(axi_slaves_sync))};
  localparam int unsigned NumAxiSlaves      = NumAxiSlavesAsync + NumAxiSlavesSync;
  typedef enum int {
% for slv in axi_slaves:
    AxiSlvIdx_${camel_case(slv['name'])} = ${loop.index}${"," if not loop.last else ""}
% endfor
  } axi_slv_idx_e;

  // AXI Memory Map Arrays (Reversed for correct SystemVerilog packed array syntax)
  // These arrays are read by the Host's internal crossbar to decode incoming 
  // addresses and route transactions to the correct AXI slave port.
  localparam int unsigned AxiExtNumRules = NumAxiSlaves;

  localparam logic [NumAxiSlaves-1:0][7:0] AxiExtRegionIdx = {
% for i in reversed(range(len(axi_slaves))):
    8'd${i}${"," if i != 0 else ""}
% endfor
  };

  localparam logic [NumAxiSlaves-1:0][63:0] AxiExtRegionStart = {
% for slv in axi_slaves[::-1]:
    64'h${parse_hex(slv['base'])}${"," if not loop.last else ""}
% endfor
  };

  localparam logic [NumAxiSlaves-1:0][63:0] AxiExtRegionEnd = {
% for slv in axi_slaves[::-1]:
    64'h${parse_hex(slv['base'])} + 64'h${parse_hex(slv['size'])}${"," if not loop.last else ""}
% endfor
  };

  // =========================================================================
  // 4. REGBUS SUBSYSTEM (SYSTEM REGISTERS MAP)
  // =========================================================================
  // Routing map for the secondary low-speed Register Bus.
  localparam int unsigned NumSyncRegSlaves  = ${len(reg_sync)};
  localparam int unsigned NumAsyncRegSlaves = ${len(reg_async)};
  localparam int unsigned NumTotalRegSlaves = NumSyncRegSlaves + NumAsyncRegSlaves;

  typedef enum int {
% for slv in all_reg_slaves:
    RegBusSlvIdx_${camel_case(slv['name'])} = ${loop.index}${"," if not loop.last else ""}
% endfor
  } regbus_slv_idx_e;

  localparam int unsigned RegExtNumRules = NumTotalRegSlaves;

  localparam logic [NumTotalRegSlaves-1:0][7:0] RegExtRegionIdx = {
% for i in reversed(range(len(all_reg_slaves))):
    8'd${i}${"," if i != 0 else ""}
% endfor
  };

  localparam logic [NumTotalRegSlaves-1:0][63:0] RegExtRegionStart = {
% for slv in all_reg_slaves[::-1]:
    64'h${parse_hex(slv['base'])}${"," if not loop.last else ""}
% endfor
  };

  localparam logic [NumTotalRegSlaves-1:0][63:0] RegExtRegionEnd = {
% for slv in all_reg_slaves[::-1]:
    64'h${parse_hex(slv['base'])} + 64'h${parse_hex(slv['size'])}${"," if not loop.last else ""}
% endfor
  };

  // =========================================================================
  // 5. DEBUG AND STATUS SIGNALS
  // =========================================================================
  typedef struct packed {
    logic                  rt_clk;
    logic                  host_clk;
    logic [NumDomains-1:0] domain_clk;
    logic [NumDomains-1:0] domain_rsts_n;
    logic                  host_pwr_on_rst_n;
  } ${p_name}_debug_sigs_t;

endpackage : ${pkg}