<%
  p_name = config.project.name
  pkg = "ollivander_soc_pkg"

  def fmt_name(name): return name.replace('_clk', '').replace('_rst', '').lower()

  # ============================================================================
  # 1. NOC MESH GRID CALCULATION
  # ============================================================================
  # Parses the 'placement' constraints from the YAML configuration to determine
  # the physical dimensions of the 2D mesh. It calculates the maximum X and Y
  # coordinates and tracks which tiles are active vs empty.
  tiles = [] # list of (x, y, component)
  
  def add_placement(c, placement):
      if not placement: return
      logical = placement.get('logical')
      if not logical: return
      
      if isinstance(logical, list):
          for l in logical: process_logical(c, l)
      else:
          process_logical(c, logical)
          
  def process_logical(c, l):
      if 'x' in l and 'y' in l:
          x, y = l['x'], l['y']
          tiles.append((x, y, c))
      elif 'box' in l:
          box = l['box']
          x_start, x_end = box['x_start'], box['x_end']
          y_start, y_end = box['y_start'], box['y_end']
          for x in range(x_start, x_end + 1):
              for y in range(y_start, y_end + 1):
                  tiles.append((x, y, c))

  add_placement(config.host, config.host.placement)
  if config.components:
      for c in config.components: add_placement(c, c.placement)
          
  max_x = max([t[0] for t in tiles]) if tiles else 0
  max_y = max([t[1] for t in tiles]) if tiles else 0

  mesh_dim_x = max_x + 1
  mesh_dim_y = max_y + 1
  
  # Create a 2D bitmap of the mesh to distinguish active tiles from empty ones (Dummy routers).
  mesh_map = [[0 for _ in range(mesh_dim_x)] for _ in range(mesh_dim_y)]
  for x, y, _ in tiles: mesh_map[y][x] = 1

  num_tiles = sum(sum(row) for row in mesh_map)
  
  axi_masters = [c.name for c in config.components if c.interfaces and c.interfaces.get('axi_master')]
  
  def parse_hex(val):
      if isinstance(val, int): return f"{val:X}"
      return str(val).replace('0x', '').replace('_', '').upper()
      
  ## Instance counting and window resolution both live in core.utils, which is what keeps this
  ## package, the address map, the firmware and FlooGen describing the same hardware. The local
  ## copy of the counting arithmetic that used to sit here was one of four.
  from core.utils import component_span, instance_count

  axi_slaves = []
  for c in config.components:
      if c.interfaces and 'axi_slave' in c.interfaces:
          for slv in c.interfaces['axi_slave']:
              # These rules become Cheshire's external-region table: they decide which
              # addresses LEAVE the host at all (anything outside dies in the internal
              # DECERR slave). 'size_per_instance' covers ONE instance, so the region
              # must span the whole array - with one instance's size, every access
              # beyond instance 0 was silently swallowed inside the host, B response
              # and all (symptom: 15 of 16 mesh clusters unreachable). An explicit
              # 'size' keeps its documented meaning of the WHOLE region and wins;
              # otherwise the span is computed from the resolved per-instance windows,
              # which is not 'per x count' once either field carries a list.
              if 'size' in slv:
                  base, size = slv['base_addr'], slv['size']
              else:
                  span_base, span_size = component_span(slv, instance_count(c))
                  base, size = hex(span_base), hex(span_size)
              axi_slaves.append({'name': c.name, 'base': base, 'size': size})
%><%namespace file="/license_header.mako" import="license"/>\
${license()}\
//
// AUTOMATICALLY GENERATED BY OLLIVANDER - DO NOT EDIT DIRECTLY
//
// NoC SoC Global Package for ${p_name.upper()}
// Contains Mesh routing information and NoC global definitions.
//
// BENDER: name="floo_noc"
// BENDER: name="axi"
// BENDER: name="register_interface"

`include "axi/typedef.svh"
`include "register_interface/typedef.svh"

package ${pkg};

  import floo_pkg::*;
  import floo_ollivander_noc_pkg::*;

  // =========================================================================
  // 0. GLOBAL ARCHITECTURE PARAMETERS & TYPES
  // =========================================================================
  // Defines the standard widths for addresses, data, and sideband signals
  // used by the AXI and RegBus interfaces across the entire SoC.
<%
  if config.topology.global_bus:
      g_addr_w = config.topology.global_bus.addr_width
      g_data_w = config.topology.global_bus.data_width
      g_user_w = config.topology.global_bus.user_width
      g_id_w   = config.topology.global_bus.mst_id_width
  else:
      narrow_net = config.topology.noc_settings.networks.get('narrow')
      g_addr_w = narrow_net.addr_width
      g_data_w = narrow_net.data_width
      ## A crossbar SoC takes the user width from the global bus the user declares; a NoC SoC has
      ## no such field, so it is derived from the same user_mapping the networks are derived from -
      ## the span up to the highest bit that means something, the AMO reservation id and the ECC
      ## error flag. It used to be a hardcoded 10, which had no relation to that mapping and made
      ## every macro export ports five bits wider than the network they were connected to.
      g_user_w = noc_user_widths['narrow']
      ## The narrow network's input ID width, resolved once in Python from what the nested
      ## macros impose (src/core/macro_boundary.py) and passed in, so that this package and
      ## the FlooGen configuration cannot disagree. It used to be a hardcoded 4, unrelated
      ## to anything the SoC declared.
      g_id_w   = noc_id_widths['narrow']

  ## Both networks are guaranteed by the schema (Topology.check_topology_config).
  wide_net = config.topology.noc_settings.networks['wide']
%>
<%
  # Calculate host's internal AXI masters (from Cheshire's gen_axi_in) to adjust ExtSlvIdWidth and LlcIdWidth
  host_params = config.host.parameters or {} if config.host else {}
  num_cores = host_params.get('NumCores', 1)
  has_dbg = 1 # Always present
  has_dma = 1 if host_params.get('Dma', True) else 0
  has_slink = 1 if host_params.get('SerialLink', True) else 0
  has_vga = 1 if host_params.get('Vga', True) else 0
  has_usb = 1 if host_params.get('Usb', True) else 0
  num_internal_masters = num_cores + has_dbg + has_dma + has_slink + has_vga + has_usb + 1
%>
  localparam int unsigned AxiAddrWidth     = ${g_addr_w};
  localparam int unsigned AxiDataWidth     = ${g_data_w};
  localparam int unsigned AxiUserWidth     = ${g_user_w};
  localparam int unsigned AxiIdWidth       = ${g_id_w};
  localparam int unsigned AxiWideDataWidth = ${wide_net.data_width};

  localparam int unsigned ExtSlvIdWidth    = AxiIdWidth + $clog2(${num_internal_masters} > 1 ? ${num_internal_masters} : 2);
  localparam int unsigned LlcIdWidth       = ExtSlvIdWidth + 1; // Margin for LLC bypass bit
% if config.project.build_mode == "macro" and config.project.macro_settings:
<%
  from core.macro_boundary import clog2
  user_span = noc_user_widths['narrow']
  is_joined = config.project.macro_settings.boundary != "dual"
  mst_id_w = g_id_w + clog2(max(num_internal_masters, 2))
%>

  // =========================================================================
  // BOUNDARY GEOMETRY PUBLISHED TO A PARENT SoC
  // =========================================================================
  // Read by a parent that nests this macro (src/core/macro_boundary.py). Which
  // numbers appear is itself the signal, so the reader needs no notion of export
  // type: a single or joined boundary publishes the ID width it *imposes*, a dual
  // boundary the widths it *accepts*.
% if is_joined:
  //
  // A joined boundary folds its networks into a single exported master port whose ID
  // comes from the crossbar behind it. That width is not negotiable: retyping the
  // port narrower would alias its IDs, so a network this macro plugs into must be
  // at least this wide. The user span is the part of the field carrying semantics.
  localparam int unsigned MacroMstIdWidth   = ${mst_id_w};
  localparam int unsigned MacroMstUserWidth = ${g_user_w};
  localparam int unsigned MacroMstUserSpan  = ${user_span};
% else:
  //
  // A dual boundary plugs its slave ports straight into the chimneys of its own network,
  // which accept these widths. A parent network wider than this would be truncated
  // at the boundary, so they are an upper bound rather than something to adapt: the
  // parent refuses instead, and this project has to be regenerated wider. The
  // master side publishes nothing, since it widens to whatever it is handed.
  localparam int unsigned MacroNarrowInIdWidth = ${g_id_w};
  localparam int unsigned MacroWideInIdWidth   = ${noc_id_widths['wide']};
% endif
% endif


  localparam int unsigned AxiUserAmoMsb    = ${config.system_settings.user_mapping.amo_msb};
  localparam int unsigned AxiUserAmoLsb    = ${config.system_settings.user_mapping.amo_lsb};
  localparam int unsigned AxiUserEccErrBit = ${config.system_settings.user_mapping.ecc_err_bit};

  localparam int unsigned LlcMaxReadTxns  = ${config.system_settings.llc.max_read_txns};
  localparam int unsigned LlcMaxWriteTxns = ${config.system_settings.llc.max_write_txns};
  localparam int unsigned LlcAmoNumCuts   = ${config.system_settings.llc.amo_num_cuts};
  localparam bit          LlcAmoPostCut   = ${'1' if config.system_settings.llc.amo_post_cut else '0'};

  localparam int unsigned RegMaxReadTxns  = ${config.system_settings.reg_bus.max_read_txns};
  localparam int unsigned RegMaxWriteTxns = ${config.system_settings.reg_bus.max_write_txns};
  localparam int unsigned RegAmoNumCuts   = ${config.system_settings.reg_bus.amo_num_cuts};
  localparam bit          RegAmoPostCut   = ${'1' if config.system_settings.reg_bus.amo_post_cut else '0'};

  localparam int unsigned LogDepth   = 3;
  localparam int unsigned LlcAwWidth = (2**LogDepth)*axi_pkg::aw_width(AxiAddrWidth, LlcIdWidth, AxiUserWidth);
  localparam int unsigned LlcWWidth  = (2**LogDepth)*axi_pkg::w_width(AxiDataWidth, AxiUserWidth);
  localparam int unsigned LlcBWidth  = (2**LogDepth)*axi_pkg::b_width(LlcIdWidth, AxiUserWidth);
  localparam int unsigned LlcArWidth = (2**LogDepth)*axi_pkg::ar_width(AxiAddrWidth, LlcIdWidth, AxiUserWidth);
  localparam int unsigned LlcRWidth  = (2**LogDepth)*axi_pkg::r_width(AxiDataWidth, LlcIdWidth, AxiUserWidth);

  typedef logic [AxiAddrWidth-1:0] soc_reg_addr_t;
  typedef logic [31:0] soc_reg_data_t;
  typedef logic [ 3:0] soc_reg_strb_t;
  `REG_BUS_TYPEDEF_ALL(soc_reg, soc_reg_addr_t, soc_reg_data_t, soc_reg_strb_t)

  typedef logic [AxiAddrWidth-1:0]   soc_axi_addr_t;
  typedef logic [AxiDataWidth-1:0]   soc_axi_data_t;
  typedef logic [AxiDataWidth/8-1:0] soc_axi_strb_t;
  typedef logic [AxiUserWidth-1:0]   soc_axi_user_t;
  typedef logic [AxiIdWidth-1:0]     soc_axi_mst_id_t;
  typedef logic [ExtSlvIdWidth-1:0]  soc_axi_slv_id_t;
  typedef logic [LlcIdWidth-1:0]     soc_axi_llc_id_t;

  `AXI_TYPEDEF_ALL(soc_axi, soc_axi_addr_t, soc_axi_mst_id_t, soc_axi_data_t, soc_axi_strb_t, soc_axi_user_t)
  `AXI_TYPEDEF_ALL(soc_axi_slv, soc_axi_addr_t, soc_axi_slv_id_t, soc_axi_data_t, soc_axi_strb_t, soc_axi_user_t)
  `AXI_TYPEDEF_ALL(soc_axi_llc, soc_axi_addr_t, soc_axi_llc_id_t, soc_axi_data_t, soc_axi_strb_t, soc_axi_user_t)

  // Aliases for explicit narrow network mapping
  typedef soc_axi_req_t  soc_axi_narrow_req_t;
  typedef soc_axi_resp_t soc_axi_narrow_resp_t;

  % if wide_net:
  typedef logic [AxiWideDataWidth-1:0]   soc_axi_wide_data_t;
  typedef logic [AxiWideDataWidth/8-1:0] soc_axi_wide_strb_t;
  `AXI_TYPEDEF_ALL(soc_axi_wide, soc_axi_addr_t, soc_axi_mst_id_t, soc_axi_wide_data_t, soc_axi_wide_strb_t, soc_axi_user_t)
  % endif

  // =========================================================================
  // 0b. NOC AXI WIDTHS
  // =========================================================================
  // Specific widths for the internal NoC packet payloads.
  localparam int unsigned NoCAxiAwWidth = (2**LogDepth)*axi_pkg::aw_width(AxiAddrWidth, AxiIdWidth, AxiUserWidth);
  localparam int unsigned NoCAxiWWidth  = (2**LogDepth)*axi_pkg::w_width(AxiDataWidth, AxiUserWidth);
  localparam int unsigned NoCAxiBWidth  = (2**LogDepth)*axi_pkg::b_width(AxiIdWidth, AxiUserWidth);
  localparam int unsigned NoCAxiArWidth = (2**LogDepth)*axi_pkg::ar_width(AxiAddrWidth, AxiIdWidth, AxiUserWidth);
  localparam int unsigned NoCAxiRWidth  = (2**LogDepth)*axi_pkg::r_width(AxiDataWidth, AxiIdWidth, AxiUserWidth);

  // =========================================================================
  // 0c. CLOCK AND RESET DOMAINS
  // =========================================================================
  // Number of clock/reset domains in the system
<%
  gateable_domains = []
  for c in config.components:
      clk_tree = getattr(c, 'clock_tree', None)
      if clk_tree and getattr(clk_tree, 'clock_gating', False):
          gateable_domains.append(c.clock_domain)
%>
  localparam int unsigned NumDomains = ${len(config.clock_tree.domains)};

  typedef enum int unsigned {
% for dom in config.clock_tree.domains:
    DomainIdx_${fmt_name(dom.name)} = ${loop.index}${"," if not loop.last else ""}
% endfor
  } domain_idx_e;

  // =========================================================================
  // 1. MESH DIMENSIONS AND TOPOLOGY
  // =========================================================================
  // Defines the physical limits of the Network-on-Chip and provides a static
  // bitmap (MeshMap) indicating the presence of active tiles vs dummy routers.
  typedef struct packed {
    int unsigned x;
    int unsigned y;
  } mesh_dim_t;

  localparam mesh_dim_t MaxId = '{x: ${max_x}, y: ${max_y}};
  localparam mesh_dim_t MinId = '{x: 0, y: 0};
  
  typedef logic [MaxId.y:0][MaxId.x:0] mesh_map_t;

  // Bitmap of the NoC mesh. 1 = Occupied Tile, 0 = Empty/Dummy
  localparam mesh_map_t MeshMap = '{
% for y in reversed(range(mesh_dim_y)):
    ${mesh_dim_x}'b${"".join([str(mesh_map[y][x]) for x in reversed(range(mesh_dim_x))])}${"," if y > 0 else ""} // y=${y}
% endfor
  };

  localparam mesh_dim_t MeshDim = '{x: ${mesh_dim_x}, y: ${mesh_dim_y}};
  localparam int unsigned NumTiles = ${num_tiles};
  localparam int unsigned NumDummyTiles = (MeshDim.x * MeshDim.y) - NumTiles;

  // =========================================================================
  // 2. ROUTING HELPER FUNCTIONS
  // =========================================================================
  // Pure SystemVerilog functions used at elaboration time to compute
  // node connections, boundary tie-offs, and relative coordinates within the NoC.

  // Whether the connection is a tie-off (edge of the mesh)
  function automatic bit is_tie_off(int x, int y, route_direction_e dir);
    return (x == 0 && dir == West) || (x == MeshDim.x-1 && dir == East) ||
           (y == 0 && dir == South) || (y == MeshDim.y-1 && dir == North);
  endfunction

  // Returns the X-coordinate of the neighbor in the given direction
  function automatic int neighbor_x(int x, route_direction_e dir);
    return (dir == West) ? x - 1 : (dir == East) ? x + 1 : x;
  endfunction

  // Returns the Y-coordinate of the neighbor in the given direction
  function automatic int neighbor_y(int y, route_direction_e dir);
    return (dir == South) ? y - 1 : (dir == North) ? y + 1 : y;
  endfunction

  // Returns the opposite direction
  function automatic route_direction_e opposite_dir(route_direction_e dir);
    return (dir == West) ? East : (dir == East) ? West : (dir == South) ? North : South;
  endfunction

  function automatic floo_pkg::route_cfg_t gen_nomcast_route_cfg();
    floo_pkg::route_cfg_t ret = floo_ollivander_noc_pkg::RouteCfg;
    // Disable multicast for non-cluster tiles
    ret.CollectiveCfg = floo_pkg::CollectiveDefaultCfg;
    return ret;
  endfunction

  localparam floo_pkg::route_cfg_t RouteCfgNoMcast = gen_nomcast_route_cfg();

  // =========================================================================
  // 4. AXI CROSSBAR RULES (HOST -> CHIMNEY)
  // =========================================================================
  // Address map rules for routing AXI traffic from the Host into the NoC.
<%
  num_axi_slvs = len(axi_slaves)
%>
  localparam int unsigned AxiExtNumRules = ${num_axi_slvs};
  localparam logic [${num_axi_slvs-1}:0][7:0] AxiExtRegionIdx = {
% for i in reversed(range(num_axi_slvs)):
    8'd0${"," if i != 0 else ""}
% endfor
  };
  localparam logic [${num_axi_slvs-1}:0][63:0] AxiExtRegionStart = {
% for slv in axi_slaves[::-1]:
    64'h${parse_hex(slv['base'])}${"," if not loop.last else ""}
% endfor
  };
  localparam logic [${num_axi_slvs-1}:0][63:0] AxiExtRegionEnd = {
% for slv in axi_slaves[::-1]:
    64'h${parse_hex(slv['base'])} + 64'h${parse_hex(slv['size'])}${"," if not loop.last else ""}
% endfor
  };

  // =========================================================================
  // 5. REGBUS SUBSYSTEM RULES
  // =========================================================================
  // Address map rules for the peripheral configuration bus (RegBus).
  // Contains the base addresses for the System Controller and external registers.
<%
  ext_regs = config.system_controller.external_registers if config.system_controller else []
  reg_slaves = [{'name': config.system_controller.name, 'base': config.system_controller.base_addr, 'size': config.system_controller.size if config.system_controller.size else '0x1000'}] if config.system_controller else []
  for ext in ext_regs:
      reg_slaves.append({'name': ext.name, 'base': ext.base_addr, 'size': ext.size if ext.size else '0x1000'})
  num_reg_slvs = len(reg_slaves)
%>
  localparam int unsigned RegExtNumRules = ${num_reg_slvs};
  localparam logic [${num_reg_slvs-1}:0][7:0] RegExtRegionIdx = {
% for i in reversed(range(num_reg_slvs)):
    8'd${i}${"," if i != 0 else ""}
% endfor
  };
  localparam logic [${num_reg_slvs-1}:0][63:0] RegExtRegionStart = {
% for slv in reg_slaves[::-1]:
    64'h${parse_hex(slv['base'])}${"," if not loop.last else ""}
% endfor
  };
  localparam logic [${num_reg_slvs-1}:0][63:0] RegExtRegionEnd = {
% for slv in reg_slaves[::-1]:
    64'h${parse_hex(slv['base'])} + 64'h${parse_hex(slv['size'])}${"," if not loop.last else ""}
% endfor
  };

endpackage : ${pkg}
