<%
  p_name = config.project.name
  pkg = "ollivander_soc_pkg"

  # ============================================================================
  # 1. NOC MESH GRID CALCULATION
  # ============================================================================
  # Parses the 'placement' constraints from the YAML configuration to determine
  # the physical dimensions of the 2D mesh. It calculates the maximum X and Y
  # coordinates and tracks which tiles are active vs empty.
  tiles = [] # list of (x, y, component)
  
  def add_placement(c, placement):
      if not placement: return
      logical = placement.get('logical')
      if not logical: return
      
      if isinstance(logical, list):
          for l in logical: process_logical(c, l)
      else:
          process_logical(c, logical)
          
  def process_logical(c, l):
      if 'x' in l and 'y' in l:
          x, y = l['x'], l['y']
          tiles.append((x, y, c))
      elif 'box' in l:
          box = l['box']
          x_start, x_end = box['x_start'], box['x_end']
          y_start, y_end = box['y_start'], box['y_end']
          for x in range(x_start, x_end + 1):
              for y in range(y_start, y_end + 1):
                  tiles.append((x, y, c))

  add_placement(config.host, config.host.placement)
  if config.components:
      for c in config.components: add_placement(c, c.placement)
          
  max_x = max([t[0] for t in tiles]) if tiles else 0
  max_y = max([t[1] for t in tiles]) if tiles else 0

  mesh_dim_x = max_x + 1
  mesh_dim_y = max_y + 1
  
  # Create a 2D bitmap of the mesh to distinguish active tiles from empty ones (Dummy routers).
  mesh_map = [[0 for _ in range(mesh_dim_x)] for _ in range(mesh_dim_y)]
  for x, y, _ in tiles: mesh_map[y][x] = 1

  num_tiles = sum(sum(row) for row in mesh_map)
  
  axi_masters = [c.name for c in config.components if c.interfaces and c.interfaces.get('axi_master')]
  
  def parse_hex(val):
      if isinstance(val, int): return f"{val:X}"
      return str(val).replace('0x', '').replace('_', '').upper()
      
  axi_slaves = []
  for c in config.components:
      if c.interfaces and 'axi_slave' in c.interfaces:
          for slv in c.interfaces['axi_slave']:
              axi_slaves.append({'name': c.name, 'base': slv['base_addr'], 'size': slv.get('size', slv.get('size_per_instance', '0x1000'))})
%><%namespace file="/license_header.mako" import="license"/>\
${license()}\
//
// AUTOMATICALLY GENERATED BY OLLIVANDER - DO NOT EDIT DIRECTLY
//
// NoC SoC Global Package for ${p_name.upper()}
// Contains Mesh routing information and NoC global definitions.
//
// BENDER: name="floo_noc"
// BENDER: name="axi"
// BENDER: name="register_interface"

`include "axi/typedef.svh"
`include "register_interface/typedef.svh"

package ${pkg};

  import floo_pkg::*;
  import floo_ollivander_noc_pkg::*;

  // =========================================================================
  // 0. GLOBAL ARCHITECTURE PARAMETERS & TYPES
  // =========================================================================
  // Defines the standard widths for addresses, data, and sideband signals
  // used by the AXI and RegBus interfaces across the entire SoC.
<%
  if config.topology.global_bus:
      g_addr_w = config.topology.global_bus.addr_width
      g_data_w = config.topology.global_bus.data_width
      g_user_w = config.topology.global_bus.user_width
      g_id_w   = config.topology.global_bus.mst_id_width
  else:
      narrow_net = config.topology.noc_settings.networks.get('narrow')
      g_addr_w = narrow_net.addr_width if narrow_net else 48
      g_data_w = narrow_net.data_width if narrow_net else 64
      g_user_w = 10
      g_id_w   = 4
      
  wide_net = config.topology.noc_settings.networks.get('wide') if config.topology.noc_settings and config.topology.noc_settings.networks else None
%>
  localparam int unsigned AxiAddrWidth     = ${g_addr_w};
  localparam int unsigned AxiDataWidth     = ${g_data_w};
  localparam int unsigned AxiUserWidth     = ${g_user_w};
  localparam int unsigned AxiIdWidth       = ${g_id_w};
  % if wide_net:
  localparam int unsigned AxiWideDataWidth = ${wide_net.data_width};
  % endif
  
  localparam int unsigned ExtSlvIdWidth    = AxiIdWidth + $clog2(${len(axi_masters)} > 1 ? ${len(axi_masters)} : 2);
  localparam int unsigned LlcIdWidth       = ExtSlvIdWidth + 1; // Margin for LLC bypass bit

  // L2 Memory Base Addresses (Extracted from components for memory interleaving)
<%
  l2_slv = next((s for s in axi_slaves if 'l2' in s['name']), None)
  l2_base = l2_slv['base'] if l2_slv else 0
  l2_size = l2_slv['size'] if l2_slv else 0
%>\
  localparam logic [63:0] L2Port0InterlBase    = 64'h${parse_hex(l2_base)};
  localparam logic [63:0] L2Port0NonInterlBase = 64'h${parse_hex(l2_base)} + 64'h${parse_hex(l2_size)}/2;
  localparam logic [63:0] L2Port1InterlBase    = 64'h${parse_hex(l2_base)};
  localparam logic [63:0] L2Port1NonInterlBase = 64'h${parse_hex(l2_base)} + 64'h${parse_hex(l2_size)}/2;
  
  localparam int unsigned AxiUserAmoMsb    = ${config.system_settings.user_mapping.amo_msb};
  localparam int unsigned AxiUserAmoLsb    = ${config.system_settings.user_mapping.amo_lsb};
  localparam int unsigned AxiUserEccErrBit = ${config.system_settings.user_mapping.ecc_err_bit};

  localparam int unsigned LlcMaxReadTxns  = ${config.system_settings.llc.max_read_txns};
  localparam int unsigned LlcMaxWriteTxns = ${config.system_settings.llc.max_write_txns};
  localparam int unsigned LlcAmoNumCuts   = ${config.system_settings.llc.amo_num_cuts};
  localparam bit          LlcAmoPostCut   = ${'1' if config.system_settings.llc.amo_post_cut else '0'};

  localparam int unsigned RegMaxReadTxns  = ${config.system_settings.reg_bus.max_read_txns};
  localparam int unsigned RegMaxWriteTxns = ${config.system_settings.reg_bus.max_write_txns};
  localparam int unsigned RegAmoNumCuts   = ${config.system_settings.reg_bus.amo_num_cuts};
  localparam bit          RegAmoPostCut   = ${'1' if config.system_settings.reg_bus.amo_post_cut else '0'};

  localparam int unsigned LogDepth   = 3;
  localparam int unsigned LlcAwWidth = (2**LogDepth)*axi_pkg::aw_width(AxiAddrWidth, LlcIdWidth, AxiUserWidth);
  localparam int unsigned LlcWWidth  = (2**LogDepth)*axi_pkg::w_width(AxiDataWidth, AxiUserWidth);
  localparam int unsigned LlcBWidth  = (2**LogDepth)*axi_pkg::b_width(LlcIdWidth, AxiUserWidth);
  localparam int unsigned LlcArWidth = (2**LogDepth)*axi_pkg::ar_width(AxiAddrWidth, LlcIdWidth, AxiUserWidth);
  localparam int unsigned LlcRWidth  = (2**LogDepth)*axi_pkg::r_width(AxiDataWidth, LlcIdWidth, AxiUserWidth);

  typedef logic [AxiAddrWidth-1:0] soc_reg_addr_t;
  typedef logic [31:0] soc_reg_data_t;
  typedef logic [ 3:0] soc_reg_strb_t;
  `REG_BUS_TYPEDEF_ALL(soc_reg, soc_reg_addr_t, soc_reg_data_t, soc_reg_strb_t)

  typedef logic [AxiAddrWidth-1:0]   soc_axi_addr_t;
  typedef logic [AxiDataWidth-1:0]   soc_axi_data_t;
  typedef logic [AxiDataWidth/8-1:0] soc_axi_strb_t;
  typedef logic [AxiUserWidth-1:0]   soc_axi_user_t;
  typedef logic [AxiIdWidth-1:0]     soc_axi_mst_id_t;
  typedef logic [ExtSlvIdWidth-1:0]  soc_axi_slv_id_t;

  `AXI_TYPEDEF_ALL(soc_axi, soc_axi_addr_t, soc_axi_mst_id_t, soc_axi_data_t, soc_axi_strb_t, soc_axi_user_t)
  `AXI_TYPEDEF_ALL(soc_axi_slv, soc_axi_addr_t, soc_axi_slv_id_t, soc_axi_data_t, soc_axi_strb_t, soc_axi_user_t)

  // Aliases for explicit narrow network mapping
  typedef soc_axi_req_t  soc_axi_narrow_req_t;
  typedef soc_axi_resp_t soc_axi_narrow_resp_t;

  % if wide_net:
  typedef logic [AxiWideDataWidth-1:0]   soc_axi_wide_data_t;
  typedef logic [AxiWideDataWidth/8-1:0] soc_axi_wide_strb_t;
  `AXI_TYPEDEF_ALL(soc_axi_wide, soc_axi_addr_t, soc_axi_mst_id_t, soc_axi_wide_data_t, soc_axi_wide_strb_t, soc_axi_user_t)
  % endif

  // =========================================================================
  // 0b. NOC AXI WIDTHS
  // =========================================================================
  // Specific widths for the internal NoC packet payloads.
  localparam int unsigned NoCAxiAwWidth = (2**LogDepth)*axi_pkg::aw_width(AxiAddrWidth, AxiIdWidth, AxiUserWidth);
  localparam int unsigned NoCAxiWWidth  = (2**LogDepth)*axi_pkg::w_width(AxiDataWidth, AxiUserWidth);
  localparam int unsigned NoCAxiBWidth  = (2**LogDepth)*axi_pkg::b_width(AxiIdWidth, AxiUserWidth);
  localparam int unsigned NoCAxiArWidth = (2**LogDepth)*axi_pkg::ar_width(AxiAddrWidth, AxiIdWidth, AxiUserWidth);
  localparam int unsigned NoCAxiRWidth  = (2**LogDepth)*axi_pkg::r_width(AxiDataWidth, AxiIdWidth, AxiUserWidth);

  // =========================================================================
  // 1. MESH DIMENSIONS AND TOPOLOGY
  // =========================================================================
  // Defines the physical limits of the Network-on-Chip and provides a static
  // bitmap (MeshMap) indicating the presence of active tiles vs dummy routers.
  typedef struct packed {
    int unsigned x;
    int unsigned y;
  } mesh_dim_t;

  localparam mesh_dim_t MaxId = '{x: ${max_x}, y: ${max_y}};
  localparam mesh_dim_t MinId = '{x: 0, y: 0};
  
  typedef logic [MaxId.y:0][MaxId.x:0] mesh_map_t;

  // Bitmap of the NoC mesh. 1 = Occupied Tile, 0 = Empty/Dummy
  localparam mesh_map_t MeshMap = '{
% for y in reversed(range(mesh_dim_y)):
    ${mesh_dim_x}'b${"".join([str(mesh_map[y][x]) for x in reversed(range(mesh_dim_x))])}${"," if y > 0 else ""} // y=${y}
% endfor
  };

  localparam mesh_dim_t MeshDim = '{x: ${mesh_dim_x}, y: ${mesh_dim_y}};
  localparam int unsigned NumTiles = ${num_tiles};
  localparam int unsigned NumDummyTiles = (MeshDim.x * MeshDim.y) - NumTiles;

  // =========================================================================
  // 2. ROUTING HELPER FUNCTIONS
  // =========================================================================
  // Pure SystemVerilog functions used at elaboration time to compute
  // node connections, boundary tie-offs, and relative coordinates within the NoC.

  // Whether the connection is a tie-off (edge of the mesh)
  function automatic bit is_tie_off(int x, int y, route_direction_e dir);
    return (x == 0 && dir == West) || (x == MeshDim.x-1 && dir == East) ||
           (y == 0 && dir == South) || (y == MeshDim.y-1 && dir == North);
  endfunction

  // Returns the X-coordinate of the neighbor in the given direction
  function automatic int neighbor_x(int x, route_direction_e dir);
    return (dir == West) ? x - 1 : (dir == East) ? x + 1 : x;
  endfunction

  // Returns the Y-coordinate of the neighbor in the given direction
  function automatic int neighbor_y(int y, route_direction_e dir);
    return (dir == South) ? y - 1 : (dir == North) ? y + 1 : y;
  endfunction

  // Returns the opposite direction
  function automatic route_direction_e opposite_dir(route_direction_e dir);
    return (dir == West) ? East : (dir == East) ? West : (dir == South) ? North : South;
  endfunction

  // =========================================================================
  // 3. MULTICAST CONFIGURATIONS
  // =========================================================================
  localparam floo_pkg::route_cfg_t RouteCfgNoMcast = floo_ollivander_noc_pkg::RouteCfg;

  // =========================================================================
  // 4. AXI CROSSBAR RULES (HOST -> CHIMNEY)
  // =========================================================================
  // Address map rules for routing AXI traffic from the Host into the NoC.
  localparam int unsigned AxiExtNumRules = 1;
  localparam logic [0:0][7:0] AxiExtRegionIdx = '{8'd0};
  localparam logic [0:0][63:0] AxiExtRegionStart = '{64'h0000000000000000};
  localparam logic [0:0][63:0] AxiExtRegionEnd   = '{64'hFFFFFFFFFFFFFFFF};

  // =========================================================================
  // 5. REGBUS SUBSYSTEM RULES
  // =========================================================================
  // Address map rules for the peripheral configuration bus (RegBus).
  // Contains the base addresses for the System Controller and external registers.
<%
  ext_regs = config.system_controller.external_registers if config.system_controller else []
  reg_slaves = [{'name': config.system_controller.name, 'base': config.system_controller.base_addr, 'size': config.system_controller.size if config.system_controller.size else '0x1000'}] if config.system_controller else []
  for ext in ext_regs:
      reg_slaves.append({'name': ext.name, 'base': ext.base_addr, 'size': ext.size if ext.size else '0x1000'})
  num_reg_slvs = len(reg_slaves)
%>
  localparam int unsigned RegExtNumRules = ${num_reg_slvs};
  localparam logic [${num_reg_slvs-1}:0][7:0] RegExtRegionIdx = {
% for i in reversed(range(num_reg_slvs)):
    8'd${i}${"," if i != 0 else ""}
% endfor
  };
  localparam logic [${num_reg_slvs-1}:0][63:0] RegExtRegionStart = {
% for slv in reg_slaves[::-1]:
    64'h${parse_hex(slv['base'])}${"," if not loop.last else ""}
% endfor
  };
  localparam logic [${num_reg_slvs-1}:0][63:0] RegExtRegionEnd = {
% for slv in reg_slaves[::-1]:
    64'h${parse_hex(slv['base'])} + 64'h${parse_hex(slv['size'])}${"," if not loop.last else ""}
% endfor
  };

endpackage : ${pkg}