<%
  import re
  p_name = config.project.name
  pkg    = f"{p_name}_soc_pkg"
  rpkg   = f"{p_name}_reg_pkg"
  npkg   = f"floo_{p_name}_noc_pkg"
  host_clk = config.host.clock_domain or "system_clk"
  
  # Costruzione della griglia bidimensionale per il piazzamento delle Tile
  comps = [config.host] + config.components
  max_x, max_y = 0, 0
  grid = {}
  
  for c in comps:
      p = getattr(c, 'placement', None)
      if not p or 'logical' not in p: continue
      
      log = p['logical']
      items = log if isinstance(log, list) else [log]
      inst_idx = 0
      for item in items:
          if 'box' in item:
              b = item['box']
              for x in range(b['x_start'], b['x_end']+1):
                  for y in range(b['y_start'], b['y_end']+1):
                      grid[(x,y)] = (c, inst_idx)
                      inst_idx += 1
                      max_x = max(max_x, x)
                      max_y = max(max_y, y)
          else:
              x, y = item['x'], item['y']
              grid[(x,y)] = (c, inst_idx)
              inst_idx += 1
              max_x = max(max_x, x)
              max_y = max(max_y, y)
              
  for x in range(max_x + 1):
      for y in range(max_y + 1):
          if (x,y) not in grid:
              grid[(x,y)] = (None, 0)
%><%namespace file="/license_header.mako" import="license"/>\
${license()}\
//
// AUTOMATICALLY GENERATED BY OLLIVANDER - DO NOT EDIT DIRECTLY
//
// Top-Level SystemVerilog Module for ${p_name.upper()}
// Topology: Network-on-Chip (FlooNoC)
// Mesh Dimensions: ${max_x + 1} x ${max_y + 1}
// (See ${p_name}_noc_map.csv for the 2D grid placement)
//
// BENDER: name="floo_noc"
// BENDER: name="register_interface"

`include "floo_noc/typedef.svh"
`include "register_interface/typedef.svh"

module ${p_name}
  import ${pkg}::*;
  import ${rpkg}::*;
  import floo_pkg::*;
  import ${npkg}::*;
<%
  # Auto-inject imports from component headers to resolve exported constants and types
  all_imports = set()
  for c in [config.host] + config.components:
      h_header = comp_info.get(c.name, {}).get("header_content", "")
      imports = re.findall(r'\bimport\s+([a-zA-Z_][a-zA-Z0-9_]*)::\*;', h_header)
      for imp in imports:
          if imp not in [pkg, rpkg, "floo_pkg", npkg]:
              all_imports.add(imp)
%>\
% for imp in sorted(all_imports):
  import ${imp}::*;
% endfor
(
  // Global Clock and Reset
% if config.clock_tree.flls > 0:
  input  logic [${config.clock_tree.flls - 1}:0] domain_clk_i,
  input  logic [${config.clock_tree.flls - 1}:0] fll_lock_i,
  input  logic pwr_on_rst_ni,
% else:
  input  logic clk_i,
  input  logic rst_ni,
% endif
  input  logic test_mode_i,
  input  logic [1:0] boot_mode_i,
  input  logic rtc_i,
  input  logic clk_rst_bypass_i,
  
  // JTAG and Debug (Host)
  input  logic jtag_tck_i,
  input  logic jtag_trst_ni,
  input  logic jtag_tms_i,
  input  logic jtag_tdi_i,
  output logic jtag_tdo_o,
  output logic jtag_tdo_oe_o\
<%
  all_extra_ports = []
  # Key: (comp.name, inst_idx), Value: list of connection strings
  comp_extra_conns = {}
  
  # This map now only contains exceptions to the standard rule 'if_name + "_"'
  interface_port_map = {
      "spi": ["spi_", "spih_"], # Exception: YAML 'spi' maps to 'spih_' prefix
      "hyperbus": ["pad_hyper_", "pad_config_"]
  }
  
  for comp in [config.host] + config.components:
      exported_interfaces = comp.export_interfaces if comp.export_interfaces else []
      if not exported_interfaces:
          continue
          
      # Find number of instances for this component
      num_instances = 0
      inst_coords = {}
      for (gx, gy), (c_grid, idx) in grid.items():
          if c_grid and c_grid.name == comp.name:
              num_instances = max(num_instances, idx + 1)
              inst_coords[idx] = (gx, gy)
      if num_instances == 0:
          num_instances = 1

      c_header = comp_info.get(comp.name, {}).get("header_content", "")
      prefixes_to_export = []
      for if_name in exported_interfaces:
          prefixes = interface_port_map.get(if_name, [if_name + "_"])
          prefixes_to_export.extend(prefixes)
          
      known_params = {}
      known_params.update(comp_info.get(comp.name, {}).get("supported_params", {}))
      known_params.update(comp_info.get(comp.name, {}).get("fixed_params", {}))
      if comp.parameters:
          for k, v in comp.parameters.items():
              known_params[k] = "1" if v is True else "0" if v is False else str(v)
              
      port_matches = re.finditer(r'\b(input|output|inout)\b\s+([^,;]+)', c_header)
      for m in port_matches:
          p_dir = m.group(1)
          decl = re.sub(r'//.*', '', m.group(2)).strip()
          decl = re.sub(r'/\*.*?\*/', '', decl, flags=re.DOTALL).strip().split('=')[0].strip()
          
          name_match = re.search(r'\b([a-zA-Z_][a-zA-Z0-9_]*)\s*((?:\[[^\]]*\]\s*)*)$', decl)
          if name_match:
              port_name = name_match.group(1)
              if any(port_name.startswith(prefix) for prefix in prefixes_to_export):
                  # Evaluate parameters in the port declaration
                  for param_name, param_val in known_params.items():
                      decl = re.sub(rf'\b{param_name}\b', param_val, decl)
                  
                  is_host = (comp.name == config.host.name)
                  for inst_idx in range(num_instances):
                      if is_host:
                          top_port_name = port_name
                      else:
                          if num_instances > 1:
                              cx, cy = inst_coords.get(inst_idx, (0,0))
                              top_port_name = f"{comp.name}_{cx}_{cy}_{port_name}"
                          else:
                              top_port_name = f"{comp.name}_{port_name}"
                      
                      inst_decl = decl[:name_match.start()] + top_port_name + name_match.group(2)
                      all_extra_ports.append(f"{p_dir} {inst_decl}")
                      
                      key = (comp.name, inst_idx)
                      if key not in comp_extra_conns:
                          comp_extra_conns[key] = []
                      comp_extra_conns[key].append(f".{port_name:<17} ( {top_port_name} )")

  # Add RegBus ports for external registers
  if config.system_controller and config.system_controller.external_registers:
      for ext_reg in config.system_controller.external_registers:
          all_extra_ports.append(f"output soc_reg_req_t {ext_reg.name}_reg_req_o")
          all_extra_ports.append(f"input  soc_reg_rsp_t {ext_reg.name}_reg_rsp_i")
%>\
${"," if all_extra_ports else ""}
% if all_extra_ports:

  // ---------------------------------------------------------
  // External Component Ports
  // ---------------------------------------------------------
  ${",\n  ".join(all_extra_ports)}
% endif
);

  // =========================================================================
  // 1. SYSTEM REGISTERS
  // =========================================================================
  ${p_name}_reg2hw_t sys_regs_reg2hw;
  ${p_name}_hw2reg_t sys_regs_hw2reg;

<%
  ext_regs = config.system_controller.external_registers if config.system_controller else []
  num_reg_slvs = len(ext_regs) + 1
%>
% if ext_regs:
  soc_reg_req_t [${num_reg_slvs-1}:0] host_reg_req;
  soc_reg_rsp_t [${num_reg_slvs-1}:0] host_reg_rsp;
  
 % for i, ext_reg in enumerate(ext_regs):
  assign ${ext_reg.name}_reg_req_o = host_reg_req[${i+1}];
  assign host_reg_rsp[${i+1}]      = ${ext_reg.name}_reg_rsp_i;
 % endfor
  assign host_reg_rsp[0] = '0; // Handled internally by the Host Tile
% endif

  // =========================================================================
  // 2. CLOCK AND RESET TREE
  // =========================================================================
<%namespace file="/hw/infrastructure/clock_reset.mako" import="clock_and_reset_tree"/>\
${clock_and_reset_tree(config, p_name)}

  // =========================================================================
  // 3. FLOONOC 2D MESH ARRAYS
  // =========================================================================
  floo_req_t  [${max_x}:0][${max_y}:0][West:North] tile_req_o, tile_req_i;
  floo_rsp_t  [${max_x}:0][${max_y}:0][West:North] tile_rsp_o, tile_rsp_i;
  floo_wide_t [${max_x}:0][${max_y}:0][West:North] tile_wide_o, tile_wide_i;

  // Mesh wiring generation
  // Horizontal connections (East-West)
  for (genvar y = 0; y <= ${max_y}; y++) begin : gen_x_links
    for (genvar x = 0; x < ${max_x}; x++) begin : gen_x_inner
      assign tile_req_i[x+1][y][West] = tile_req_o[x][y][East];
      assign tile_rsp_i[x][y][East]   = tile_rsp_o[x+1][y][West];
      assign tile_wide_i[x+1][y][West]= tile_wide_o[x][y][East];

      assign tile_req_i[x][y][East]   = tile_req_o[x+1][y][West];
      assign tile_rsp_i[x+1][y][West] = tile_rsp_o[x][y][East];
      assign tile_wide_i[x][y][East]  = tile_wide_o[x+1][y][West];
    end
    // Boundaries
    assign tile_req_i[0][y][West] = '0;
    assign tile_rsp_i[0][y][West] = '0;
    assign tile_wide_i[0][y][West] = '0;
    
    assign tile_req_i[${max_x}][y][East] = '0;
    assign tile_rsp_i[${max_x}][y][East] = '0;
    assign tile_wide_i[${max_x}][y][East] = '0;
  end

  // Vertical connections (North-South)
  for (genvar x = 0; x <= ${max_x}; x++) begin : gen_y_links
    for (genvar y = 0; y < ${max_y}; y++) begin : gen_y_inner
      assign tile_req_i[x][y+1][South] = tile_req_o[x][y][North];
      assign tile_rsp_i[x][y][North]   = tile_rsp_o[x][y+1][South];
      assign tile_wide_i[x][y+1][South]= tile_wide_o[x][y][North];

      assign tile_req_i[x][y][North]   = tile_req_o[x][y+1][South];
      assign tile_rsp_i[x][y+1][South] = tile_rsp_o[x][y][North];
      assign tile_wide_i[x][y][North]  = tile_wide_o[x][y+1][South];
    end
    // Boundaries
    assign tile_req_i[x][0][South] = '0;
    assign tile_rsp_i[x][0][South] = '0;
    assign tile_wide_i[x][0][South] = '0;
    
    assign tile_req_i[x][${max_y}][North] = '0;
    assign tile_rsp_i[x][${max_y}][North] = '0;
    assign tile_wide_i[x][${max_y}][North] = '0;
  end

  // =========================================================================
  // 4. TILE INSTANTIATIONS
  // =========================================================================
% for y in range(max_y + 1):
 % for x in range(max_x + 1):
  <% 
    c, inst_idx = grid[(x,y)]
    t_name = f"i_tile_{x}_{y}"
  %>
  % if c is None:
  // --- DUMMY TILE @ (${x}, ${y}) ---
  ${p_name}_dummy_tile ${t_name} (
    .clk_i       ( ${host_clk} ),
    .rst_ni      ( host_pwr_on_rst_n ),
    .test_mode_i ( test_mode_i ),
    .id_i        ( '{ x: ${x}, y: ${y}, port_id: 0 } ),
    .floo_req_o  ( tile_req_o[${x}][${y}] ),
    .floo_rsp_i  ( tile_rsp_i[${x}][${y}] ),
    .floo_wide_o ( tile_wide_o[${x}][${y}] ),
    .floo_req_i  ( tile_req_i[${x}][${y}] ),
    .floo_rsp_o  ( tile_rsp_o[${x}][${y}] ),
    .floo_wide_i ( tile_wide_i[${x}][${y}] )
  );
  
  % else:
  <%
    is_host = (c.name == config.host.name)
    module_type = f"{p_name}_{c.type}"
    
    # Determine number of instances for this component to properly suffix generated wire names
    num_instances = 0
    for (gx, gy), (c_grid, c_idx) in grid.items():
        if c_grid and c_grid.name == c.name:
            num_instances = max(num_instances, c_idx + 1)
            
    # Determine clock and reset connections
    c_clk = c.clock_domain or host_clk
    c_rst = c.reset_domain or c_clk.replace('_clk', '_rst')
    if c_rst == host_clk.replace('_clk', '_rst'):
        c_rst_wire = 'host_pwr_on_rst_n'
    else:
        c_rst_wire = f'rsts_n[DomainIdx_{fmt_rst(c_rst)}]'
    
    # Determine Auto Control Group bindings
    ctrl_group = None
    if config.system_controller and config.system_controller.auto_control_groups:
        for g in config.system_controller.auto_control_groups:
            if g.target_component_type in [c.type, c.type.replace('_tile', '_subtile'), c.type.replace('_tile', '_isle')]:
                ctrl_group = g
                break
                
    # Extract base address and size if available (for clusters)
    base_addr = 0
    size_per_inst = 0
    if c.interfaces and 'axi_slave' in c.interfaces:
        slvs = c.interfaces['axi_slave']
        if isinstance(slvs, list) and len(slvs) > 0:
            base_addr = slvs[0].get('base_addr', 0)
            size_per_inst = slvs[0].get('size_per_instance', 0)
            
    conns = [
        f".clk_i       ( {c_clk} )",
        f".rst_ni      ( {c_rst_wire} )",
        ".test_mode_i ( test_mode_i )",
        f".id_i        ( '{{ x: {x}, y: {y}, port_id: 0 }} )",
        f".floo_req_o  ( tile_req_o[{x}][{y}] )",
        f".floo_rsp_i  ( tile_rsp_i[{x}][{y}] )",
        f".floo_wide_o ( tile_wide_o[{x}][{y}] )",
        f".floo_req_i  ( tile_req_i[{x}][{y}] )",
        f".floo_rsp_o  ( tile_rsp_o[{x}][{y}] )",
        f".floo_wide_i ( tile_wide_i[{x}][{y}] )"
    ]
    
    if is_host:
        host_conns_dict = {
            "sys_regs_reg2hw_o": "sys_regs_reg2hw",
            "sys_regs_hw2reg_i": "sys_regs_hw2reg",
            "boot_mode_i": "boot_mode_i",
            "rtc_i": "rtc_i",
            "jtag_tck_i": "jtag_tck_i",
            "jtag_trst_ni": "jtag_trst_ni",
            "jtag_tms_i": "jtag_tms_i",
            "jtag_tdi_i": "jtag_tdi_i",
            "jtag_tdo_o": "jtag_tdo_o",
            "jtag_tdo_oe_o": "jtag_tdo_oe_o",
            "reg_req_o": "host_reg_req" if ext_regs else "/* unused */",
            "reg_rsp_i": "host_reg_rsp" if ext_regs else "'0"
        }
        for hc in comp_extra_conns.get((c.name, inst_idx), []):
            m = re.match(r'\.([a-zA-Z0-9_]+)\s*\((.*?)\)', hc)
            if m: host_conns_dict[m.group(1)] = m.group(2).strip()
            
        h_header = comp_info.get(c.name, {}).get("header_content", "")
        port_matches = re.finditer(r'\b(input|output|inout)\b\s+([^,;]+)', h_header)
        for m in port_matches:
            p_dir = m.group(1)
            decl = re.sub(r'//.*', '', m.group(2)).strip()
            decl = re.sub(r'/\*.*?\*/', '', decl, flags=re.DOTALL).strip().split('=')[0].strip()
            decl = re.sub(r'\)\s*$', '', decl).strip()
            name_match = re.search(r'\b([a-zA-Z_][a-zA-Z0-9_]*)\s*((?:\[[^\]]*\]\s*)*)$', decl)
            if name_match:
                port_name_from_header = name_match.group(1)
                if port_name_from_header not in ["clk_i", "rst_ni", "test_mode_i", "id_i", "sys_clk_i", "sys_rst_ni", "rt_clk_i", "pwr_on_rst_ni", "floo_req_o", "floo_rsp_i", "floo_wide_o", "floo_req_i", "floo_rsp_o", "floo_wide_i"] and port_name_from_header not in host_conns_dict:
                    host_conns_dict[port_name_from_header] = "'0" if p_dir == "input" else ""
                    
        for p, w in host_conns_dict.items():
            conns.append(f".{p:<17} ( {w} )")
    else:
        if ctrl_group:
            conns.extend([
                f".tile_clk_en_i    ( sys_regs_reg2hw.{ctrl_group.name.lower()}_clk_en.q[{inst_idx}] )",
                f".tile_rst_ni      ( ~sys_regs_reg2hw.{ctrl_group.name.lower()}_rst.q[{inst_idx}] )",
                f".clk_rst_bypass_i ( clk_rst_bypass_i )"
            ])
            
        # Generic integration based on SystemVerilog header parsing
        c_header = comp_info.get(c.name, {}).get("header_content", "")
        if "hart_base_id_i" in c_header:
            nr_cores = c.parameters.get('NrCores', 'snitch_cluster_pkg::NrCores') if c.parameters else 'snitch_cluster_pkg::NrCores'
            conns.append(f".hart_base_id_i        ( ({inst_idx} * {nr_cores}) + 1 )") # +1 to reserve Hart 0 for the Host
        if "cluster_base_addr_i" in c_header:
            conns.append(f".cluster_base_addr_i   ( 64'h{'%X' % (base_addr)} + ({inst_idx} * 64'h{'%X' % (size_per_inst)}) )")
        if "cluster_base_offset_i" in c_header:
            conns.append(f".cluster_base_offset_i ( 64'h{'%X' % (size_per_inst)} )")
            
        # Inject extra standard internal signals
        c_i = comp_info.get(c.name, {})
        if c_i.get('has_sys_clk'): conns.append(f".sys_clk_i     ( {host_clk} )")
        if c_i.get('has_sys_rst'): conns.append(f".sys_rst_ni    ( host_pwr_on_rst_n )")
        if c_i.get('has_pwr_on_rst'):
            por_wire = 'host_pwr_on_rst_n' if c_rst == host_clk.replace('_clk', '_rst') else f'pwr_on_rsts_n[DomainIdx_{fmt_rst(c_rst)}]'
            conns.append(f".pwr_on_rst_ni ( {por_wire} )")
        if c_i.get('has_rt_clk'): conns.append(f".rt_clk_i      ( rtc_i )")

        exported_ports = []
        if (c.name, inst_idx) in comp_extra_conns:
            for hc in comp_extra_conns[(c.name, inst_idx)]:
                m = re.match(r'\.([a-zA-Z0-9_]+)\s*\(', hc)
                if m: exported_ports.append(m.group(1))
                
        # Inject static connections inferred by the generic wiring engine
        for wc in wiring_matrix.get(c.name, []):
            port_name = wc.split('(')[0].strip().strip('.')
            if port_name not in ["clk_i", "rst_ni", "test_mode_i", "id_i", "sys_clk_i", "sys_rst_ni", "rt_clk_i", "pwr_on_rst_ni", "floo_req_o", "floo_rsp_i", "floo_wide_o", "floo_req_i", "floo_rsp_o", "floo_wide_i", "hart_base_id_i", "cluster_base_addr_i", "cluster_base_offset_i", "tile_clk_en_i", "tile_rst_ni", "clk_rst_bypass_i"] and port_name not in exported_ports:
                # Extract the target wire name from the wiring matrix connection
                m_wire = re.match(r'\.[a-zA-Z0-9_]+\s*\(\s*([a-zA-Z0-9_]+)\s*\)', wc)
                if m_wire:
                    wire_name = m_wire.group(1)
                    # If this component has multiple instances, append the mesh coordinates to the wire name to avoid multiple drivers
                    if num_instances > 1 and wire_name != "'0":
                        new_wire = re.sub(rf'({c.name})', rf'\1_{x}_{y}', wire_name)
                        wc = wc.replace(wire_name, new_wire)
                conns.append(wc)
                
        # Inject exported interfaces
        if (c.name, inst_idx) in comp_extra_conns:
            conns.extend(comp_extra_conns[(c.name, inst_idx)])
                
    param_conns = []
    if c.parameters:
        c_info = comp_info.get(c.name, {})
        supported_params = c_info.get("supported_params", {})
        for k, v in c.parameters.items():
            if k in supported_params:
                val = "1'b1" if v is True else "1'b0" if v is False else str(v)
                param_conns.append(f".{k:<17} ( {val} )")
  %>
  // --- ${c.name.upper()} @ (${x}, ${y}) ---
  ${module_type} \
% if param_conns:
  #(
    ${',\n    '.join(param_conns)}
  ) \
% endif
  ${t_name} (
    ${',\n    '.join(conns)}
  );
  % endif
 % endfor
% endfor

endmodule : ${p_name}
