<%
  import re
  from core.utils import simplify_port_ranges
  p_name = config.project.name

  pkg    = config.project.soc_pkg_name
  rpkg   = f"{top_level_module_name}_sys_regs_pkg"
  npkg   = config.project.noc_pkg_name
  host_clk = config.host.clock_domain or "system_clk"
  
  # ============================================================================
  # MAKO TEMPLATE FOR THE SOC TOP-LEVEL (NOC TOPOLOGY)
  # ============================================================================
  # This template generates the absolute Top-Level SystemVerilog module for a 
  # Network-on-Chip (FlooNoC) architecture. It is responsible for:
  # 1. Mapping logical component placements into a strict 2D physical grid.
  # 2. Generating the multidimensional FlooNoC routing matrices.
  # 3. Instantiating all the Tiles and bridging their exported ports to the top.

  # ============================================================================
  # 1. 2D MESH GRID CONSTRUCTION (LOGICAL TO PHYSICAL MAPPING)
  # ============================================================================
  # FlooNoC requires a perfectly rectangular grid: the bounding box is calculated,
  # and empty coordinates are flagged to be filled with 'Dummy Tiles' (pure routers)
  # to maintain physical network continuity.
  comps = [config.host] + config.components
  max_x, max_y = 0, 0
  grid = {}
  
  for c in comps:
      p = getattr(c, 'placement', None)
      if not p or 'logical' not in p: continue
      
      log = p['logical']
      items = log if isinstance(log, list) else [log]
      inst_idx = 0
      for item in items:
          if 'box' in item:
              b = item['box']
              for x in range(b['x_start'], b['x_end']+1):
                  for y in range(b['y_start'], b['y_end']+1):
                      grid[(x,y)] = (c, inst_idx)
                      inst_idx += 1
                      max_x = max(max_x, x)
                      max_y = max(max_y, y)
          else:
              x, y = item['x'], item['y']
              grid[(x,y)] = (c, inst_idx)
              inst_idx += 1
              max_x = max(max_x, x)
              max_y = max(max_y, y)
              
  # Fill unassigned physical coordinates with 'None' to indicate where a Dummy 
  # Tile (a pure FlooNoC router with no attached IP) should be instantiated.
  for x in range(max_x + 1):
      for y in range(max_y + 1):
          if (x,y) not in grid:
              grid[(x,y)] = (None, 0)
              
  # ============================================================================
  # MACRO TARGET PARSING
  # ============================================================================
  # Parses user-defined macro export targets in the format "[x,y].Direction"
  used_edges = set()
  macro_targets = {}
  if config.project.build_mode == "macro" and config.project.macro_settings:
      for t_type in ["slaves", "masters"]:
          items = getattr(config.project.macro_settings, t_type) or []
          for item in items:
              m = re.match(r'\[\s*(\d+)\s*,\s*(\d+)\s*\]\s*\.\s*([A-Za-z]+)', item.target)
              if m:
                  tx, ty, tdir = int(m.group(1)), int(m.group(2)), m.group(3).capitalize()
                  key = (tx, ty, tdir)
                  used_edges.add(key)
                  if key not in macro_targets: macro_targets[key] = {"masters": [], "slaves": []}
                  macro_targets[key][t_type].append(item.bus_type)
%><%namespace file="/license_header.mako" import="license"/>\
${license()}\
//
// AUTOMATICALLY GENERATED BY OLLIVANDER - DO NOT EDIT DIRECTLY
//
// Top-Level SystemVerilog Module for ${p_name.upper()}
// Topology: Network-on-Chip (FlooNoC)
// Mesh Dimensions: ${max_x + 1} x ${max_y + 1}
// (See ${p_name}_noc_map.csv for the 2D grid placement)
//
// OLLIVANDER_MACRO_PRAGMAS_PLACEHOLDER

`include "floo_noc/typedef.svh"
`include "register_interface/typedef.svh"
// Field-wise AXI struct assignment, used at the macro boundary to widen a
// chimney output ID back to the network input width.
`include "axi/assign.svh"

module ${top_level_module_name}
  import ${pkg}::*;
  import ${rpkg}::*;
  import floo_pkg::*;
  import ${npkg}::*;
<%
  # Auto-inject imports from component headers to resolve exported constants and types
  all_imports = set()
  for c in [config.host] + config.components:
      imports = comp_info.get(c.name, {}).get("imports", [])
      for imp in imports:
          if imp not in [pkg, rpkg, "floo_pkg", npkg]:
              all_imports.add(imp)
%>\
% for imp in sorted(all_imports):
  import ${imp}::*;
% endfor
<%
  is_macro = config.project.build_mode == "macro"
  has_macro_types = is_macro and config.project.macro_settings
  ## The exported master of an isle macro is the joined port, whose ID comes from the
  ## interconnect behind it and is published as MacroMstIdWidth. A subtile exports the
  ## network's input type on both directions, so both widths are the same one.
  is_isle_macro = has_macro_types and config.project.macro_settings.export_type == "isle"
  out_id_w = f"{pkg}::MacroMstIdWidth" if is_isle_macro else f"{pkg}::AxiIdWidth"
%>
#(
  // Standard geometry, referenced from the SoC package rather than re-emitted here.
  // These localparams are the module's advertised contract, read by a parent that
  // instantiates it and by the documentation; nothing inside the module uses them. Two
  // copies of the same width is exactly how they came to contradict the package - the
  // widths were computed a second time in this template, and stayed at a hardcoded 10
  // and 4 while the package moved to the resolved values.
  localparam int unsigned AxiAddrWidth = ${pkg}::AxiAddrWidth,
  localparam int unsigned AxiDataWidth = ${pkg}::AxiDataWidth,
  localparam int unsigned AxiUserWidth = ${pkg}::AxiUserWidth,
  localparam int unsigned AxiIdWidth   = ${pkg}::AxiIdWidth${"," if is_macro else ""}
% if is_macro:
  localparam int unsigned AxiInIdWidth  = ${pkg}::AxiIdWidth,
  localparam int unsigned AxiOutIdWidth = ${out_id_w}${"," if has_macro_types else ""}
% endif
% if has_macro_types:
  // Macro Base Address for hardware address translation
  parameter logic [63:0] MACRO_BASE_ADDR = 64'h0,
  // Macro Types for Parent SoC Integration
  parameter type axi_req_t  = ${pkg}::soc_axi_req_t,
  parameter type axi_resp_t = ${pkg}::soc_axi_resp_t,
%   if config.project.macro_settings.masters:
  parameter type axi_master_req_t  = ${pkg}::soc_axi_slv_req_t,
  parameter type axi_master_resp_t = ${pkg}::soc_axi_slv_resp_t,
%   endif
  // Boundary AXI types of a subtile macro, one pair per network. Both the slave
  // and the master port carry the *input* type of the network, which is what a
  // manager attached to a FlooNoC network looks like. FlooNoC compresses IDs
  // across a network (InIdWidth > OutIdWidth), so the output of one chimney can
  // never be handed straight to the input of the next one: the convention is
  // that each side widens its own chimney output back to the input width before
  // exporting it, so the adaptation stays next to the chimney that narrowed the
  // ID and the two boundaries connect directly. Taking these from the SoC
  // package instead would export a single ID and user width for both networks
  // and both directions, which matches neither of them.
  parameter type axi_narrow_req_t  = ${npkg}::axi_narrow_in_req_t,
  parameter type axi_narrow_resp_t = ${npkg}::axi_narrow_in_rsp_t,
  parameter type axi_wide_req_t    = ${npkg}::axi_wide_in_req_t,
  parameter type axi_wide_resp_t   = ${npkg}::axi_wide_in_rsp_t
% endif
)
(
  // Global Clock and Reset
% if config.clock_tree.generators > 0:
  input  logic [${config.clock_tree.generators - 1}:0] domain_clk_i,
  input  logic [${config.clock_tree.generators - 1}:0] clk_gen_lock_i,
  input  logic pwr_on_rst_ni,
% else:
  input  logic clk_i,
  input  logic rst_ni,
  input  logic pwr_on_rst_ni,
% endif
  input  logic test_mode_i,
  input  logic [1:0] boot_mode_i,
<%
  has_rt_clk = any(dom.is_real_time and (dom.source_gen is None or config.clock_tree.generators == 0) for dom in config.clock_tree.domains)
%>\
% if has_rt_clk:
  input  logic rt_clk_i,
% endif
  input  logic clk_rst_bypass_i\
<%
  all_extra_ports_list = list(all_extra_ports)
  if config.project.build_mode == "macro" and config.project.macro_settings:
      if config.project.macro_settings.export_type == "isle":
          if config.project.macro_settings.slaves:
              all_extra_ports_list.extend(["input  axi_req_t  axi_req_i", "output axi_resp_t axi_resp_o"])
          if config.project.macro_settings.masters:
              all_extra_ports_list.extend(["output axi_master_req_t  axi_req_o", "input  axi_master_resp_t axi_resp_i"])
      else:
          if config.project.macro_settings.slaves:
              for slv in config.project.macro_settings.slaves:
                  pfx = "narrow" if slv.bus_type == "narrow" else "wide"
                  all_extra_ports_list.extend([f"input  axi_{pfx}_req_t  axi_{pfx}_req_i", f"output axi_{pfx}_resp_t axi_{pfx}_resp_o"])
          if config.project.macro_settings.masters:
              for mst in config.project.macro_settings.masters:
                  pfx = "narrow" if mst.bus_type == "narrow" else "wide"
                  all_extra_ports_list.extend([f"output axi_{pfx}_req_t  axi_{pfx}_req_o", f"input  axi_{pfx}_resp_t axi_{pfx}_resp_i"])

  # Add explicit RegBus ports for external registers (e.g., located in the padframe)
  if config.system_controller and config.system_controller.external_registers:
      for ext_reg in config.system_controller.external_registers:
          all_extra_ports_list.append(f"output {pkg}::soc_reg_req_t {ext_reg.name}_reg_req_o")
          all_extra_ports_list.append(f"input  {pkg}::soc_reg_rsp_t {ext_reg.name}_reg_rsp_i")
%>\
${"," if all_extra_ports_list else ""}
% if all_extra_ports_list:

  // ---------------------------------------------------------
  // External Component Ports
  // ---------------------------------------------------------
  ${",\n  ".join(all_extra_ports_list)}
% endif
);

  // =========================================================================
  // 1. SYSTEM REGISTERS
  // =========================================================================
  ${top_level_module_name}_sys_regs_pkg::${top_level_module_name}_sys_regs__out_t sys_regs_hwif_out;
  ${top_level_module_name}_sys_regs_pkg::${top_level_module_name}_sys_regs__in_t  sys_regs_hwif_in;

% if config.system_controller and config.system_controller.clk_gen_status_regs:
  assign sys_regs_hwif_in.clk_gen_lock.clk_gen_lock.next  = clk_gen_lock_i;
% endif

% for c in config.components:
 % if c.system_config and c.system_config.get('has_eoc_status'):
  % if c.interrupts and 'eoc_o' in c.interrupts and not c.interrupts['eoc_o'].get('source'):
  assign sys_regs_hwif_in.eoc_status.${c.name}_eoc.next = intr_${c.name}_eoc_o;
  % endif
 % endif
% endfor

<%
  ext_regs = config.system_controller.external_registers if config.system_controller else []
  num_reg_slvs = len(ext_regs) + 1
%>
% if ext_regs:
  ${pkg}::soc_reg_req_t [${num_reg_slvs-1}:0] host_reg_req;
  ${pkg}::soc_reg_rsp_t [${num_reg_slvs-1}:0] host_reg_rsp;
  
  // Connect external register slaves to the Host's RegBus array.
  // Index 0 is reserved for the internal System Controller PCRs.
 % for i, ext_reg in enumerate(ext_regs):
  assign ${ext_reg.name}_reg_req_o = host_reg_req[${i+1}];
  assign host_reg_rsp[${i+1}]      = ${ext_reg.name}_reg_rsp_i;
 % endfor
  assign host_reg_rsp[0] = '0; // Handled internally by the Host Tile
% endif

  // =========================================================================
  // 2. CLOCK AND RESET TREE
  // =========================================================================
  // Root host reset, always present (driven by clock_and_reset_tree).
  // The per-domain vectors `pwr_on_rsts_n` / `rsts_n` are declared by that same
  // macro, but only when the SoC actually has a global reset tree to drive them.
  logic host_pwr_on_rst_n;

% if not has_rt_clk:
  logic rt_clk_i;
  assign rt_clk_i = 1'b0;
% endif

<%namespace file="/hw/infrastructure/clock_reset.mako" import="clock_and_reset_tree"/>\
${clock_and_reset_tree(config, p_name)}

  // =========================================================================
  // 3. FLOONOC 2D MESH ARRAYS
  // =========================================================================
  // These multi-dimensional arrays represent the physical packet-switched links 
  // between adjacent routers in the grid.
  ${npkg}::floo_req_t  [${max_x}:0][${max_y}:0][West:North] tile_req_o, tile_req_i;
  ${npkg}::floo_rsp_t  [${max_x}:0][${max_y}:0][West:North] tile_rsp_o, tile_rsp_i;
  ${npkg}::floo_wide_t [${max_x}:0][${max_y}:0][West:North] tile_wide_o, tile_wide_i;

`ifndef SYNTHESIS
  // SIMULATION-ONLY LINK ACTIVITY COUNTERS, one pair per tile: request and wide
  // flit handshakes on the tile's four cardinal links, both directions. Kept in
  // the top - which is not a hierarchical block on Verilator - as concurrent
  // logic, so that the testbench's progress monitor (+progress) reads a handful
  // of words once per heartbeat instead of scanning 320 hierarchical references
  // on every clock (measured: that made QuestaSim three to four times slower).
  // Free-running; the testbench prints deltas. Sampled on the top clock, which
  // is the NoC clock of every tile in the generated designs.
  int unsigned mon_req_cnt  [${max_x}:0][${max_y}:0];
  int unsigned mon_wide_cnt [${max_x}:0][${max_y}:0];
  for (genvar mx = 0; mx <= ${max_x}; mx++) begin : gen_mon_x
    for (genvar my = 0; my <= ${max_y}; my++) begin : gen_mon_y
      // All handshakes of one cycle are summed into ONE assignment: separate
      // non-blocking increments would keep only the last one and undercount a
      // tile with several links moving at once (the first form did exactly that).
      always_ff @(posedge clk_i) begin
        automatic int unsigned req_n = 0, wide_n = 0;
        for (int md = 0; md < 4; md++) begin
          req_n  += 32'(tile_req_o[mx][my][md].valid  && tile_req_i[mx][my][md].ready);
          req_n  += 32'(tile_req_i[mx][my][md].valid  && tile_req_o[mx][my][md].ready);
          wide_n += 32'(tile_wide_o[mx][my][md].valid && tile_wide_i[mx][my][md].ready);
          wide_n += 32'(tile_wide_i[mx][my][md].valid && tile_wide_o[mx][my][md].ready);
        end
        mon_req_cnt[mx][my]  <= mon_req_cnt[mx][my]  + req_n;
        mon_wide_cnt[mx][my] <= mon_wide_cnt[mx][my] + wide_n;
      end
    end
  end
`endif

  // MESH WIRING GENERATION
  // Generates the bidirectional links connecting adjacent routers. Edge ports 
  // at the chip boundaries are safely tied off to zero to prevent floating inputs.
  
  // 3.1 Horizontal connections (East <-> West)
  for (genvar y = 0; y <= ${max_y}; y++) begin : gen_x_links
    for (genvar x = 0; x < ${max_x}; x++) begin : gen_x_inner
      assign tile_req_i[x+1][y][West] = tile_req_o[x][y][East];
      assign tile_rsp_i[x][y][East]   = tile_rsp_o[x+1][y][West];
      assign tile_wide_i[x+1][y][West]= tile_wide_o[x][y][East];

      assign tile_req_i[x][y][East]   = tile_req_o[x+1][y][West];
      assign tile_rsp_i[x+1][y][West] = tile_rsp_o[x][y][East];
      assign tile_wide_i[x][y][East]  = tile_wide_o[x+1][y][West];
    end
    // East/West Boundaries Tie-Offs
    % if (0, y, 'West') not in used_edges:
    assign tile_req_i[0][y][West] = '0;
    assign tile_rsp_i[0][y][West] = '0;
    assign tile_wide_i[0][y][West] = '0;
    % endif
    
    % if (max_x, y, 'East') not in used_edges:
    assign tile_req_i[${max_x}][y][East] = '0;
    assign tile_rsp_i[${max_x}][y][East] = '0;
    assign tile_wide_i[${max_x}][y][East] = '0;
    % endif
  end

  // 3.2 Vertical connections (North <-> South)
  for (genvar x = 0; x <= ${max_x}; x++) begin : gen_y_links
    for (genvar y = 0; y < ${max_y}; y++) begin : gen_y_inner
      assign tile_req_i[x][y+1][South] = tile_req_o[x][y][North];
      assign tile_rsp_i[x][y][North]   = tile_rsp_o[x][y+1][South];
      assign tile_wide_i[x][y+1][South]= tile_wide_o[x][y][North];

      assign tile_req_i[x][y][North]   = tile_req_o[x][y+1][South];
      assign tile_rsp_i[x][y+1][South] = tile_rsp_o[x][y][North];
      assign tile_wide_i[x][y][North]  = tile_wide_o[x][y+1][South];
    end
    // North/South Boundaries Tie-Offs
    % if (x, 0, 'South') not in used_edges:
    assign tile_req_i[x][0][South] = '0;
    assign tile_rsp_i[x][0][South] = '0;
    assign tile_wide_i[x][0][South] = '0;
    % endif
    
    % if (x, max_y, 'North') not in used_edges:
    assign tile_req_i[x][${max_y}][North] = '0;
    assign tile_rsp_i[x][${max_y}][North] = '0;
    assign tile_wide_i[x][${max_y}][North] = '0;
    % endif
  end

  // =========================================================================
  // 4. TILE INSTANTIATIONS
  // =========================================================================
  // Iterates over every coordinate in the calculated 2D mesh. 
  // It instantiates either a Functional Tile (wrapper containing the IP and a 
  // Chimney adapter) or a Dummy Tile (a pure router node for traffic forwarding 
  // without an attached local IP).
% for inst_name, inst in ir.instances.items():
  // --- Tile / Component: ${inst.inst_name} (${inst.module_name}) ---
  ${inst.module_name} \
  % if inst.parameters:
  #(
    % for idx, (k, v) in enumerate(inst.parameters.items()):
    .${k.ljust(17)} ( ${v} )${"," if idx < len(inst.parameters) - 1 else ""}
    % endfor
  ) \
  % endif
  ${inst.inst_name} (
    % for idx, conn in enumerate(inst.connections):
    .${conn.port_name.ljust(17)} ( ${conn.expression} )${"," if idx < len(inst.connections) - 1 else ""}
    % endfor
  );

% endfor

  // =========================================================================
  // 5. MACRO NOC ADAPTERS (CHIMNEY / JOIN)
  // =========================================================================
% if config.project.build_mode == "macro" and macro_targets:
 % for (tx, ty, tdir), info in macro_targets.items():
  // --- Border Adapter @ [${tx}, ${ty}] ${tdir} ---
  <%
    is_isle = config.project.macro_settings.export_type == "isle"
    has_slaves = len(info["slaves"]) > 0
    has_masters = len(info["masters"]) > 0
    
    has_narrow_in = has_slaves and ("narrow" in info["slaves"] or not is_isle)
    has_wide_in = has_slaves and ("wide" in info["slaves"] or is_isle)
    has_narrow_out = has_masters and ("narrow" in info["masters"] or is_isle)
    has_wide_out = has_masters and ("wide" in info["masters"] or is_isle)
    
    c_name = f"border_{tx}_{ty}_{tdir}"
  %>
  ${npkg}::id_t ${c_name}_id;
  assign ${c_name}_id.x = ${tx} ${'- 1' if tdir == 'West' else '+ 1' if tdir == 'East' else ''};
  assign ${c_name}_id.y = ${ty} ${'- 1' if tdir == 'South' else '+ 1' if tdir == 'North' else ''};
  
  // The signals around the border chimney carry the network's own types, one per
  // direction: the chimney packs InIdWidth bits on its input ports and
  // OutIdWidth on its output ports, so a single type for both would mismatch one
  // of the two inside the IP.
  ${npkg}::axi_narrow_in_req_t  ${c_name}_narrow_in_req;
  ${npkg}::axi_narrow_in_rsp_t  ${c_name}_narrow_in_rsp;
  ${npkg}::axi_narrow_out_req_t ${c_name}_narrow_out_req;
  ${npkg}::axi_narrow_out_rsp_t ${c_name}_narrow_out_rsp;
  ${npkg}::axi_wide_in_req_t    ${c_name}_wide_in_req;
  ${npkg}::axi_wide_in_rsp_t    ${c_name}_wide_in_rsp;
  ${npkg}::axi_wide_out_req_t   ${c_name}_wide_out_req;
  ${npkg}::axi_wide_out_rsp_t   ${c_name}_wide_out_rsp;
  
  ${npkg}::floo_req_t  ${c_name}_floo_req_o, ${c_name}_floo_req_i;
  ${npkg}::floo_rsp_t  ${c_name}_floo_rsp_o, ${c_name}_floo_rsp_i;
  ${npkg}::floo_wide_t ${c_name}_floo_wide_o, ${c_name}_floo_wide_i;
  
  assign tile_req_i[${tx}][${ty}][${tdir}] = ${c_name}_floo_req_o;
  assign ${c_name}_floo_req_i = tile_req_o[${tx}][${ty}][${tdir}];
  
  assign tile_rsp_i[${tx}][${ty}][${tdir}] = ${c_name}_floo_rsp_o;
  assign ${c_name}_floo_rsp_i = tile_rsp_o[${tx}][${ty}][${tdir}];
  
  assign tile_wide_i[${tx}][${ty}][${tdir}] = ${c_name}_floo_wide_o;
  assign ${c_name}_floo_wide_i = tile_wide_o[${tx}][${ty}][${tdir}];
  
  floo_nw_chimney #(
    .AxiCfgN             ( ${npkg}::AxiCfgN ),
    .AxiCfgW             ( ${npkg}::AxiCfgW ),
    .ChimneyCfgN         ( floo_pkg::set_ports(floo_pkg::ChimneyDefaultCfg, ${"1'b1" if has_narrow_out else "1'b0"}, ${"1'b1" if has_narrow_in else "1'b0"}) ),
    .ChimneyCfgW         ( floo_pkg::set_ports(floo_pkg::ChimneyDefaultCfg, ${"1'b1" if has_wide_out else "1'b0"}, ${"1'b1" if has_wide_in else "1'b0"}) ),
    .RouteCfg            ( ${pkg}::RouteCfgNoMcast ),
    .AtopSupport         ( 1'b1 ),
    .WideRwDecouple      ( ${npkg}::WideRwDecouple ),
    .VcImpl              ( ${npkg}::VcImpl ),
    .MaxAtomicTxns       ( 3 ),
    .Sam                 ( ${npkg}::Sam ),
    .sam_rule_t          ( ${npkg}::sam_rule_t ),
    .id_t                ( ${npkg}::id_t ),
    .rob_idx_t           ( ${npkg}::rob_idx_t ),
    .hdr_t               ( ${npkg}::hdr_t ),
    .axi_narrow_in_req_t ( ${npkg}::axi_narrow_in_req_t ),
    .axi_narrow_in_rsp_t ( ${npkg}::axi_narrow_in_rsp_t ),
    .axi_narrow_out_req_t( ${npkg}::axi_narrow_out_req_t ),
    .axi_narrow_out_rsp_t( ${npkg}::axi_narrow_out_rsp_t ),
    .axi_wide_in_req_t   ( ${npkg}::axi_wide_in_req_t ),
    .axi_wide_in_rsp_t   ( ${npkg}::axi_wide_in_rsp_t ),
    .axi_wide_out_req_t  ( ${npkg}::axi_wide_out_req_t ),
    .axi_wide_out_rsp_t  ( ${npkg}::axi_wide_out_rsp_t ),
    .floo_req_t          ( ${npkg}::floo_req_t ),
    .floo_rsp_t          ( ${npkg}::floo_rsp_t ),
    .floo_wide_t         ( ${npkg}::floo_wide_t )
  ) i_chimney_${c_name} (
    .clk_i               ( ${host_clk} ),
    .rst_ni              ( host_pwr_on_rst_n ),
    .id_i                ( ${c_name}_id ),
    .test_enable_i       ( test_mode_i ),
    .route_table_i       ( '0 ),
    .sram_cfg_i          ( '0 ),
    .axi_narrow_in_req_i ( ${c_name}_narrow_in_req ),
    .axi_narrow_in_rsp_o ( ${c_name}_narrow_in_rsp ),
    .axi_narrow_out_req_o( ${c_name}_narrow_out_req ),
    .axi_narrow_out_rsp_i( ${c_name}_narrow_out_rsp ),
    .axi_wide_in_req_i   ( ${c_name}_wide_in_req ),
    .axi_wide_in_rsp_o   ( ${c_name}_wide_in_rsp ),
    .axi_wide_out_req_o  ( ${c_name}_wide_out_req ),
    .axi_wide_out_rsp_i  ( ${c_name}_wide_out_rsp ),
    .floo_req_o          ( ${c_name}_floo_req_o ),
    .floo_rsp_o          ( ${c_name}_floo_rsp_o ),
    .floo_wide_o         ( ${c_name}_floo_wide_o ),
    .floo_req_i          ( ${c_name}_floo_req_i ),
    .floo_rsp_i          ( ${c_name}_floo_rsp_i ),
    .floo_wide_i         ( ${c_name}_floo_wide_i )
  );

  % if is_isle:
   % if has_slaves:
  always_comb begin
    ${c_name}_wide_in_req = axi_req_i;
    ${c_name}_wide_in_req.aw.addr = axi_req_i.aw.addr - MACRO_BASE_ADDR;
    ${c_name}_wide_in_req.ar.addr = axi_req_i.ar.addr - MACRO_BASE_ADDR;
  end
  assign axi_resp_o = ${c_name}_wide_in_rsp;
  assign ${c_name}_narrow_in_req = '0;
   % endif
   % if has_masters:
  floo_nw_join #(
    .AxiCfgN         ( floo_pkg::axi_cfg_swap_iw(${npkg}::AxiCfgN) ),
    .AxiCfgW         ( floo_pkg::axi_cfg_swap_iw(${npkg}::AxiCfgW) ),
    .AxiCfgJoin      ( floo_pkg::axi_cfg_swap_iw(floo_pkg::axi_join_cfg(${npkg}::AxiCfgN, ${npkg}::AxiCfgW)) ),
    .EnAtopAdapter   ( 1'b0 ), 
    .AtopUserAsId    ( 1'b1 ), 
    .axi_narrow_req_t( ${npkg}::axi_narrow_out_req_t ),
    .axi_narrow_rsp_t( ${npkg}::axi_narrow_out_rsp_t ),
    .axi_wide_req_t  ( ${npkg}::axi_wide_out_req_t ),
    .axi_wide_rsp_t  ( ${npkg}::axi_wide_out_rsp_t ),
    .axi_req_t       ( axi_master_req_t ),
    .axi_rsp_t       ( axi_master_resp_t )
  ) i_join_${c_name} (
    .clk_i           ( ${host_clk} ),
    .rst_ni          ( host_pwr_on_rst_n ),
    .test_enable_i   ( test_mode_i ),
    .axi_narrow_req_i( ${c_name}_narrow_out_req ),
    .axi_narrow_rsp_o( ${c_name}_narrow_out_rsp ),
    .axi_wide_req_i  ( ${c_name}_wide_out_req ),
    .axi_wide_rsp_o  ( ${c_name}_wide_out_rsp ),
    .axi_req_o       ( axi_req_o ),
    .axi_rsp_i       ( axi_resp_i )
  );
   % endif
  % else:
   % if "narrow" in info["slaves"]:
  always_comb begin
    ${c_name}_narrow_in_req = axi_narrow_req_i;
    ${c_name}_narrow_in_req.aw.addr = axi_narrow_req_i.aw.addr - MACRO_BASE_ADDR;
    ${c_name}_narrow_in_req.ar.addr = axi_narrow_req_i.ar.addr - MACRO_BASE_ADDR;
  end
  assign axi_narrow_resp_o = ${c_name}_narrow_in_rsp;
   % else:
  assign ${c_name}_narrow_in_req = '0;
   % endif
   % if "wide" in info["slaves"]:
  always_comb begin
    ${c_name}_wide_in_req = axi_wide_req_i;
    ${c_name}_wide_in_req.aw.addr = axi_wide_req_i.aw.addr - MACRO_BASE_ADDR;
    ${c_name}_wide_in_req.ar.addr = axi_wide_req_i.ar.addr - MACRO_BASE_ADDR;
  end
  assign axi_wide_resp_o = ${c_name}_wide_in_rsp;
   % else:
  assign ${c_name}_wide_in_req = '0;
   % endif
   % if "narrow" in info["masters"]:
  // The chimney output carries OutIdWidth, the boundary carries InIdWidth: the
  // field-wise assignment widens the ID on the way out and truncates it back on
  // the response, which is lossless because the extension is a zero-extension of
  // the same value. A whole-struct assignment would instead misalign every field,
  // 'id' being the first member and therefore the most significant bits.
  `AXI_ASSIGN_REQ_STRUCT(axi_narrow_req_o, ${c_name}_narrow_out_req)
  `AXI_ASSIGN_RESP_STRUCT(${c_name}_narrow_out_rsp, axi_narrow_resp_i)
   % else:
  assign ${c_name}_narrow_out_rsp = '0;
   % endif
   % if "wide" in info["masters"]:
  `AXI_ASSIGN_REQ_STRUCT(axi_wide_req_o, ${c_name}_wide_out_req)
  `AXI_ASSIGN_RESP_STRUCT(${c_name}_wide_out_rsp, axi_wide_resp_i)
   % else:
  assign ${c_name}_wide_out_rsp = '0;
   % endif
  % endif
 % endfor
% endif

endmodule : ${top_level_module_name}
